### ISSUE TITLE
<pfe-accordion> has issues with chevron direction

### ISSUE THREAD

**Issue by chrisdo1** [patternfly/patternfly-elements#1002]
## Description of the issue

1. When I expand a disclosure element (This is a pfe-accordion with only one header-panel pairing) and hover over the button, I see the text and chevron shift to the left. 
2. On the regular accordion, the chevron points the wrong directions, [see design specs](https://github.com/patternfly/patternfly-elements/issues/877)
3. On the disclosure version of the accordion, the chevron points the wrong directions [see design specs](https://github.com/patternfly/patternfly-elements/issues/877)

### Impacted component(s)

- pfe-accordion

#### Steps to reproduce item 1

1. Go to the pfe-accordion demo page: http://localhost:8000/elements/pfe-accordion/demo/
2. Scroll to the Disclosure
3. Expand the disclosure
4. Hover over the header (button)

#### Steps to reproduce item 2

1. Go to the pfe-accordion demo page: http://localhost:8000/elements/pfe-accordion/demo/
2. Notice that the chevron points down and it should point to the right when closed
3. Expand the accordion
5. Notice that the chevron points up, and it should point down when open

#### Steps to reproduce item 3

1. Go to the pfe-accordion demo page: http://localhost:8000/elements/pfe-accordion/demo/
2. Scroll to the Disclosure
3. Notice that the chevron points down and it should point to the right when closed
4. Expand the disclosure
5. Notice that the chevron points to the right, and it should point down when open

### Expected behavior

- The text and chevron should remain fixed on hover.
- The thicker border should be on the left and should be an accent color on pfe-nav (accordion)

### Screenshots

![accordion-hover](https://user-images.githubusercontent.com/32456107/88294085-d313bb80-ccc9-11ea-855d-7222e9ad530d.gif)

prod: redhat.com/search/linux
![image](https://user-images.githubusercontent.com/456863/88673987-3aa97c80-d0b7-11ea-93ac-efdc7c15415e.png)

https://rally1.rallydev.com/#/detail/defect/aaca0dbc-bf59-41a8-a0ad-12089bafb9cd?fdp=true

**Comment by starryeyez024** [comment]
I think the mobile nav (which uses accordion)  is also impacted.
Prod:
![image](https://user-images.githubusercontent.com/456863/88319518-49281a80-ccea-11ea-8aa4-7962c5d56cb8.png)

current state of master branch:
![image](https://user-images.githubusercontent.com/456863/88319238-e2a2fc80-cce9-11ea-8aba-f98240745b9e.png)

**Comment by starryeyez024** [comment]
Resolved:

>  When I expand a disclosure element (This is a pfe-accordion with only one header-panel pairing) and hover over the button, I see the text and chevron shift to the left. 
>  On the disclosure version of the accordion, the chevron points the wrong directions

Still needs to be addressed:

> On the regular accordion, the chevron points the wrong directions

**Comment by starryeyez024** [comment]
closing in favor of one issue to address all chevron concerns: https://github.com/patternfly/patternfly-elements/issues/1512
