### ISSUE TITLE
pfe-navigation 1.x issues with borders

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#1006]
## Description of the issue

In the mobile view of pfe-navigation, the accent color is missing in some circumstances 

### Impacted component(s)

- pfe-navigation  

### Steps to reproduce

1. Go to [the nav demo page](https://deploy-preview-1004--happy-galileo-ea79c4.netlify.app/elements/pfe-navigation/demo/)
2. Click on the menu hamburger icon
3. click on a menu item like products
4. Notice that there is a gray border across the top instead of an accent color border on the left.

### Screenshots

current state of master branch:
![image](https://user-images.githubusercontent.com/456863/88319238-e2a2fc80-cce9-11ea-8aba-f98240745b9e.png)

vs redhat.com: 
![image](https://user-images.githubusercontent.com/456863/88319693-8391b780-ccea-11ea-9765-8fc612d5f05a.png)

## Related issues

- https://github.com/patternfly/patternfly-elements/issues/1002

**Comment by castastrophe** [comment]
Rally: #US261998 https://rally1.rallydev.com/#/detail/userstory/399031068408

**Comment by castastrophe** [comment]
This appears to have been fixed.  This is the master branch: https://patternfly-elements.netlify.app/elements/pfe-navigation/demo/

![image](https://user-images.githubusercontent.com/1840295/119229838-be6da300-bae7-11eb-8b12-6b82c8a5e9b4.png)
