### ISSUE TITLE
Resilient npm dev task

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#108]
Can the `npm run dev` task throw errors but not stop running if it encounters an error? Its maddening to think your code is not working but really the task runner has just stopped running silently.

**Comment by mwcz** [comment]
@starryeyez024 RHElements doesn't have a `npm run dev` task.  Could you be using `npm start`?

**Comment by kylebuch8** [comment]
@starryeyez024 I think we can close this. I've tested introducing errors into the code and I see that the dev task continues to run. Then when I fix the error, everything runs smoothly.
