### ISSUE TITLE
[fix] pfe-tabs | vertically align tab text

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#1086]
If tabs have text which is stacking to two lines, currently the text is top-aligned.
![image](https://user-images.githubusercontent.com/456863/92522725-32cc1480-f1ed-11ea-8368-0a9de1ec9e74.png)

The tab text should be vertically aligned:
![image](https://user-images.githubusercontent.com/456863/92522783-44adb780-f1ed-11ea-8c61-e484c1692312.png)

```
.product-tabs pfe-tab{
    display: flex;
    align-items: center;
}
```

**Comment by castastrophe** [comment]
@coreyvickery Can I get your thumbs up on this request when you get a chance?

**Comment by coreyvickery** [comment]
@castastrophe Looks good until we implement the overflow scrolling feature.

**Comment by castastrophe** [comment]
@coreyvickery Is the idea that once overflow scrolling exists, we won't overflow content inside a tab?

**Comment by castastrophe** [comment]
cc @kylebuch8 ^

**Comment by coreyvickery** [comment]
@castastrophe @kylebuch8 I wouldn't think so, unless there are lots of tab labels with really long names, which we might have to break as a worst case scenario.

**Comment by starryeyez024** [comment]
This is obsolete now since the tabs scroll.
