### ISSUE TITLE
pfe-navigation: Discuss header

### ISSUE THREAD

**Issue by wesruv** [patternfly/patternfly-elements#1105]
Making this to continue a discussion from a doc because comment columns in googles docs aren't cutting it.

Here's the designs I have:
* Openshift: https://xd.adobe.com/view/9c0d6be5-0bc1-4b0a-ae90-66cf10dfcb51-c95e/screen/f2c2da14-f6b1-48fe-ab6a-a58a9b010d4a/
* Ansible: https://xd.adobe.com/view/c63b9720-6d43-4ba0-b8b1-3252f9201c91-9368/screen/6fb32b9e-0bff-4948-b602-b5761af102be
* Customer Portal ![CP_pfe-nav](https://user-images.githubusercontent.com/5607236/93915889-ad5d5f80-fcd6-11ea-8057-7402735a1d8d.png)

Here's the existing discussion:

@castastrophe 
For discussion: Should the navigation provide the header tag or do we provide guidance in the README for the component that the `pfe-navigation` tag should be inserted into a header tag? It is suggested in the spec that the header tag would contain the logos and site title (and often contains navigation as well). I think those potentially belong outside of the nav tag so the `pfe-navigation` could use the role of banner instead, and we can add a nav tag around the list containing site links.

@kelsS 
I have also been thinking on this as well and would love to brainstorm about it.

@wesruv 
I hadn't considered this yet, I think there's a chance there's more that could go in a header tag than the navigation, so I'm leaning towards "recommend they put pfe-nav in a header tag"

@castastrophe 
Well what would go in the header tag includes the name of the site and the logo but those are all in pfe-navigation so I'm thinking pfe-navigation is technically a header component that contains a nav

**Comment by wesruv** [comment]
So the Customer Portal mock shows what I'm thinking of, what if there's additional navigation outside of what is in PFE-nav, e.g. breadcrumbs or those 'quick links'. I could see other 'header-ish' things existing outside of pfe-nav.

So I think this is an area for guidance on implementation, but I don't know that I'd enforce pfe-navigation being the header

**Comment by kelsS** [comment]
Adding some notes here from our meeting, we discussed and decided to add the role banner into the component and add a flag or empty role feature to turn off the banner role so that someone can treat pfe-nav as not the header if they need too. But pfe-nav will be treated as the banner by default. I will make a Jira ticket for the feature.

**Comment by castastrophe** [comment]
@kelsS @wesruv Has this been resolved?  Do we still need this issue?

**Comment by wesruv** [comment]
I think so, the solution we landed on was we're adding `role="header"` with JS if there isn't a role on `pfe-navigation` and if it doesn't have a parent `header, [role=header]`. Feel free to reopen if that poses any issues.
