### ISSUE TITLE
pfe-tab wind variant should use both background variables

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#1123]
## Description of the issue

There are two background variables for pfe tabs:  `--pfe-tabs--BackgroundColor` and  `--pfe-tabs--BackgroundColor--inactive`.  The earth variant leverages both, but wind does not.

### Impacted component(s)

- pfe-tabs

### Steps to reproduce

1. Go to the pfe-tabs demo page 
2. add these style overrides
```
:root {
    --pfe-tabs--BackgroundColor: pink !important;
    --pfe-tabs--BackgroundColor--inactive: beige !important;
}
```
3. Notice that **all** the wind tabs inherit the (active) background color variable.

### Expected behavior

Only the active wind tab should be pink, the other tabs should be beige.

### Screenshots

![image](https://user-images.githubusercontent.com/456863/94957119-3c2e6100-04bb-11eb-9ffd-ecb628b7aabf.png)

**Comment by castastrophe** [comment]
Shouldn't the tabs in wind always be transparent?
