### ISSUE TITLE
keep gulp watch running when errors occur

### ISSUE THREAD

**Issue by mwcz** [patternfly/patternfly-elements#113]
Requested by @starryeyez024, gulp watch should not abort when an error, such as a SASS compilation error, is encountered.

It seems pretty easy based on a cursory search.  Might be able to write our own [error handler](https://github.com/gulpjs/gulp/blob/master/docs/API.md#fn-1) which logs but doesn't abort.

**Comment by castastrophe** [comment]
This is resolved
