### ISSUE TITLE
move generator into monorepo

### ISSUE THREAD

**Issue by mwcz** [patternfly/patternfly-elements#114]
The generator is the only package that exists outside of the monorepo.  I'd like to move it into the monorepo, perhaps with this directory structure:

```
├── elements
│   ├── all
│   ├── the
│   └── elements
├── themes
│   ├── all
│   ├── the
│   └── themes
└── utils
    ├── generator-rhelement
    └── and other utils if needed
```

This way the generator is easy to find, shares issues and PRs, and we can run tests on the generator at the same time as the rest of the repo.

@kylebuch8 what do you think?

**Comment by mwcz** [comment]
Could even create another dir for @Homa's framework integration examples. 
```
├── elements
│   ├── all
│   ├── the
│   └── elements
├── themes
│   ├── all
│   ├── the
│   └── themes
├── examples
│   ├── all
│   ├── the "compound"
│   └── examples with multiple RHElements
└── utils
    ├── generator-rhelement
    └── and other utils if needed
```

**Comment by kylebuch8** [comment]
@mwcz I'm good with pulling it in. Just as long as we can keep publishing it separately (which I know won't be an issue).
