### ISSUE TITLE
IE11 | pfe-navigation rendering

### ISSUE THREAD

**Issue by castastrophe** [patternfly/patternfly-elements#1174]
## Description of the issue

![pfe-navigation](https://user-images.githubusercontent.com/1840295/98558191-2444bc80-2273-11eb-9cad-5a9dc82de226.png)

The navigation bar in IE11 is a bit too tall such that the highlighted active item does not appear connected to the open tray.

### Impacted component(s)

- pfe-navigation

### Steps to reproduce

1. Go to the Navigation demo page in IE11
2. Click on the Products tray

### Expected behavior

Set a height maximum possibly on the navigation bar scoped for IE11

**Comment by starryeyez024** [comment]
It's better than it was in the screenshot, and we are moving towards graceful degradation anyhow. Closing this one out.

![image](https://user-images.githubusercontent.com/456863/113437684-107e2c00-93b5-11eb-9f4b-b5148a028959.png)
