### ISSUE TITLE
pfe-content-set does not work within an iframe

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#1182]
https://webrh-patternkit.int.open.paas.redhat.com/schema/content_set_band

When you click on the tabs, it does not load the correct content frame.

Per Kyle, "It has to do with pushState."

**Comment by castastrophe** [comment]
I'm not sure if this is enough of a fix for you but I wrapped it in a try/catch so that it would stop throwing blocking errors in PatternKit
