### ISSUE TITLE
.pfe-l-grid-fill-height + pfe-band grid

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#1216]
## Description of the issue

The styles 
```
.pfe-l-grid.pfe-l-grid-fill-height {
    height: 100%;
}
```
don't work well with the default slot in the pfe-band. Not sure if this is intentional or outside the expectations of those classes. It's causing the content to expand past the band body area:

![image](https://user-images.githubusercontent.com/456863/101636575-87a04680-39f9-11eb-858d-8094f1dadb6f.png)

### Impacted component(s)

- pfe-band

### Steps to reproduce

1. Go to 'https://patternflyelements.com/examples/
2. Notice the pfe-ctas are overlapping into the gray band below. 

### Expected behavior

I would expect the content to stay contained within the band body area.

**Comment by castastrophe** [comment]
I can no longer reproduce this issue.  If you see it come up again, please re-open!  Thanks!
