### ISSUE TITLE
IE11 Demo site white screening

### ISSUE THREAD

**Issue by heyMP** [patternfly/patternfly-elements#1243]
## Description of the issue

The demo pages aren't loading IE11. It appears to be attempting to load some sass files.

### Steps to reproduce

1. In IE11 https://happy-galileo-ea79c4.netlify.app
6. You should be seeing a white screen

### Expected behavior

It should be loading as it does in all other browsers.

### Screenshots

![Screen Shot 2020-12-21 at 3 10 31 PM](https://user-images.githubusercontent.com/3428964/102818910-816a7c80-43a0-11eb-9ab2-bb77d13c08c1.png)

**Comment by castastrophe** [comment]
Here's a link without having to pull down the branch: https://happy-galileo-ea79c4.netlify.app/elements/pfe-band/demo/

**Comment by heyMP** [comment]
I can now only get this issue when running a local dev server.  I'm now getting an error loading "source maps".  Which makes sense.  
![Screen Shot 2020-12-21 at 3 56 06 PM](https://user-images.githubusercontent.com/3428964/102821627-69e1c280-43a5-11eb-8eec-f6241c0bd6b2.png)

**Comment by castastrophe** [comment]
Is this still an issue @heyMP ?
