### ISSUE TITLE
Ability to choose prefix for randomId()

### ISSUE THREAD

**Issue by wesruv** [patternfly/patternfly-elements#1251]
In working on #1230 and wanted to make a unique ID for something, checked out randomId() from the base class but it prefixes the ID with `pfe-` and I was hoping to add something more descriptive to the ID for any dev looking at the DOM.

In my code my ideal is `pfe-detail-toggle-######`, I was hoping we could add a param to randomId, e.g.

`randomId(idPrefix = prefix) {`

But it's a getter, so it can't have a param. I don't know the finer points of Classes, or getters, or setters, so I don't know if trying to get this change in would be breaking.

### Impacted component(s)

- pfe-accordion
- pfe-content-set
- pfe-icon
- pfe-jump-links-nav
- pfe-modal
- pfe-tab-panel
- pfe-tab

## Related issues

- (#1230) Add PFE-Primary-Detail (component that's in PF React)

**Comment by wesruv** [comment]
Related conversation: https://github.com/patternfly/patternfly-elements/pull/1230#discussion_r542546031

**Comment by castastrophe** [comment]
Code in question:

```
  /**
   * A quick way to fetch a random ID value.
   * _Note:_ All values are prefixes with `pfe` automatically to ensure an ID-safe value is returned.
   *
   * @example: In a component's JS: `this.id = this.randomID;`
   */
  get randomId() {
    return (
      `${prefix}-` +
      Math.random()
        .toString(36)
        .substr(2, 9)
    );
  }
  ```

**Comment by castastrophe** [comment]
We could just replace `${prefix}` with `${this.tag}` 🤷‍♀️

**Comment by castastrophe** [comment]
I don't have an opinion either way though I will point out that since this is a randomly generated ID, it will be different on every load of the page so there's not much value to authors consuming the components.  They're mostly useful for accessibility wiring and internal connections for the component.

**Comment by wesruv** [comment]
Right, my point with a human friendly name is so they can understand what's going on with useful naming that ties to code and documentation, not so they can select by it.

**Comment by wesruv** [comment]
I find great value in being able to look at the DOM to help understand functionality.

The html tag and it's necessary attributes don't usually paint a full picture of how things are being used. We aren't using classes (because we don't need to) and with BEM those are very helpful in understanding intent. In this case I need an ID and I find it helpful to give a clue what this element is being used for with words used in the code and documentation.

In my case I don't think there's a great reason to create a sub component, which would help semantically, but creates overhead of managing the a11y of a custom element and the (small) cost of bootstrapping the custom element.

**Comment by wesruv** [comment]
Maybe it's more helpful to first know:
Is it a breaking change to change a getter to a function that accepts a param, but has the same output if it's called without the param being filled?

I suspect @kylebuch8 @castastrophe or @mwcz may know off the top of their head how much of a problem that might be?

**Comment by wesruv** [comment]
https://github.com/patternfly/patternfly-elements/blob/master/elements/pfe-accordion/src/pfe-accordion.js#L415

Looks like this issue has come up in another place, but we're doing extra string processing to fix it

**Comment by wesruv** [comment]
Pecked around a bit more, I would consider this a breaking change if we changed the getter to a method, because calling it we'd have to say `element.randomId()` instead of `element.randomId`.

So that stinks.

**Comment by kylebuch8** [comment]
@wesruv - Just to clarify. In JavaScript, a getter cannot receive a parameter. The [MDN documentation states](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get#Description)
> It must have exactly zero parameters

**Comment by wesruv** [comment]
Yarr, I think this is more thought than it's worth, closing!
