### ISSUE TITLE
pfe-audio-player

### ISSUE THREAD

**Issue by dcaryll** [patternfly/patternfly-elements#1254]
# Component name: PFE Audio Player

> An audio player is a set of interactive playback controls used to play audio clips.

## Design specification

Need to consult with Aaron Williamson for use cases for Podcasts and Kelsey Cannon for analytics needs

## Accessibility

TBD

## Interaction

TBD

## Analytics

Custom events needed. Need to consult with Kelsey Cannon on tracking.

**Comment by castastrophe** [comment]
Possible tool we can extend: https://github.com/elmsln/lrnwebcomponents/tree/master/elements/a11y-media-player

**Comment by castastrophe** [comment]
Some example components:
- https://github.com/davatron5000/podcast-player/tree/lit-version
- https://github.com/LRNWebComponents/a11y-media-player

**Comment by castastrophe** [comment]
TODO Research SRT format for transcript

**Comment by castastrophe** [comment]
What formats does https://www.rev.com/ provide and how can we consume those outputs directly?

**Comment by castastrophe** [comment]
Look to https://simplecast.com for what kind of analytics they provide

**Comment by castastrophe** [comment]
RSS feed https://feeds.pacific-content.com/commandlineheroes

**Comment by coreyvickery** [comment]
@castastrophe Do you have what you need to get started on the `pfe-audio-player` MVP? From my interpretation, it seems like the following are the most important features that are being requested.

[X] = ranking number ([spreadsheet](https://docs.google.com/spreadsheets/d/1quuxkd0LTVf7Qp6bXlwIKyIwiny8T-HUod0Qo9yXDDk/edit#gid=0))

* Support for compact player [20]
* Basic controls (play, pause) [20]
* Time (current, remaining) [18]
* Adjust volume via slider [17]
* Mute/volume on [16]
* Subscribe (links to podcast platforms, if applicable) [16]
* Support for full player [15]
* Metadata (title, description, supporting text) [15]
* Advanced controls (rewind by X seconds, fast forward by X seconds) [15]
* Support for mini player [14]
* Thumbnail image [14]

I can put together more designs with these features only if that would be helpful.

**Comment by coreyvickery** [comment]
@castastrophe @heyMP See link below for detailed specs.

https://xd.adobe.com/view/6f46d2c1-deb2-4f6e-a8e3-7b92b06c2cad-3a15/

**Comment by methomps** [comment]
@bennypowers @marionnegp does it make sense to transfer this issue over into our RHDS space and update with relevant links, etc?

**Comment by marionnegp** [comment]
@methomps, I think so. I don't see an audio player as a component in PatternFly.

**Comment by bennypowers** [comment]
Yes, let's do this in RHDS -> https://github.com/RedHat-UX/red-hat-design-system/issues/317
