### ISSUE TITLE
CI: Remove the build from the test command

### ISSUE THREAD

**Issue by castastrophe** [patternfly/patternfly-elements#1256]
Currently CI runs a build and then fires the test suite and visual regression tests concurrently.  The test command includes another build of the project which is duplicative.  Need to allow for the build to be turned off on the `npm run test` command.

**Comment by Prototype4988** [comment]
Hi, I would like to work on this issue as i am a beginner in open source kindly guide me how to fix this issue

**Comment by castastrophe** [comment]
#If I reminder correctly, there is a build false flag in the test.js node script but the script had a bug in it so we didn't update the package.json to use it yet. @kylebuch8 do you happen to remember what that bug was?

**Comment by castastrophe** [comment]
This is the WIP I have in place already: https://github.com/patternfly/patternfly-elements/pull/1326
