### ISSUE TITLE
Reduce padding on the pfe-jump-links

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#1274]
## Description of the issue

Currently the jump links component has 16px of padding all the way around each edge, and then an additional chunk of padding comes from the accordion-panel in the shadow DOM. 

1. The default padding on the left edge is about 60px, which is very large
2. Half of this padding comes from jump links (16px all around), the other half is from the accordion panel container (which has 24px padding on the left & right)
3. The accordion panel padding cannot be overridden.
 
### Impacted component(s)

- pfe-jump-links
- pfe-accordion

### Expected behavior

1. The jump links content should be 0px from the edges by default.  If an author desires padding + styles around it, the component can be placed in a card.
2. The jump links component should override the CSS variables for the accordion panel container

### Steps to reproduce

1. Go to https://patternflyelements.com/elements/pfe-jump-links/demo/
2. Inspect the jump links component and notice that the padding and background colors ship with the component, but there's no attribute to opt out.
3. Add inline styles on the pfe-jump-links or the document root:
```
 --pfe-accordion__panel-container--Padding: 0;
```
notice nothing happens. 

 

#### Current amount of spacing:
![image](https://user-images.githubusercontent.com/456863/104664163-91723500-569c-11eb-80ed-a3df45a604a3.png)
from: https://patternflyelements.com/elements/pfe-jump-links/demo/

#### Mockups often show jump links content aligning with the left edge of layouts:
![image](https://user-images.githubusercontent.com/456863/104664262-c8e0e180-569c-11eb-8c26-f7aa64c37362.png)
from:  https://xd.adobe.com/view/793e2f7d-a1e4-414e-a5da-26ab0d6013cd-2c6d/

.

![image](https://user-images.githubusercontent.com/456863/104664284-d7c79400-569c-11eb-88f4-edb71b78f593.png)
from: https://xd.adobe.com/view/1a085703-7753-4fab-9fcf-d3e9683232b4-4f5b/

**Comment by starryeyez024** [comment]
@coreyvickery wanted to make you aware of this, thanks!

**Comment by castastrophe** [comment]
I have a jump links branch in the works but it's focused on JS so maybe we put a story in the backlog just for the styles?

**Comment by coreyvickery** [comment]
@starryeyez024 Forgive me, but what is the ask here? Do I or we need to explore the design of this component again with reduced padding the PatternFly folks? If or when I do, should I drop new specs in this issue?

**Comment by starryeyez024** [comment]
@coreyvickery  I guess I am looking for specs like this https://github.com/patternfly/patternfly-elements/issues/1258 for the vertical jump links that show padding. We can add an attribute and/or CSS variable that allows other devs to opt out of the default padding for use cases where the links need to align to the left edge. No-padding would be my preference as the default, since you can always put the jump-links in a pfe-card. 

Currently the default padding is too big, imho: 
![image](https://user-images.githubusercontent.com/456863/105717822-93cf5d00-5eee-11eb-966e-368c25fd8a5e.png)

**Comment by coreyvickery** [comment]
@starryeyez024 Take a look at this issue and let me know if what I wrote is sufficient.

https://github.com/patternfly/patternfly-elements/issues/1311

**Comment by coreyvickery** [comment]
@starryeyez024 Moved the documentation over and deleted the other issue.

# pfe-jumplink (vertical) padding

## Component padding
> Default should be no padding *around* component
<img width="356" alt="Screen Shot 2021-01-28 at 11 43 35 AM" src="https://user-images.githubusercontent.com/45767595/106193396-4bb87080-6162-11eb-9258-7b406f6ffd7c.png">

[PatternFly spacers](https://www.patternfly.org/v4/guidelines/spacers)

## Padding when used in card
<img width="256" alt="Screen Shot 2021-01-28 at 12 18 04 PM" src="https://user-images.githubusercontent.com/45767595/106194033-27a95f00-6163-11eb-9e78-d4dc97b04949.png">

## Alignment

### Left edge
> Jump links should have no padding when used on the edge of a grid, left or right
<img width="1438" alt="Screen Shot 2021-01-28 at 12 37 30 PM" src="https://user-images.githubusercontent.com/45767595/106197451-9c7e9800-6167-11eb-8261-3fb40dc11e1a.png">

### Content
> When not inside of/aligned to left or right edge of the grid (i.e. *sitting outside*), padding between jump links and content has a specific value based on the screen size (proposed solution for Topic and Article pages)

**Small screens**
<img width="1200" alt="Desktop, sm - Vertical jump links (1200px)" src="https://user-images.githubusercontent.com/45767595/106316643-e9bf4000-6221-11eb-9bdb-ceb9f30d5bd2.png">

**Large screens**
<img width="1440" alt="Desktop, lg - Vertical jump links (1440px)" src="https://user-images.githubusercontent.com/45767595/106316661-efb52100-6221-11eb-978d-cb1894985aeb.png">

[XD link](https://xd.adobe.com/view/8a2967f7-e652-4617-b6b3-c15c82de7c57-df7a/screen/8854b40b-7f99-4a1f-b4a3-8b5f90f06bf9/)

**Comment by starryeyez024** [comment]
@coreyvickery  do we have mobile mockups that show jump links spacing within the accordion?

**Comment by coreyvickery** [comment]
@starryeyez024 I can't find your comment about mobile mock-ups that show Jump links spacing inside of a Disclosure, but I believe an example is on ux.redhat.com.

https://ux.redhat.com/components/jump-links/

**Comment by starryeyez024** [comment]
resolved with https://github.com/patternfly/patternfly-elements/pull/1482
