### ISSUE TITLE
pfe-accordion: Drop shadow showing under opened header

### ISSUE THREAD

**Issue by kylebuch8** [patternfly/patternfly-elements#1287]
## Description of the issue
A drop shadow is showing under the expanded header.

### Impacted component(s)

- pfe-accordion
- pfe-content-set

### Steps to reproduce

1. Go to https://patternflyelements.com/elements/pfe-accordion/demo/
2. Click on the first accordion header
3. See the drop shadow under the header that shouldn't exist.

### Expected behavior

There shouldn't be a drop shadow.

### Screenshots

![image](https://user-images.githubusercontent.com/330256/105045072-7a816900-5a35-11eb-8603-02723c796b44.png)

**Comment by castastrophe** [comment]
Appears to have been introduced in: https://github.com/patternfly/patternfly-elements/commit/89ddfdc00382e46946309f02719a5faa1190248f

**Comment by kylebuch8** [comment]
This issue should've been closed by #1288. Everything looks good now.

![image](https://user-images.githubusercontent.com/330256/106899179-0bf20b80-66c3-11eb-8375-18475ee7fa76.png)
