### ISSUE TITLE
pfe-tabs: Variant in nested tabs is overridden by parent tab variant

### ISSUE THREAD

**Issue by kylebuch8** [patternfly/patternfly-elements#1396]
## Variant in nested tabs is overridden by parent tab variant

If you have a set of nested tabs and the child tab set has a variant defined, it is overridden by the variant that is set on the parent tab set even if the parent tabs don't have a variant set.

### Impacted component(s)
- pfe-tabs
- pfe-content-set

### Steps to reproduce

1. Go to https://codesandbox.io/s/cranky-rgb-gm8bp?file=/index.html
2. View variant attribute on line 15 of index.html
3. See that the wind variant has overridden the variant in the nested tab set

### Expected behavior

The parent tab set should not override the variant of a child tab set.

### Screenshots
![image](https://user-images.githubusercontent.com/330256/108858663-68599400-75ba-11eb-9e58-75bd7dcb6001.png)

**Comment by castastrophe** [comment]
I wonder if this is because the cascade built into pfelement isn't scooped to direct children. It just does a generic query selector.

**Comment by kylebuch8** [comment]
This issue was fixed by #1393. By upgrading to v1.3.1 in the demo, the issue is no longer present.
