### ISSUE TITLE
pfe-accordion: No padding at the bottom of a disclosure panel

### ISSUE THREAD

**Issue by kylebuch8** [patternfly/patternfly-elements#1397]
## pfe-accordion: No padding at the bottom of a disclosure panel

There is no padding at the bottom of a disclosure.

### Impacted component(s)
- pfe-accordion

### Steps to reproduce

1. Go to https://codesandbox.io/s/agitated-grass-4lh31?file=/index.html
2. Expand the first disclosure.
3. See that there is no padding at the bottom

### Expected behavior
I expect there to be some padding at the bottom of the panel.

### Screenshots
![image](https://user-images.githubusercontent.com/330256/108872512-3d763c80-75c8-11eb-8450-f819a18672cc.png)

**Comment by starryeyez024** [comment]
This has been resolved: https://patternflyelements.com/elements/pfe-accordion/demo/

![image](https://user-images.githubusercontent.com/456863/113033261-d61b5180-915e-11eb-94d5-82f869cc1c32.png)
