### ISSUE TITLE
[feat] pfe-accordion | Cannot add custom code in accordion headers

### ISSUE THREAD

**Issue by castastrophe** [patternfly/patternfly-elements#1403]
## Description of the requested feature

```
Hi all! Has anyone ever encountered issues trying to render a a PF React (icon) component inside  of a PFE accordion header?

...

I was hoping to have an `OutlinedQuestionCircleIcon` after the 'API' copy and have the tooltip sprout from there.

...

In the past I believe we've also tried adding a "NEW" label to indicate that new results have popped into the accordion too
```
Q from John Barguti, Portal Case Management

![recording (17)](https://user-images.githubusercontent.com/1840295/109050974-05462b00-76a8-11eb-8ccc-4f6a805f85e0.gif)

### Impacted component(s)

- pfe-accordion

**Comment by jaadbarg** [comment]
Regarding the "NEW" label, hopefully these screenshots provide a little more context. Thanks!
![image](https://user-images.githubusercontent.com/46633207/109052570-c0bb8f00-76a9-11eb-979a-f549a6eb4409.png)
![image (1)](https://user-images.githubusercontent.com/46633207/109052574-c1ecbc00-76a9-11eb-8a3b-df7ae631a3c9.png)

**Comment by castastrophe** [comment]
Development notes: Currently text content inside the accordion header is copied into the Shadow DOM and rendered there for controlled styling without light DOM influence.  That means that external styles do not work inside the accordion header region.

**Comment by castastrophe** [comment]
@coreyvickery Can you provide some design guidance here when you get a chance?

**Comment by coreyvickery** [comment]
@castastrophe Currently, we do not have any examples of this in marketing. I understand the need to use a Label, but not a Tooltip, so maybe we can talk through usage or best practices. I can create some guidelines when this is issue prioritized in our spreadsheet.

@ajacobs21e Is PatternFly planning on doing anything similar to what John is asking about? I did not see anything on the website.

**Comment by ajacobs21e** [comment]
@mcarrano do you know if it's possible to add a label to an accordion?

**Comment by mcarrano** [comment]
I don't think we have an explicit example of including labels in an accordion header, but I don't see any reason why you couldn't. We do a similar thing within our notification drawer. @mcoker any constraints on what you can place inside of the header of an Accordion?

**Comment by mcoker** [comment]
@mcarrano not really, though it's worth noting that the label is taller than regular text, so placing a label in the accordion header makes that header taller than headers without a label. 

<img width="861" alt="Screen Shot 2021-06-04 at 11 00 30 AM" src="https://user-images.githubusercontent.com/35148959/120830969-aef94b80-c524-11eb-8b2f-1bac9f2fb752.png">


The notification drawer uses badges, and badges are shorter than a line of text so they don't change the height of the header.

<img width="867" alt="Screen Shot 2021-06-04 at 11 03 59 AM" src="https://user-images.githubusercontent.com/35148959/120830956-ac96f180-c524-11eb-86f1-ac49b9975395.png">

**Comment by mcarrano** [comment]
Oh, that's right. I forgot that we were using badges and not labels in the drawer. @ajacobs21e @coreyvickery We haven't had a specific request from product to add labels. But if you decide to do that in PFE, I don't see any reason not to.
