### ISSUE TITLE
[NEW] pfe-progress-steps

### ISSUE THREAD

**Issue by heyMP** [patternfly/patternfly-elements#1436]
# pfe-progress-steps

> Gives the user a visual representation of the current state of their progress through an application (typically a multistep form).

## Design specification
> The Progress steps component is only available in the Light theme.

### Horizontal
<img width="672" alt="__Progress steps - Horizontal" src="https://user-images.githubusercontent.com/45767595/110428495-575b5900-8077-11eb-943c-8bf48be21c1c.png">

### Horizontal, compact
<img width="672" alt="__Progress steps - Horizontal - Compact" src="https://user-images.githubusercontent.com/45767595/110428505-5a564980-8077-11eb-937f-cc43b6cdbc25.png">

### Vertical
<img width="98" alt="__Progress steps - Vertical" src="https://user-images.githubusercontent.com/45767595/110428511-5d513a00-8077-11eb-81e1-8c382578a751.png">

- - -

## Accessibility

[Best practice for Regular Step Indicator](https://design.gccollab.ca/component/progress-indicators/)

- - -

## Interactions
<img width="915" alt="__Progress steps - interaction states" src="https://user-images.githubusercontent.com/45767595/110430501-7c050000-807a-11eb-8144-a08a51d08a1e.png">

- - -

### Horizontal and Horizontal, compact

<img width="685" alt="01 Progress steps - Horizontal - Step 1" src="https://user-images.githubusercontent.com/45767595/110432601-5a594800-807d-11eb-96fe-878dde85b4c6.png">
<img width="676" alt="02 Progress steps - Horizontal - Step 2" src="https://user-images.githubusercontent.com/45767595/110432602-5a594800-807d-11eb-9b6b-6f38fe862384.png">
<img width="676" alt="03 Progress steps - Horizontal - Step 2 - Error" src="https://user-images.githubusercontent.com/45767595/110432603-5a594800-807d-11eb-8620-280ec57ebbab.png">
<img width="689" alt="04 Progress steps - Horizontal - Step 3" src="https://user-images.githubusercontent.com/45767595/110432606-5a594800-807d-11eb-9350-70d145f872f2.png">
<img width="678" alt="05 Progress steps - Horizontal - Step 3 - Error" src="https://user-images.githubusercontent.com/45767595/110432609-5a594800-807d-11eb-98a5-4808c8b539cf.png">
<img width="679" alt="06 Progress steps - Horizontal - Complete" src="https://user-images.githubusercontent.com/45767595/110432611-5af1de80-807d-11eb-9d33-957e135d6ebb.png">

### Vertical

<img width="98" alt="01 Progress steps - Vertical - Step 1" src="https://user-images.githubusercontent.com/45767595/110433927-2121d780-807f-11eb-8dbf-fdd6bc249295.png">
<img width="217" alt="02+Error Progress steps - Vertical - Step 2" src="https://user-images.githubusercontent.com/45767595/110433771-e750d100-807e-11eb-9380-1e483025321f.png">
<img width="217" alt="04+Error Progress steps - Vertical - Step 3" src="https://user-images.githubusercontent.com/45767595/110433772-e7e96780-807e-11eb-9977-37599811da39.png">
<img width="79" alt="06 Progress steps - Vertical - Complete" src="https://user-images.githubusercontent.com/45767595/110433774-e7e96780-807e-11eb-8dc6-fcbc53682566.png">

[PatternFly spacers](https://www.patternfly.org/v4/guidelines/spacers/)
[PatternFly icons](https://www.patternfly.org/v4/guidelines/icons)

- - -

## Source

https://xd.adobe.com/view/9a5a5c65-9ba2-4f43-8a0e-fc86e54a95f1-cf09/screen/5efe7c63-48dd-4894-8603-b942f49c65a8/specs/

**Comment by heyMP** [comment]
@coreyvickery ^

**Comment by coreyvickery** [comment]
@heyMP Hey Michael, this issue has been updated. Let me know if any other documentation needs to be included.

**Comment by heyMP** [comment]
@coreyvickery ready for design review.  I unfortunately started with the wrong name so I need to do a big search and replace. :)

https://deploy-preview-1406--happy-galileo-ea79c4.netlify.app/elements/pfe-progress-stepper/demo/

**Comment by coreyvickery** [comment]
@heyMP This is looking really good, here is my feedback.

* The `Done` step should always be selectable
* A lot of links in the Vertical components are not selectable (however, `Error` is never selectable)
* For the Horizontal components, do you need guidance about how wide the text labels can be until they break to two lines?

**Comment by heyMP** [comment]
@coreyvickery Per our conversation a few weeks ago:

> The Done step should always be selectable

There are instances where we don't want the steps to be clickable.  We can leave it up to the developer to specify which steps can be clickable.

> A lot of links in the Vertical components are not selectable (however, Error is never selectable)

This is an issue with how I'm presenting the demo.  I'm going to clean it up so it's hopefully more clear.

> For the Horizontal components, do you need guidance about how wide the text labels can be until they break to two lines?

The width of the steps need to be explicitly set by the `--pfe-progress-stepper__item--Width` variable.  This ensures that the steps line up correctly and appear symmetrical.  So long story short, it will be up to the developer to decide when to break the text into multiple lines.  Is this an acceptable approach?  We can set a max-width saying, "no matter what, an item can't be over 250px", or something like that.

I'm going to improve the demo and send it back to you for review!

**Comment by heyMP** [comment]
@coreyvickery changes are ready for review! 

https://deploy-preview-1406--happy-galileo-ea79c4.netlify.app/elements/pfe-progress-steps/demo/

- [x] Made demo more consistent by making all steps clickable in the first half of the demo.
- [x] Updated namespace to pfe-progress-steps

**Comment by coreyvickery** [comment]
@heyMP Thanks for sending, this is the last round of feedback that I have.

* Interaction states look good.
* Mobile looks good.
* Can the `Current` and `Error` states not be selectable by default? It doesn't make a lot of sense if they are, but no worries if not.
* I like the idea of setting a maximum width for descriptions, at least for the horizontal orientation, so let's go with 200px. I can also provide a maximum character count for designers when I write the website documentation.
* I might be crazy, but I think I see a tiny amount of white space between some of the bars and the icons. This could be my computer's screen rendering or something else, but I thought I would point it out anyways. No worries if there's no easy fix.

<img width="924" alt="Screen Shot 2021-04-15 at 2 56 01 PM" src="https://user-images.githubusercontent.com/45767595/114923495-e720bf80-9dfa-11eb-804e-7afbf922a2e2.png">

Thanks again.

**Comment by heyMP** [comment]
@coreyvickery some changes for ya!  And a brand new url:  https://deploy-preview-1406--patternfly-elements.netlify.app/elements/pfe-progress-steps/demo/

- [x] `current` and `error` states should not be selectable.
- [x] remove the 1px white white line between progress bar and circle icon.  (the svg is transparent so I needed a background of some type or else you would see the gray progress bar behind the checkmark.  I used a background gradient technique to ensure the circle is transparent around the edges but solid in the center.)

**Comment by coreyvickery** [comment]
@heyMP So beautiful, go ahead and close.

**Comment by heyMP** [comment]
Thanks @coreyvickery! Sending to code review 🦾

**Comment by coreyvickery** [comment]
@heyMP Hey Michael. My apologies, I made a tiny change that needs to be included in the web component.

When a user reaches an `Error` step, the text label font weight needs to be Medium.

<img width="714" alt="Screen Shot 2021-05-16 at 7 35 04 PM" src="https://user-images.githubusercontent.com/45767595/118416529-294d5300-b67e-11eb-8954-e940281d8ac8.png">

<img width="718" alt="Screen Shot 2021-05-16 at 7 35 11 PM" src="https://user-images.githubusercontent.com/45767595/118416530-294d5300-b67e-11eb-91f8-b9af87bb54f4.png">

<img width="295" alt="Screen Shot 2021-05-16 at 7 35 18 PM" src="https://user-images.githubusercontent.com/45767595/118416531-294d5300-b67e-11eb-8153-ed73149ab669.png">

A similar treatment of the text label can be seen when a user is in the `Current` step.

<img width="714" alt="Screen Shot 2021-05-16 at 7 39 20 PM" src="https://user-images.githubusercontent.com/45767595/118416614-94972500-b67e-11eb-988d-8b5eff730747.png">
