### ISSUE TITLE
Content set not cascading properties consistently

### ISSUE THREAD

**Issue by zhawkins** [patternfly/patternfly-elements#1438]
## Description of the issue

Within Percy visual regression some properties are not cascading. Unfortunately this isn't a flicker because it's consistent.

### Impacted component(s)

- content-set
- tabs

When comparing `1.0.0-prerelease.55` with `1.3.2` I see the following:

![example-1](https://user-images.githubusercontent.com/2671663/110549119-992fe200-80ff-11eb-97b4-0f940488f95f.png)

![example-2](https://user-images.githubusercontent.com/2671663/110549127-9b923c00-80ff-11eb-8613-5051e957af40.png)

I've been able to resolve these issues with some help from Cassondra by manually cascading the properties.

```
Promise.all([
    customElements.whenDefined("pfe-content-set"),
    customElements.whenDefined("pfe-tabs")
]).then(() => {
    document.querySelectorAll("pfe-tabs").forEach(tabs => tabs.cascadeProperties());
});
``` 

So, while that _works_ it's not great and we shouldn't have to manually call cascadeProperties().

**Comment by castastrophe** [comment]
I'll add, we can't replicate this ourselves in-browser.  It seems specific to Percy.

**Comment by castastrophe** [comment]
Related issue: https://github.com/patternfly/patternfly-elements/issues/1423

**Comment by kylebuch8** [comment]
I think this might not just be Percy and be more related to the cascade of all the properties. It appears to be a race condition. If I throttle my network to 3G speeds using developer tools, the accordion demo page loads fine.
https://patternflyelements.com/elements/pfe-accordion/demo/

But, when I remove the network throttling, the dark and saturated bands don't properly cascade the color attribute.

With throttling
![image](https://user-images.githubusercontent.com/330256/115898365-79dce200-a42b-11eb-890e-f3f76e317503.png)

Without throttling
![image](https://user-images.githubusercontent.com/330256/115898419-88c39480-a42b-11eb-95dd-196797614dea.png)
