### ISSUE TITLE
Add file for Node version manager  

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#1506]
## Description of the requested feature

The package.json file already specifies the version of Node for tools like CI, but for developers, an .nvmrc or .node-version file would be helpful so that anyone using NVM could easily switch between projects and it would remember the version of node needed for PatternFly Elements.

**Comment by castastrophe** [comment]
@starryeyez024 This was such a small and reasonable request that I went ahead and opened a PR for it: https://github.com/patternfly/patternfly-elements/pull/1511/files
