### ISSUE TITLE
research Web Test Runner

### ISSUE THREAD

**Issue by mwcz** [patternfly/patternfly-elements#1519]
Justin recommended [Web Test Runner](https://modern-web.dev/docs/test-runner/overview/) very highly.  We should investigate and see how much effort it would be to incorporate.

**Comment by castastrophe** [comment]
@zhawkins Is working through this now as part of the AT epic 🎉

**Comment by castastrophe** [comment]
Closing this in favor of: https://github.com/patternfly/patternfly-elements/issues/1425
