### ISSUE TITLE
refactor theme js files to allow toggling themes

### ISSUE THREAD

**Issue by mwcz** [patternfly/patternfly-elements#153]
To address an issue with theme toggling in Storybook that @TylerMartin5 and @markcaron discovered, I think we should refactor each theme's js files as follows.  Using cp-theme for an example.

1. instead of running immediately, cp-theme.js should export a function
2. when run, that function should remove any rhelements' theme-related elements from the head (to clear out any previously set themes)
3. that function will then activate cp-theme by injecting stuff into the head

This will enable toggling from one theme to another in Storybook, but also for any page that wants to have theme toggles, like a demo page or an app with light/dark themes.

**Comment by castastrophe** [comment]
Cool idea.  Would there be 2 methods for importing a theme then: 1 approach using the JS file, another for using the CSS file directly?

**Comment by mwcz** [comment]
Yeah, that would be excellent.
