### ISSUE TITLE
[feat] pfe-styles | add primary ordered list styles

### ISSUE THREAD

**Issue by heyMP** [patternfly/patternfly-elements#1565]
# pfe-styles: 

Helper classes for PatternFly Elements.

## Design specification updates

We need to include a primary ordered list style for pfe-styles.  This would allow a use to add a class of `<ol class=".pfe-list--primary">` to an ordered list tag and see the follow design:

![Screen Shot 2021-04-29 at 9 26 14 AM](https://user-images.githubusercontent.com/3428964/116558892-e7768b80-a8cd-11eb-874a-becd5d10b804.png)

## Docs

https://docs.google.com/document/d/1YlAbzfSr6wb4tfrf2AjosQsVRQdPXTMWo4vUwWCEBZ0/edit?ts=6089b653#heading=h.73gku8pdr96n

## Mockup

https://xd.adobe.com/view/49a4d095-016e-4698-9726-323abe6f6b23-1cf7/screen/4395b2c9-1963-47f4-877a-6948e34fe954

## Related issues

- #878 

## Demo

https://deploy-preview-1571--patternfly-elements.netlify.app/elements/pfe-styles/demo/ (Scroll down to Primary Ordered List header)

**Comment by heyMP** [comment]
Hey @coreyvickery, can you take a look at demo and let me know what you think?  This would be the `primary` variant of an ordered list.  This would not apply to unordered lists as they don't have numerical indicators next to the items.

One thing to note about the demo, `ol.pfe-list--primary` does not handle layout; meaning, I'm using `pfe-l-grid` to put the items into a grid layout on larger screens.

https://deploy-preview-1571--patternfly-elements.netlify.app/elements/pfe-styles/demo/ (Scroll down to Primary Ordered List header)

Thank you!

**Comment by castastrophe** [comment]
Question: does anyone else read these bullets down the column versus across?

<img width="1196" alt="Screen Shot 2021-05-03 at 11 28 51 AM" src="https://user-images.githubusercontent.com/1840295/116897176-f8433c00-ac02-11eb-963f-fc963a6a0be7.png">

**Comment by heyMP** [comment]
lol.. yes; we went back and forth about that.  The good news is that `ol.pfe-list--primary` is unopinionated about it the layout.  So the author could use `columns` instead of `grid` to get the desired reading flow.

**Comment by coreyvickery** [comment]
@heyMP Looks good to me.

**Comment by coreyvickery** [comment]
@eohammond If you have an opinion, you should say it here.

**Comment by eohammond** [comment]
@heyMP I agree, looks great. The number icons are beautiful. @castastrophe like Potter said, we went back and forth on that. When real content is entered it's less likely that the big column of whitespace will exist between the columns containing content. So we think it will flow horizontally better than this test content does. But @heyMP are you saying that a content strategist could actually change whether the numbered progression is vertical or horizontal w/n FTS?

**Comment by heyMP** [comment]
Hi @eohammond! Yes, since content inside of the list items can vary widely, I'm. not sure it would make sense to have to ol.pfe-list--primary be in charge of its layout.  I think it would be better for the author to either use the `pf.l.grid` class (which is what the demo uses) or include CSS that controls the layout.  The the author could change the reading order depending on the context.

**Comment by castastrophe** [comment]
Great point @heyMP! Thanks for clarifying!

**Comment by eohammond** [comment]
Thanks @heyMP sounds good to me.
