### ISSUE TITLE
[fix] pfe-tabs issue with active border color on horizontal/wind

### ISSUE THREAD

**Issue by dcaryll** [patternfly/patternfly-elements#1585]
## Description of issue

On horizontal/wind tabs, the active border is not maintaining its color (#06c) when clicking between tabs. The active state seems to be being overridden by the focus state border.

### Impacted component(s)

- pfe-tabs 

### Steps to reproduce

1. Go to https://patternflyelements.com/components/tabs/
2. Click on one of the tab elements in the horizontal/wind tabset
3. See wrong color on active tab element bottom border

### Expected behavior

Active tab element has colored border

### Screenshots

![Screen Shot 2021-05-06 at 9 18 49 AM](https://user-images.githubusercontent.com/1249747/117304809-27002300-ae4c-11eb-9b6d-588ebce112dd.png)

**Comment by heyMP** [comment]
Looks like `:host(:focus)` is taking priority over `[aria-selected="true"]`

**Comment by bonjo7** [comment]
Removed `:host(:focus)` which was over writing `[aria-selected="true"]`, underline is now coloured on selected tab
