### ISSUE TITLE
[docs] Update CSS variable documentation

### ISSUE THREAD

**Issue by castastrophe** [patternfly/patternfly-elements#1632]
Do we consistently say "Theme hook" in the docs? I wonder if these should be more explicit & say "CSS Custom Properties" or "CSS Variables"

_Originally posted by @starryeyez024 in https://github.com/patternfly/patternfly-elements/pull/1545#discussion_r632794702_

**Comment by castastrophe** [comment]
We could emulate PF: https://www.patternfly.org/v4/components/action-list#css-variables

**Comment by castastrophe** [comment]
Good document to draw from: https://www.patternfly.org/v4/developer-resources/global-css-variables/

**Comment by starryeyez024** [comment]
My 2 cents is we could still use the terminology "theme hook" when introducing the concepts of CSS variables & how they are useful somewhere in the theming documentation. But everywhere else where they are mentioned, they should probably be referred to by the proper naming convention `CSS variables` that the world would understand if they randomly dropped into a doc about a particular component.

**Comment by castastrophe** [comment]
@bennypowers Is this issue still relevant?

**Comment by bennypowers** [comment]
We opted for the term `CSS Custom Properties`, which is searchable and in line with spec. We don't document *every single* available properties. Undocumented properties can be considered "private"
