### ISSUE TITLE
add framework tests

### ISSUE THREAD

**Issue by mwcz** [patternfly/patternfly-elements#165]
We need tests to ensure RHElements continue to work within React, Angular, Vue, etc.

Things to research:

1. for UI-only elements, do visual regression testing to make sure they look right within frameworks
2. for behavioral elements (ex: accordion, tabs), do something like the tests on https://custom-elements-everywhere.com/ to ensure attrs and events work within the framework

**Comment by kylebuch8** [comment]
Closing in favor of #1011
