### ISSUE TITLE
An issue in pfe-modal

### ISSUE THREAD

**Issue by mayilks** [patternfly/patternfly-elements#1657]
Hi,

Hope you are well,

I am using the Pattern fly modal to play the youtube iframe on my webpage. If I am trying to close the modal. The modal is closed but youtube is playing in the background I can able to hear the sound. Is there any way to pause or stop the video from playing while hit the close button?

Thanks in advance. stay safe :)

**Comment by castastrophe** [comment]
Hi @mayilks, thanks for reaching out.  This is not a bug in pfe-modal but rather, a result of the youtube implementation.  You will need to connect to the YouTube API and stop playing the video when the `pfe-modal:close` event is fired.

Here is a link to read more about the YouTube API: https://developers.google.com/youtube/iframe_api_reference

An option for what you can do:  `document.addEventListener("pfe-modal:close", player.stopVideo);`, where player is defined as a YouTube object in the example from the documentation I linked to.
