### ISSUE TITLE
[chore] dev command running storybook build before component build

### ISSUE THREAD

**Issue by zipzit** [patternfly/patternfly-elements#1684]
## Description of the issue

I wanted to understand what patternfly-elements really is and how it works.  Great, I see the readme includes a nice Quickstart setup:
```
git clone git@github.com:patternfly/patternfly-elements.git
cd patternfly-elements
npm install # this will take a while due to lerna bootstrap
npm run dev -- --storybook --docs # This will build and spin up a local server with storybook preview and docume
```
So I spin up a Linux Virtualbox machine.  Install npm, clone the repo per above.  `npm run...` = total fail   Lots and lots of error messages.  See attached file.  

[patternfly elements fail.txt](https://github.com/patternfly/patternfly-elements/files/6683380/patternfly.elements.fail.txt)

### Impacted component(s)
Quick start fail = scare folks away.  Why bother offering a quickstart if its going to fail?  Perhaps I'm doing this wrong?  (hint, my expectation is that a quick start ALWAYS works, and that the Quickstart criteria is included as a test in any pull request update...)
- 

### Steps to reproduce

follow the instructions at [PatternFly Elements Github readme Quickstart](https://github.com/patternfly/patternfly-elements#quick-start)

### Expected behavior 
I would expect a functioning website / demo.  I expect that the QuickStart instructions on the repo readme page to be ACCURATE in EVERY detail.  Additionally its not clear from the readme where the server will be located.  Is "localhost:80" the correct answer there?  (if not, why is that info not included in the readme Quickstart?)

### Screenshots

 Fail.  Nothing to see.  

## Related issues

- () Description

**Comment by castastrophe** [comment]
Thanks for sharing the console output, very helpful.  It appears that storybook is trying to kick off before the components are built.  Going to flag this as a likely script update needed.

**Comment by castastrophe** [comment]
We are deprecating storybook in the project via #1708 so I'll close this PR out now
