### ISSUE TITLE
[feat] Add Custom Elements Manifest to PFE elements

### ISSUE THREAD

**Issue by heyMP** [patternfly/patternfly-elements#1685]
## Description of the requested feature

Custom Elements Manifest is a recently 1.0 spec for describing APIs of web components.  This is a spec has been adopted by many popular libraries and toolchains already.  It would be nice if we could align with the web component community on this spec and export a `custom-elements.json` with each component.

## Tooling

OpenWC as a tool to analyze your web components and generate the `custom-elements.json` file.  https://github.com/webcomponents/custom-elements-manifest

### Impacted component(s)

- All components

## Further reading

Pascal has a great writeup on the spec that explains the benefits of adoption: https://dev.to/open-wc/introducing-custom-elements-manifest-gkk

**Comment by bennypowers** [comment]
Take a look at http://npm.im/@custom-elements-json/analyzer

writing plugins is really user-friendly. Some examples: 
https://github.com/apollo-elements/apollo-elements/tree/next/packages/docs/custom-elements-manifests-plugins

**Comment by bennypowers** [comment]
OK
