### ISSUE TITLE
[CI] Automate tag releases

### ISSUE THREAD

**Issue by castastrophe** [patternfly/patternfly-elements#1706]
When any PR is merged into master (if it has a 'fix' or 'feat' prefix)

1. Version bumps
2. Update the changelog automagically with:
  ```
  ## <Version> (<today's-date>)

  - [<PR#>](<PR link>) <PR title> (<linked issue numbers>)
  ```
3. Create a tag release
4. Update tag description with info from changelog

**Comment by heyMP** [comment]
Lion and others are using [changesets](https://github.com/atlassian/changesets). Might be worth exploring.

**Comment by bennypowers** [comment]
Changesets is now a thing by PFE
