### ISSUE TITLE
chore: Remove storybook

### ISSUE THREAD

**Issue by castastrophe** [patternfly/patternfly-elements#1707]
### Discussion from chat

Cassondra:
Is anyone interested in deprecating the storybook for PFE?  I know we don't have a solid replacement yet but I'm wondering how used it is and if we're putting all this work into building stories for nothing

Michael:
I was mulling over the same thing.  Especially seeing the work that's being done with custom-elements-manifest and that neat Web Component Dev Tools.  It seems like we are rapidly approaching a time were much of the storybook features are replicated in our docs/demos and 3rd party tooling.

**Comment by bennypowers** [comment]
Sure :)
