### ISSUE TITLE
[feat] pfe-progress-indicator add theme hooks for changing color of spinner

### ISSUE THREAD

**Issue by heyMP** [patternfly/patternfly-elements#1743]
# Component name: pfe-progress-indicator

![Screen Shot 2021-08-04 at 2 58 52 PM](https://user-images.githubusercontent.com/3428964/128239285-6ab92918-42a3-4dea-ba61-c6da8a40689e.png)

## Design specification updates

Currently, the component only offers the ability to override the size of the spinner.  We should add the ability to control the color of the color of the spinner as well.

## Proposal

Add the following theme hooks

```css
--pfe-progress-indicator--foreground-color;
--pfe-progress-indicator--background-color;
```

**Comment by markcaron** [comment]
@heyMP I'm assuming the `foreground-color` is the color of the part spinning, while the `background-color` is the color of the circle, correct?

**Comment by coreyvickery** [comment]
@heyMP Simple changes.

* Keep the animation speed and overlay the same
* Color: #06c
* Transparency: 25%

**Comment by heyMP** [comment]
> @heyMP I'm assuming the `foreground-color` is the color of the part spinning, while the `background-color` is the color of the circle, correct?

Yeah, that's what I was thinking.  I'm not married to those names either.

**Comment by markcaron** [comment]
[Work completed](https://github.com/patternfly/patternfly-elements/pull/1746)
