### ISSUE TITLE
[feat] pfe-button | Add large variant

### ISSUE THREAD

**Issue by coreyvickery** [patternfly/patternfly-elements#1745]
# Component name: pfe-button

> Update to pfe-button to add large variant

## Specs

<img width="147" alt="Button, large" src="https://user-images.githubusercontent.com/45767595/128402048-768743e5-786f-4e91-9d56-51b43d9adb9d.png">

* Background color: `#0066cc`
* Rounded corners: 3px
* Text: Red Hat Text, Medium, 16pt/24 (1.5)
* Top/bottom padding = 12px
* Left/right padding = 24px

## Interaction states

<img width="661" alt="Button, large accessibility" src="https://user-images.githubusercontent.com/45767595/128403108-aec4d45b-f7c7-413d-804c-befd10c235d8.png">

### Default
* Same as specs

### Focus
* Default focus ring
* Text is the same

### Hover
* Text is the same
* Background color: `#004080`

### Active
* Default focus ring
* Text is the same
* Background color: `#004080`

**Comment by heyMP** [comment]
@coreyvickery ready for review! https://deploy-preview-1751--patternfly-elements.netlify.app/elements/pfe-button/demo/

**Comment by coreyvickery** [comment]
@heyMP Looks great, approved.

**Comment by markcaron** [comment]
[Work completed](https://github.com/patternfly/patternfly-elements/pull/1751).
