### ISSUE TITLE
Storybook page does not load completely

### ISSUE THREAD

**Issue by chrisdo1** [patternfly/patternfly-elements#1750]
### Description of the issue
The Storybook page has a TypeError that prevents most of the components on the page from loading.

#### Steps to reproduce

1. Navigate to [Storybook in your browser](https://patternflyelements.org/storybook/?path=/story/accordion--pfe-accordion).
2. You should see the error at the top of the page `TypeError: Cannot read property 'toLowerCase' of undefined`.
3. You should only see the first 16 elements in the left nav.

#### Screenshots
![Screen Shot 2021-08-12 at 4 18 48 PM](https://user-images.githubusercontent.com/32456107/129264037-5c4481c1-3fcd-4677-8beb-8435539c5b59.png)

**Comment by bennypowers** [comment]
We dropped storybook in 2.0, closing for now
