### ISSUE TITLE
PFE-Readtime wordcount need to be change to character count for APAC languages.

### ISSUE THREAD

**Issue by alazzara** [patternfly/patternfly-elements#1768]
## Description of the issue

There is currently an issue with readtime for APAC languages where there are long stings with no spaces or word breaks. This is causing the readtime calculation to be really low and inaccurate. I think we will need to update the code from word count to character count for these languages in order to generate an accruate readtime.

### Impacted component(s)

- Anything using PFE-readtime. For Webrh it is impacting the Long form article and Topic pages.

### Steps to reproduce

1. Go to: https://www.redhat.com/en/topics/containers/what-is-a-kubernetes-cluster and note the readtime.
2. Now go to: https://www.redhat.com/ja/topics/containers/what-is-a-kubernetes-cluster' and note the readtime is hidden as it is less than 1 minute due to calculation error.

###Screenshots

<img width="1130" alt="PFE-readtime_bug" src="https://user-images.githubusercontent.com/55710331/131875610-e17562ca-6107-421e-88e7-5434f068ad63.png">

### Expected behavior
I expect the readtime to show up on APAC languages when there is enough content on the page to indicate a readtime that is greater than 1 minute.

**Comment by bennypowers** [comment]
I believe korean is covered so far. can we list the other languages which need adjusting and update this issue?
