### ISSUE TITLE
PFE-Codeblock: Make Prism an explicit import

### ISSUE THREAD

**Issue by wesruv** [patternfly/patternfly-elements#1773]
Prism is being imported by `pfe-codeblock.js` but it's not being included in the project anywhere. From what I've seen it looks like the module resolver will pull in what it can, and that will likely be different depending on who builds it. This means the languages that have highlighting in codeblock may change depending on who builds/releases it.

Need to include Prism as a dep and specify what languages we want as part of the build so it is consistent.

### Impacted component(s)
- pfe-codeblock

**Comment by wesruv** [comment]
Work in progress here: `1773-codeblock-make-prism-a-dependency-2`

Discussion here: https://chat.google.com/room/AAAAQFSmB88/wDg_qWcnJxs****

**Comment by bennypowers** [comment]
Now we import prism as such:

https://github.com/patternfly/patternfly-elements/blob/58b1ae602790a4532c9dc485c2f8bb36f81a1d44/elements/pfe-codeblock/pfe-codeblock.ts#L7-L20

and include its dependency here:

https://github.com/patternfly/patternfly-elements/blob/58b1ae602790a4532c9dc485c2f8bb36f81a1d44/elements/pfe-codeblock/package.json#L78

If this doesn't satisfy your need, please reopen

**Comment by wesruv** [comment]
looks like it will, thanks Benny!
