### ISSUE TITLE
Focus moves inside of collapsed accordion

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#1779]
## Description of the issue

When the keyboard is used to move the focus through a webpage, the focus should not move onto links which are hidden from view. 

### Expected behavior

The pfe-accordion has collapsed panels which contain links, and so the focus should only move to each heading (and past the hidden links), unless the panel is expanded & visible.

### Impacted component(s)

- pfe-accordion

### Steps to reproduce

1. Go to https://patternflyelements.com/components/accordion/
2. Click on the Accordion heading at the top of the page (to skip the nav)
3. Hit the tab key several times.
4. Notice that the first accordion header is focused, and then the next time you hit the tab key the focus disappears. This is because it's focused on a link within the first panel. When you hit tab again, the focus will move to the second accordion header.

### Screenshots

![image](https://user-images.githubusercontent.com/456863/132919006-1db0b2e7-c5c5-4ce9-ab6b-454e71456d86.png)

(the link in the bottom left is an empty anchor link within the hidden panel)

**Comment by kelsS** [comment]
Hi @heyMP @starryeyez024 @kylebuch8, I am bumping up the priority of this issue. It is causing problems with the new Product Index Page and rendering the component unusable for assistive tech and keyboard navigating.

**Comment by bennypowers** [comment]
wai-aria example accordion: https://www.w3.org/TR/wai-aria-practices/examples/accordion/accordion.html

I'm going to see about putting together some unit tests in #1804, maybe we can solve this there

**Comment by kelsS** [comment]
@kylebuch8, @bennypowers fixed this issue in ticket [1804](https://github.com/patternfly/patternfly-elements/pull/1804).

**Comment by bennypowers** [comment]
Fixed in 2.0
