### ISSUE TITLE
Create a global 'connected' event in PFElement base class

### ISSUE THREAD

**Issue by wesruv** [patternfly/patternfly-elements#1803]
Working on the latest `pfe-clipboard` update, I found I am probably going to want an event to know when a component on the page is ready so I can set `pfeClipboard.contentToCopy` for the portal's docs.

@kylebuch8 mentioned maybe we should have a global 'connected' event, as it may come in handy for other components as well.

So basically we'd fire the custom event `connected` in the connectedCallback and I'm guessing `event.details` may be something like:
```
{
  tagName: 'pfe-blabla',
  component: referenceToComponentInstance
}
```
Having tagName as a key would be nice to quickly filter in eventListeners, though we could easily do `event.details.component.tagName`, not sure if we'd want anything else?

### Impacted component(s)

- pfelement base class

What do you folks think?

![Discuss amongst yourselves](https://media4.giphy.com/media/l2SpQRuCQzY1RXHqM/200.gif)

**Comment by wesruv** [comment]
Follow up question, maybe @bennypowers might have insight:
Does Lit Element have an event that fires on `connectedCallback`, and if not is there a reason they don't that we should keep in mind?

**Comment by heyMP** [comment]
Funny, this is actually an agenda item for our report at TPAC.  This is the main issue for this functionality. https://github.com/WICG/webcomponents/issues/809

We can use connectedCallback in LitElement.  We could also fire it after first render.  That would allow other elements to access the shadowdom right away.  I think it's a good addition until we get an official spec for this functionality.

**Comment by bennypowers** [comment]
could you do this with 
```
await customElements.whenDefined('pfe-clipboard');
```

**Comment by wesruv** [comment]
Gotcha, I'll try what @bennypowers is suggesting, I would prefer to be IE11 compatible with this feature, so the async may not be ideal; but I'll try setting the property before it's upgraded to see if that works.

@kylebuch8 wanted me to bring this up as an issue, but @bennypowers convinced me in GChat that it might not be the best idea since it'd be hard to rollback once it's out. With that and the suggestions here for what can work with LitElement, I'ma close this.

Thanks!
