### ISSUE TITLE
pfe-clipboard icon incorrect size

### ISSUE THREAD

**Issue by rlahoda** [patternfly/patternfly-elements#1814]
## Description of the issue

The svg copy image displays at the incorrect size of 32px x 32px on Safari. This doesn't happen on Firefox. This appears to be because the SVG element itself has a set height and width of 32px. The other icon used in the component is set at 16x16px. This appears to be an issue with Webkit broswers.

The solution would either be to remove the height/width of the element and use CSS to determine those values, or update the element to have the correct 16px x 16px

### Impacted component(s)

- pfe-clipboard and any components that use it

### Steps to reproduce

View https://patternflyelements.com/components/clipboard/ in Safari 

### Screenshots

<img width="110" alt="image" src="https://user-images.githubusercontent.com/18124644/144911929-37fe2e56-c216-44ca-85f2-04993edb9208.png">

## Related issues

- #100

**Comment by bennypowers** [comment]
@rlahoda I believe this is fixed, please reopen if you can reproduce
