### ISSUE TITLE
bug: [feat/pfe-tools] pfe-tools `prepublishOnly` throws error.

### ISSUE THREAD

**Issue by heyMP** [patternfly/patternfly-elements#1819]
## Description of the issue

Running the prepublish command in pfe-tools results in an error that the `analyze` script is missing.

### Impacted component(s)

- pfe-tools

### Steps to reproduce

From the root of PFE run `npm run prepublishOnly --workspace @patternfly/pfe-tools`

### Screenshots

![Screen Shot 2021-12-14 at 8 40 00 AM](https://user-images.githubusercontent.com/3428964/146015223-fb030fa8-1f6f-41c0-88bc-70fa5231b518.png)

**Comment by bennypowers** [comment]
I reproduced this with
```
npm run clean:nuke
npm ci
npm run prepublishOnly -w @patternfly/pfe-tools
```
I solved it by replacing the `prepublishOnly` script with `npm run build` in the pfe-tools package

See https://github.com/patternfly/patternfly-elements/commit/6a11930703c1e940565156a9f084f9706f3502fa
