### ISSUE TITLE
bug: [feat/pfe-tools]  `npm run test` results throws non-breaking error

### ISSUE THREAD

**Issue by heyMP** [patternfly/patternfly-elements#1820]
## Description of the issue

When running tests, the tests complete and pass but it exits with an error. 

```
 🚧 Browser logs:
      SyntaxError: The requested module '/node_modules/lit/index.js?wds-import-map=0' does not provide an export named 'TemplateResult'

 ❌ Could not import your test module. Check the browser logs or open the browser in debug mode for more information.
 ```

### Steps to reproduce

1. Checkout `feat/pfe-tools` branch
2. `npm ci`
3. `npm run test`

All tests should pass but exit with an error.

![Screen Shot 2021-12-15 at 2 44 06 PM](https://user-images.githubusercontent.com/3428964/146256639-b76aaa20-217a-4510-ab2f-a33ddbbcf87e.png)

**Comment by bennypowers** [comment]
i fixed this after ```npm run clean:deep && npm test```

**Comment by heyMP** [comment]
I also had to build the pfe-tools package before running tests.  But it did resolve the error. 👍


```
npm run clean:deep
npm run build --workspace @patternfly/pfe-tools
npm test
```
