### ISSUE TITLE
switch "demo" dir to "example" in each element and in generator

### ISSUE THREAD

**Issue by mwcz** [patternfly/patternfly-elements#185]
We would like to use rhelements.github.io/demo as the URL for storybook.

To avoid naming overlap with the current "demo" directory that each element has, we should rename "demo" to "examples" in each existing element and in the generator.

**Comment by markcaron** [comment]
Sounds reasonable.

**Comment by castastrophe** [comment]
@kylebuch8 @mwcz Still desirable or should we close this issue?

**Comment by kylebuch8** [comment]
I don't see the issue. I think we can close this.
