### ISSUE TITLE
[idea]: support meta tags for PFE config

### ISSUE THREAD

**Issue by bennypowers** [patternfly/patternfly-elements#1854]
**Case**: User wants to enable or disable "performance tracking"

Current API:

```html
<html>
  <head>
    ...
    <script>window.PfeConfig = { trackPerformance: true }</script>
    ... proceed to load pfe elements
  </head>
  ...
</html>
```

The disadvantage of this approach is that it relies on a render-blocking script tag

Proposed API:

current API still works, but we add:

```html
<html>
  <head>
    <!-- default "false" -->
    <meta name="pfe-track-performance" content="true">
    <!-- default "true" -->
    <meta name="pfe-auto-reveal" content="false">
    <!-- default from localStorage -->
    <meta name="pfe-log" content="false">
  </head>
  ...
</html>
```

Allowing an HTML-only configuration

**Comment by heyMP** [comment]
That's a cool approach.  I do think that it might be more approachable to SPA developers to use the `PfeConfig`.  I would vote for having both if possible.

**Comment by heyMP** [comment]
that's perfect. 👍

**Comment by bennypowers** [comment]
let's adopt this as implementation is cheap and there's not much to bikeshed over

**Comment by mwcz** [comment]
I think it's a cool idea, but I'm not fully bought-in to the render-blocking concern, for two reasons.

First is that the timing of creating an object with a few properties is so fast that any delay in rendering will be imperceptible on even the slowest smartphones.  I measured it with `console.time` and 6x CPU slowdown, and it still ran in 6 microseconds.

The second reason is that `window.PfeConfig` doesn't _have_ to be inlined, it just needs to be created before components are imported.  For example:

**main.js**
```js
import "./my-pfe-config.js";
import "@patternfly/pfe-card";
```

**my-pfe-config.js**
```js
window.PfeConfig = { trackPerformance: true }
```

This way eliminates render blocking, and my-pfe-config.js will still wind up first.  And in the case of bundling, IIRC bundlers generally respect source order.

And keeping the object in JS means that a TS interface can provide type checking for the values, which is out of reach for meta tags.

Rewinding time for a minute... I wasn't a big fan of `window.PfeConfig` when it was introduced, but I definitely understood the need for a method of configuring components _before_ they can upgrade.  But in my mind, the culprit that really needs to be apprehended is that each component's module `define`s itself with `customElements`!  You can't simply configure a class before `customElements.define`...

```js
import PfeCard from "@patternfly/pfe-card";
PfeCard.configure({ beAwesome: true });
PfeCard.define(); // something like this would be cool
```

That would be my ideal case for configuring components.  The big challenge is how to offer that flexibility without forcing everyone to start writing lots of `PfeFoo.define()` boilerplate for every component they want.  My only idea, which I'm not very fond of, is to offer two bundles: `pfe-card.js` which automatically `define`s, and `pfe-card-no-define.js` which doesn't `define`, allowing for pre-define config.

**Comment by heyMP** [comment]
OpenWC boilerplate creates two separate exports for components.  One with the define, one without the define.  I'm partial to this approach as it's saved my butt a few times when I just need to make quick and dirty hacks.  I know that other WC community members disagree but I can't remember what the reasoning was.

**Comment by bennypowers** [comment]
on one foot: scoped registry isn't quite baked yet (even with polyfills). if you need to subclass, you should change names too, and it's better to fail loudly than silently
