### ISSUE TITLE
[pfe-clipboard] If site isn't HTTPS copy functionality will not work.

### ISSUE THREAD

**Issue by wesruv** [patternfly/patternfly-elements#1868]
The clipboard API requires a secure origin to work, otherwise `navigator.clipboard` will be undefined.

I recommend we hide the clipboard button and throw a warning if the site is not `https`

**Comment by heyMP** [comment]
Ah, that's right.  We could possibly use the the old school fallback if we don't have access to `navigator.clipboard`.

**Comment by zeroedin** [comment]
Took a look at this issue.  Feel free to review and suggest any changes. 

https://github.com/zeroedin/patternfly-elements/commit/4b131451a8a0b711bad6dde64c1fff7af3b27f6d

**Comment by kelsS** [comment]
Hey @wesruv me and Aditi are going to work through this ticket together. Would you add her to the project to she can be an assignee https://github.com/aditiohri
