### ISSUE TITLE
Broken link on PFE Typography page

### ISSUE THREAD

**Issue by marionnegp** [patternfly/patternfly-elements#1925]
## Description of the issue

"View the demo page of all CSS typography classes" link on https://patternflyelements.org/theming/typography/ is broken.

**Comment by brianferry** [comment]
Looks like this should link to https://ux.redhat.com/foundations/typography or perhaps more specifically to https://ux.redhat.com/foundations/typography/#desktop-scale

**Comment by bennypowers** [comment]
there's a build step in pfe-styles (or pfe-sass?) that should generate a page for this

if you want to do some code archaeology, find a pre-2.0 deploy preview on netlify and check out how it used to be

**Comment by marionnegp** [comment]
Closing this because I don't think the Typography page exists anymore
