### ISSUE TITLE
[docs]: patternflyelements.com/v1/ should redirect to v1 docs

### ISSUE THREAD

**Issue by zeroedin** [patternfly/patternfly-elements#1949]
Currently, patternflyelements.com documentation is version 2 of PFE in pre-release.  We need to add a link to version 1.X.X documentation for those maintaining current elements in production.

**Comment by bennypowers** [comment]
I had a few thoughts on how to accomplish this

- [every netlify build has its own permalink](https://docs.netlify.com/site-deploys/overview/#branches-and-deploys)
- we can set up specific branches to alutomatically deploy to a given url, as well
- We can configure [path-based redirects in netlify.toml[(https://docs.netlify.com/configure-builds/file-based-configuration/#redirects) 

I think the above is more than enough to maintain a list of versions like v1 and v2 and eventually v3. I'd like it better if we could deploy by tag, and hey look here's a github action that does just that

https://stackoverflow.com/questions/61775854/how-to-use-github-actions-to-deploy-on-tag-to-netlify

[more docs on that action](https://github.com/netlify/actions/tree/master/build) it's pretty simple, just a single http call with curl, so if we need to extend it we can

if we pulled that off we could have:
1. a dropdown which lists versions by repo tag (v1, v2, etc)
2. a long lived permalink for which deploys to the major versions for each push to a semver-formatted tag (e.g. the v1 deploy would update when pushing to tag v1.12.4)
3. a netlify.toml file which gets (manually?) updated every time we want to add a version
4. and we can calculate the 11ty data for versions by [reading the netlify.toml](https://www.npmjs.com/package/toml) and using [addGlobalData](https://www.11ty.dev/docs/data-global-custom/), no need to maintain a separate 11ty json file for that.

**Comment by zeroedin** [comment]
This sounds like a much more maintainable idea to me.  I like it.

**Comment by bennypowers** [comment]
@zeroedin you still want this one?

**Comment by zeroedin** [comment]
> @zeroedin you still want this one?

Sure, I can take a stab at it.

**Comment by bennypowers** [comment]
last good 1.12 docs: https://61f9ac3d5f4a9200081bb953--patternfly-elements.netlify.app/
