### ISSUE TITLE
pfe-card slots only work with legacy slot names pfe-card--header and pfe-card--footer | Angular integration

### ISSUE THREAD

**Issue by asharron** [patternfly/patternfly-elements#1977]
# Description 

When using the `pfe-card` element, using slot names `header` or `footer` does not seem to work and will render blank markup. Using the names `pfe-card--header` and `pfe-card--footer`, however, will make the component output the correct markup though they are marked as deprecated / legacy. 

![Screenshot from 2022-04-04 14-23-16](https://user-images.githubusercontent.com/16943263/161607525-f6274ea8-c6f5-4969-bae1-dd83cdae5244.png)

![Screenshot from 2022-04-04 14-23-29](https://user-images.githubusercontent.com/16943263/161607544-42b5435d-7691-473c-9993-024ed20a3cc4.png)

Link to sandbox: https://codesandbox.io/s/fervent-kalam-z7yfue?file=/src/app/app.component.html

# How To Reproduce 

1. Create a new angular project 
2. Add the CUSTOM_ELEMENTS_SCHEMA object to the schemas array in app.module.ts
3. NPM install `@patternfly/pfe-card`
4. Import `@patternfly/pfe-card` into an angular component 
5. Create the `pfe-card` element and put 3 pieces of markup inside it
6. Give the first piece of markup the attribute `slot="header"` and see that markup not be output in the card
7. Give the last piece of markup the attribute `slot="footer"` and see that markup not be output in the card
8. Change the first piece of markup to have attribute `slot="pfe-card--header` and see it be output in the card
9. Change the last piece of markup to have attribute `slot="pfe-card--footer` and see it be output in the card

Not that big of an issue, but did find it confusing the docs recommended to use `header` and `footer` slot names and it didn't work for me causing me to mis-troubleshoot a bit. 

Issue found using Angular Core v13.2.0 and @patternfly/pfe-card v1.12.3

**Comment by bennypowers** [comment]
That version of pfe-card (v1.x) only supports the old, prefixed slots. The new, unprefixed slots are v2 APIs

https://codesandbox.io/s/black-dew-qyqrdg?file=/src/app/app.component.html

I'm going to close this for now as we have no plans to implement the new slots in the version 1 branch. If you have a particular need for that, please open a [new discussion](https://github.com/patternfly/patternfly-elements/discussions/new)
