### ISSUE TITLE
Asides in PFE band demo not lining correctly

### ISSUE THREAD

**Issue by marionnegp** [patternfly/patternfly-elements#1983]
@bennypowers, the asides in the [PFE demo's](https://patternflyelements.org/components/band/demo/) default band, darker band, darkest band, and dark band with bg image aren’t lined up with the body copy. The aside in the lightest band is correctly positioned on this page.

**Comment by bennypowers** [comment]
Thanks for the report

The scss for band's grid is quite complex. Ideally, we'd replace it with simple vanilla css grid, but for now I just added an overriding rule for this case at the bottom of the file.
