### ISSUE TITLE
[feat] pfe-pagination

### ISSUE THREAD

**Issue by kylebuch8** [patternfly/patternfly-elements#200]
A pagination component for both desktop and mobile.

**Desktop**
<img width="511" alt="screen shot 2018-10-08 at 11 21 28 am" src="https://user-images.githubusercontent.com/330256/46618123-b5716400-caec-11e8-8eca-a40254a1b595.png">

<img width="541" alt="screen shot 2018-10-08 at 11 22 05 am" src="https://user-images.githubusercontent.com/330256/46618133-bd310880-caec-11e8-95ba-5e0abd3dd3ac.png">

<img width="920" alt="screen shot 2018-10-08 at 11 22 44 am" src="https://user-images.githubusercontent.com/330256/46618137-c0c48f80-caec-11e8-98a2-7e8e7ca14a15.png">

**Mobile**
<img width="1172" alt="screen shot 2018-10-08 at 11 23 19 am" src="https://user-images.githubusercontent.com/330256/46618150-c91cca80-caec-11e8-9f61-363247afb9c7.png">

<img width="1180" alt="screen shot 2018-10-08 at 11 25 05 am" src="https://user-images.githubusercontent.com/330256/46618173-d8037d00-caec-11e8-8f87-deb66aa34529.png">

## Developer Checklist
- [ ] Documentation
- [ ] Tests
- [ ] Theming
- [ ] Story

**Comment by markcaron** [comment]
Working on the visuals now. Will hand off when needing JS improvements.

**Comment by ajacobs21e** [comment]
PF4 pagination for reference: https://drive.google.com/file/d/1PpIo3-cZeUdVsq9WsG-LmbDj0Vwb6A5E/view
Their use case is solely for a list / table view. We'll need to consider if page level pagination is a separate use case.

**Comment by ajacobs21e** [comment]
https://docs.google.com/document/d/1hr2V3Dt2PYeH-3y1fpr8e0umkSnG1EYk-6pm1E_LBOM/edit component requirements doc

**Comment by coreyvickery** [comment]
@ajacobs21e @samlinville @mceledonia Has any further work been completed for this?

**Comment by ajacobs21e** [comment]
I haven't done anything since collecting some requirements & past work in the reqs doc

**Comment by castastrophe** [comment]
@coreyvickery Would you take a look at this when you get a chance?  Pagination was raised as a need in relation to the search results pages and eventually we want to replace the React components being used there with web components.

**Comment by coreyvickery** [comment]
@castastrophe I've adopted the same component as PatternFly, unless we have different needs for redhat.com. It's not as visual as what we use today, but maybe that's something to discuss when this gets prioritized.

https://www.patternfly.org/v4/components/pagination

https://xd.adobe.com/spec/3e62e93c-8338-4f31-5040-3b81f0ed5c71-4853/screen/890b9d34-73dd-473e-8981-7173a4f93819/

**Comment by markcaron** [comment]
With the migration to our Red Hat Design System, we'll handle the prioritization and development of [this component in the RHDS repo](https://github.com/RedHat-UX/red-hat-design-system/issues/234).

**Comment by bennypowers** [comment]
Note: contrary to the typical 1:1 workflow of first implementing the pfe version of a component, then subclassing for RHDS, we took the decision to do rh-pagination first. One reason is because pfe-pagination and rh-pagination would anyways be somewhat different.

We therefore have not included pfe-pagination in the 2.0/1:1 release milestone, but we would eventually like to build it. at that point, the work on rh-pagination should be back ported.
