### ISSUE TITLE
pfe-cta color context attribute color-palette incorrectly applies styles to variants

### ISSUE THREAD

**Issue by zeroedin** [patternfly/patternfly-elements#2002]
pfe-cta had the color context attribute `color-palette` applied to it as a color context provider.  I believe this might have done inadvertently.

latest example:
![image](https://user-images.githubusercontent.com/13666/163856524-c10647a3-4ec2-4363-b8f0-dabea0cbc2b5.png)

pfe-cta I don't believe needs to be a provider of color context, instead, its prior `color` attribute was separate from the color context code base instead working as a for lack of better terminology tertiary theme attribute.

pfe-cta has a `priority` as well as `variant` attribute which affects its styling.  The`color` attribute was a third attribute to override some of the styles applied by the other two to give more variation.  If I understand it correctly it was not the being used in the same context as the `on` and now `color-palette` as a context for child elements as pfe-cta really only accepts `<a>` and `<button>` tags as the light dom elements.

pfe-cta should reflect the same styles as in the example below:

v1.x example:
![image](https://user-images.githubusercontent.com/13666/163857259-4fbed8b4-6e1d-4703-9e65-218d68ec95c6.png)

My suggestion is to revert back to the `color` attribute as an explicit attribute such as in `pfe-icon` and `pfe-label`, removing the `@colorContextProvider` decorator and the `@deprecation` of the color attribute.  Reverting the demo HTML and scss changes for the component.

**Comment by bennypowers** [comment]
Closed by #2006 
If there are any hanging issues here, let's open a new ticket
