### ISSUE TITLE
Drop lerna in favour of wireit

### ISSUE THREAD

**Issue by bennypowers** [patternfly/patternfly-elements#2011]
[Lerna's finally dead](https://github.com/lerna/lerna).

[wireit](https://github.com/google/wireit) is the new hotness from Google.

We should drop lerna (and npm-run-all) in favour of wireit

For context: the only thing we use Lerna for is parallel scripts, we don't use any of the monorepo management or publishing features.

**Comment by castastrophe** [comment]
Haha the link you posted now links off to `https://blog.nrwl.io/lerna-5-1-new-website-new-guides-new-lerna-example-repo-distributed-caching-support-and-speed-64d66410bec7` saying basically "We're not dead yet!"

![image](https://user-images.githubusercontent.com/1840295/180478036-468d1ab0-a177-4311-8d84-51456e8787ff.gif)

I've done some cursory explorations into wirier and it looks pretty great. I'm also a big fan of yarn 3 and their [workspaces](https://yarnpkg.com/features/plugins#official-plugins) tooling.

**Comment by bennypowers** [comment]
Will let you know here. I'm waiting on https://github.com/google/wireit/issues/33 before diving in
