### ISSUE TITLE
[bug] PFE Nav — multiple issues, mostly style adjustments

### ISSUE THREAD

**Issue by markcaron** [patternfly/patternfly-elements#2023]
# Component name: <pfe-navigation>

There are several issues we've found in implementing the [new PFE Nav](https://github.com/patternfly/patternfly-elements/tree/CPFED-3689-new-navigation-epic) on RHDC.

### 1. Force break text blocks being stripped ###

<img width="632" alt="image" src="https://user-images.githubusercontent.com/1890950/167154993-0faf1dfe-c1ef-4d61-8213-a38104f9d4d2.png">

Our current nav structure utilizes `<span class=”text-block”></span>` around some of the text/labels in the nav. These appear to be getting stripped—potentially as text is being moved from lightDOM to shadowDOM. This is causing line break issues with longer labels, especially when translated.

### 2. Too much space between stacked CTAs, including the bottom margin on the last CTA.

In Chrome at 767px wide and below, as soon as the CTAs start stacking, it feels like we have too much space between the CTAs. See bottom of the Red Hat & open source menu. Can that be tightened up? Maybe 32px between each of them?

<img width="515" alt="image" src="https://user-images.githubusercontent.com/1890950/167155610-8f9f60b3-47f4-4894-bf8c-9c778878df6d.png">

Last CTA example:

<img width="527" alt="image" src="https://user-images.githubusercontent.com/1890950/167156220-72516c0a-6eb2-48af-ab43-c98c37039b0a.png">

### 3. CTAs bumping against each other at certain breakpoints.

This is likely related to # 2 above. In Chrome and FF at 469px wide “Search jobs” is butting up against the primary CTA. Wondering about defaulting to stacking multiple CTAs, especially given different lengths in different languages.

<img width="429" alt="image" src="https://user-images.githubusercontent.com/1890950/167155952-53b5f544-a8d7-4b73-9f87-45ce8cf65f2e.png">

### 4. Increased font-size on mobile's accordion (from previous version)

New version on the left:

<img width="631" alt="image" src="https://user-images.githubusercontent.com/1890950/167156488-ba6f77c1-272f-4595-92fd-f205ebee594e.png">

### 5. On medium to smaller screens, allow for 2 columns in dropdown at breakpoint

At 767px and above, we have 3 columns. Then below that it drops to 1 column. On the previous version, there was a step for 2 columns in between (767px-576px). It’d save some scrolling.

<img width="631" alt="image" src="https://user-images.githubusercontent.com/1890950/167157052-41f56c12-93d1-478b-824f-fedf99394f5d.png">

### 6. Increased spacing between list items in drop down.

See above screenshot in # 5.

Was it intentional to increase the spacing between list items? I can see the argument for making it more readable, but it’ll require more scrolling. I’m thinking about the super long Product A-Z that’s coming.

### 7. Mobile views overlap.

![mobile (1)](https://user-images.githubusercontent.com/103068985/168604972-7218446e-8556-40b4-a2db-78cbd66bc3ef.png)

Component's handling of long copy on mobile nav, copy overlap with >, instead of wrapping.

### 8. Decrease padding in nested accordion on mobile to get more horizontal space. 

Notes from System UX discovery meeting on this:
- 2 CSS variables control padding - 32px surrounding nav & search bar, lessen that. 16px is the norm.
- Allen is modifying the CSS variable as a "bandaid" for now- trying 16px padding option instead of 32px.
- We'll need to "undo" this once we implement at the component level
- Notes: https://docs.google.com/document/d/17iSx7gVr6scH4AcQo4nsaGTCy8lOo2hLl2dVn00Zpss/edit#bookmark=id.go2uwaexcuq1

Let me know if you have questions. Thanks!

**Comment by markcaron** [comment]
CC @wesruv @heyMP @methomps

**Comment by bennypowers** [comment]
Should we reopen this in redhat-ux/red-hat-design-system?

**Comment by methomps** [comment]
Attempt to link a related issue with this larger feature of pfe-nav 2.0 enhancement

**Comment by methomps** [comment]
I’d think so, if that’s where we are migrating prioritized work eligible to “pick up next”.
