### ISSUE TITLE
Happy path for running the repo and generating a new components throwing lerna errors

### ISSUE THREAD

**Issue by Djfaucette** [patternfly/patternfly-elements#2028]
## When I pull down a fresh clone of the repo and run this: npm ci && npm run dev I get this message

lerna info Executing command in 1 package: "npm run dev"
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/dfaucett/Documents/projects/redhat/patternfly-elements/node_modules/@patternfly/pfe-tools/dev-server.js.js' imported from /Users/dfaucett/Documents/projects/redhat/patternfly-elements/web-dev-server.config.js

It's weird - looks like something somewhere is trying to add an extra ".js" extension onto a file

I'm using node 16 if that's relevant

Similarly, when running npm run new...

Analyzing cp-error
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/dfaucett/Documents/projects/redhat/patternfly-elements/node_modules/@patternfly/pfe-tools/custom-elements-manifest.js.js' imported from /Users/dfaucett/Documents/projects/redhat/patternfly-elements/elements/cp-error/custom-elements-manifest.config.js

That was trying to create a new component named cp-error

Looks like a similar issue, .js.js in a filename is weird

### Impacted component(s)

-

**Comment by bennypowers** [comment]
Glad to hear you worked it out
