### ISSUE TITLE
feat: migrate MatchMediaController to pfe-core

### ISSUE THREAD

**Issue by zeroedin** [patternfly/patternfly-elements#2032]
There is a MatchMediaController that has been marked to upstream in rh-footer.  I have a use case for it as well.  Creating this issue to track this feature request.

```js
// TODO: upstream to PFE
import { MatchMediaController } from '../../lib/MatchMediaController.js';
```

**Comment by bennypowers** [comment]
lets close since rhds is moving on to screensize controller
