### ISSUE TITLE
[1:1] pfe-card

### ISSUE THREAD

**Issue by bennypowers** [patternfly/patternfly-elements#2046]
# Component name: `<pfe-card>`

## Design specification updates

[PatternFly v4 Card](https://www.patternfly.org/v4/components/card)

We may defer implementation of `expanded` and `selectable` for now.

**Comment by methomps** [comment]
Discussion thread around card: https://github.com/orgs/RedHat-UX/discussions/361

**Comment by brianferry** [comment]
@marionnegp @coreyvickery @markcaron 

For `pfe-card` it looks like for 1:1 our coverage should be

- Basic Card (title, body, footer)
- Cards that can include any combination of the following
  - Title Header
  - Image Header
  - Body
  - Footer
- Compact Card
- Large Card

Do we want to also support for the first pass the following options: 

Borders / Drop Shadows:
- Flat (no drop-shadow, does have a border)
- Rounded (sets a border radius)
- Plain (No border or drop shadow)

Styling of the internals of the card itself:
- Full-Height (Body takes up full height)
- Card w/ dividers between sections (similar to how accordion can include borders between sections)

Actions
**What are they?** pf v4 includes a menu and a checkbox item, presumably could be anything and would have to be provided functionality by the user?
**What do they include?**
- Card w/ image and **actions**
- Card w/ title and **actions**
- Card w/ **actions** and no title

As mentioned by @bennypowers previously we will likely need to defer expanded and selectable for now. 

Keeping in mind too that whatever we add in here could be pfe specific if we think rhds is not going to need it.

**Comment by brianferry** [comment]
Added a branch @ feat/pfe-card-pfv4 for this work https://github.com/patternfly/patternfly-elements/tree/feat/pfe-card-pfv4

**Comment by coreyvickery** [comment]
@markcaron @marionnegp Seems fine for 1:1, are we missing anything else?

**Comment by bennypowers** [comment]
Closed by #2222
