### ISSUE TITLE
[1:1] pfe-avatar

### ISSUE THREAD

**Issue by bennypowers** [patternfly/patternfly-elements#2048]
# Component name: `<pfe-avatar>`

## Design specification updates

[PatternFly v4 Avatar](https://www.patternfly.org/v4/components/avatar)

In this case it may be advantageous to compose `<pfe-avatar>` into the shadow DOM, rather than extending it's class.

**Comment by bexter89** [comment]
note to ensure alt attribute is included for accessibility; currently the nav bar on access.redhat.com uses pfe-avatar and accessibility reports are showing hits to our score based on the lack of an alt attribute.
