### ISSUE TITLE
[1:1] pfe-tabs

### ISSUE THREAD

**Issue by bennypowers** [patternfly/patternfly-elements#2051]
# Component name: `<pfe-tabs>`
## Design specification updates

[PatternFly v4 Tabs](https://www.patternfly.org/v4/components/tabs)

**Comment by methomps** [comment]
https://github.com/patternfly/patternfly-elements/pull/1698

**Comment by zeroedin** [comment]
PR: https://github.com/patternfly/patternfly-elements/pull/2099
