### ISSUE TITLE
minify-html-literals error

### ISSUE THREAD

**Issue by zhawkins** [patternfly/patternfly-elements#2064]
I'm running into a rollup error when trying to consume a element that imports pfe-icon. I've tracked it to this issue: https://github.com/asyncLiz/rollup-plugin-minify-html-literals/issues/14

which lead me to:
https://github.com/patternfly/patternfly-elements/blob/8499a6ebac6f12c02c75be718320018d0143f5e6/elements/pfe-icon/pfe-icon.ts#L185

Removing this style attribute lead to rollup minifying html literals correctly.

**Comment by bennypowers** [comment]
We have this with static html templates as well, in https://github.com/asyncLiz/minify-html-literals/issues/37

Preferably we could fix upstream, but barring that, we can solve locally by refactoring (back) to control flow logic with the static templates and by imperatively setting a css var in icon
