### ISSUE TITLE
Dev server: Don't focus nav on page load

### ISSUE THREAD

**Issue by bennypowers** [patternfly/patternfly-elements#2075]
Not sure if this is really a blocking issue.  But when you click on a component demo from the nav, a new page loads, and focus returns to the top of the nav on the first nav item, not the top of the page itself.  I feel like this is most likely an accessibility error.   After page load I would assume focus is on the document, usually followed by a skip-nav link which could skip the header links (logo/github) and then place focus on the main navigation.  If the main nav is hidden skip nav might have to then place focus on the hamburger menu button (noted this isn't a saved preference so this might be moot).  This gives the user the option to click a header link after page load.  There is also a visual style applied with `:focus-visible` which almost makes it look like an active page indicator.

![image](https://user-images.githubusercontent.com/13666/181601666-a64598b3-46cf-4a38-9358-5f9fa95b6033.png)

Otherwise LGTM

_Originally posted by @zeroedin in https://github.com/patternfly/patternfly-elements/issues/2072#issuecomment-1198441220_

**Comment by zeroedin** [comment]
This issue was resolved previously in an unlinked PR.

The second part of this issue was the lack of skip-nav link which is being resolved separately in: https://github.com/patternfly/patternfly-elements/pull/2550
