### ISSUE TITLE
[1:1] pfe-tile

### ISSUE THREAD

**Issue by bennypowers** [patternfly/patternfly-elements#2092]
# Component name: `<pfe-tile>`

> The tile component exists in PF 4 and will be added to RHDS, but it's not part of PFE yet.

## Design specification

[PatternFly v4 Tile](https://www.patternfly.org/v4/components/tile)

**Comment by markcaron** [comment]
PF's Tile is currently in Beta. Wondering if we should be attempting to do an 1:1 work on Beta components at this time.

Also, the definition of "tile" might be a source of confusion. In PF, Tiles seem to be "selectable" (i.e. `listbox`). Our use might be more "clickable" (i.e. `<a>`).

Carbon seems to allow multiple types of interaction within their definition of [Tile](https://carbondesignsystem.com/components/tile/usage/).

When migrating this as 1:1, do we narrow the scope for PFE and then widen the scope for RHDS to match Carbon's usage? What's the industry standard on these?

**Comment by bennypowers** [comment]
The impetus for this issue was to unblock `<rh-tile>`. We're fine to prioritize this only slightly higher than that.

**Comment by bennypowers** [comment]
closed by #2187
