### ISSUE TITLE
pfe-tabs | Mobile view

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#211]
There is no mobile solution currently build into the rh-tabs, currently they just overflow off the page
https://www.evernote.com/l/AA6nPwJ4bjdClJGrVJXzfCQzWaDA-LVxyC4

Could we pass in a breakpoint at which it changes to a menu?
https://www.evernote.com/l/AA580WRExvpDWpxY-n9ZC-2qoT2UdIIw-qg

Or should it just default to v-tabs?

**Comment by castastrophe** [comment]
Closing this in favor of: https://github.com/patternfly/patternfly-elements/issues/1013
