### ISSUE TITLE
Create dialog / modal component

### ISSUE THREAD

**Issue by mwcz** [patternfly/patternfly-elements#212]
Description to come.

**Comment by starryeyez024** [comment]
If you check out the `restore-dialog` branch and view [http://localhost:1234/elements/rh-dialog/demo/](http://localhost:1234/elements/rh-dialog/demo/) there is a button but it does nothing. 

Console says:
`Uncaught ReferenceError: dialogPolyfill is not defined`

**Comment by starryeyez024** [comment]
Can we modify this issue to be specific to dialogs, which are different than modals? @mwcz @TylerMartin5 @markcaron https://www.nngroup.com/articles/modal-nonmodal-dialog/

**Comment by TylerMartin5** [comment]
@starryeyez024 second that - this was the original intent for this component
