### ISSUE TITLE
rh-dropdown

### ISSUE THREAD

**Issue by mwcz** [patternfly/patternfly-elements#213]
Description to come.

**Comment by ajacobs21e** [comment]
We have the requirement to filter items in the dropdown if there more than a certain number of items. We'll need to determine what that number is - iirc we used 7+ for filter dropdowns on /search.

**Comment by mwcz** [comment]
@ajacobs21e Sounds great to me.  I love text filters.

**Comment by starryeyez024** [comment]
[Discovery doc](https://docs.google.com/document/d/1IBOxLED7v7YjyvygUMjKByDS0bilS9-_mMaWdwl6oeQ/edit#)

**Comment by markcaron** [comment]
I know I've mentioned this in our meetings, but I want to echo my concern for not conflating UI patterns in PFE. We should be consistent in our language and naming around dropdowns, select fields, and navigational "dropdowns". All three behave differently, and we should also ensure that they look different—to have "material honesty".

The same goes for buttons and CTAs (calls-to-action) links.

**Comment by markcaron** [comment]
Per our offline discussion, we could have `pfe-dropdown` handle both the `select` and the `listbox` dropdown, but we'd need to have the component checking the lightDOM for potential misuse by developers. We'd also have varying sets of requirements depending on use case.

`Combobox` and the navigational dropdown are separate constructs/components.

**Comment by kylebuch8** [comment]
Closing this since the work is being handled in https://github.com/patternfly/patternfly-elements/pull/668.
