### ISSUE TITLE
Move all elements to single package

### ISSUE THREAD

**Issue by bennypowers** [patternfly/patternfly-elements#2134]
This repo will remain a monorepo, BUT, all the elements will be in a single package

## Goal 1: `@patternfly/elements`
pfe-tools will likely need to be updated to accommodate this change, and those changes to pfe tools will have to be validated against rhds

## Goal 2: Remove esbuild from element build chain
currently, each element package builds sources into javascript with tsc, but then deletes those runtime files and rebuilds them with esbuild. This is so that we can inline the scss sources.

Instead, we should use a ttsc plugin to accomplish the same thing, and make tslib a dependency.

See https://github.com/RedHat-UX/red-hat-design-system/blob/main/transformers/css-import-specifiers.cjs and https://github.com/RedHat-UX/red-hat-design-system/blob/main/scripts/transform-css.js

We can still use esbuild to bundle the whole package into pfe.min.js

## Goal 3: Remove or port all elements
There should not be any elements in /elements which aren't PF 1:1, so delete or port these:
- pfe-band (#2290)
- pfe-select (#2145)
- pfe-dropdown (#2049)
- pfe-autocomplete (#2115)
- pfe-progress-steps (#2052)

**Comment by brianferry** [comment]
Would it be worth moving pfe-tools into it's own repo or is it simpler to keep them together and just package it separately from the elements?

**Comment by bennypowers** [comment]
We'd have to do that for a number of packages, not just pfe-tools, as well as the core packages.

For that reason, I think it's best to retain the monorepo infra here, but combine the elements info a single package

**Comment by bennypowers** [comment]
Closed by #2316
