### ISSUE TITLE
[tools] Add Type Definitions

### ISSUE THREAD

**Issue by KamiQuasi** [patternfly/patternfly-elements#216]
Publishing Reference: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html
Structure Reference: https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/declaration%20files/templates/module-class.d.ts.md

**Comment by KamiQuasi** [comment]
@kylebuch8 and @mwcz I would think we need to also include these in the generator. Not sure about a mechanism to update/test/verify them yet, but will look into it.

**Comment by mwcz** [comment]
Something to discuss along with this: once an element is generated, do we put responsibility on the developer of every new element to update the d.ts file with every change they make to the element?  For example, if I create an element and give it a `doStuff()` function, must I the element creator update the d.ts to reflect that, or would someone who knows TypeScript (hi @KamiQuasi!) be responsible for keeping all the d.ts files in sync?

Not expecting an answer, just something we should think about and discuss.

**Comment by mwcz** [comment]
I wonder if typedefs can be generated from jsdoc comments.  I bet someone has tried that...

**Comment by mwcz** [comment]
https://github.com/englercj/tsd-jsdoc

But... "Warning: Highly Experimental"

Sounds fun. :boom:

**Comment by mwcz** [comment]
#52

**Comment by castastrophe** [comment]
Pull requests accepted 😝

**Comment by castastrophe** [comment]
@kylebuch8 Is this on the roadmap or something we plan to work on?

**Comment by castastrophe** [comment]
I assigned this issue to milestone 3.0.  I think we should evaluate developer knowledge of TS in 2022 for integration into our 3.0 release.  I'm fine migrating to TS entirely if the industry is putting out enough mid-level developers with TS experience by then.

**Comment by heyMP** [comment]
@zhawkins found this great article too.  Just posting here as a possible intermediary step using JSDoc, intellisense.  It theoretically allows you to generate type definitions based on JSDoc.

https://austingil.com/typescript-the-easy-way/

**Comment by mwcz** [comment]
Related: https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html

**Comment by bennypowers** [comment]
pfe-2.0 should cover this
