### ISSUE TITLE
[bug] pfe-tools: pfe-tools@1.0.0-next.30 breaking decorators in RHDS

### ISSUE THREAD

**Issue by heyMP** [patternfly/patternfly-elements#2166]
## Description of the issue

@zeroedin and I were debugging issues related to `@query, @state, @queryAssignedElements, @colorContextProvider` not working as expected.  We tracked it down to an issue with the latest version `next.30` of pfe-tools.  We pinned it to version `next.29` for a temporary fix.

### Impacted component(s)

- all components

### Steps to reproduce

1. RHDS Seconary Nav: https://github.com/RedHat-UX/red-hat-design-system/issues/568
2. RHDS Footer: https://github.com/RedHat-UX/red-hat-design-system/pull/569

**Comment by bennypowers** [comment]
sorry to hear there was a problem with the release - did you get any output that could help pin down the issue? there were some key improvements in beta.30 which unblock other prs

**Comment by zeroedin** [comment]
I think i found the culprit
```
            esbuildPlugin({
                ts: true,
                // see https://github.com/evanw/esbuild/issues/2220
                target: 'es2020'
            }),in pfe-tools/dev-server.js
```
The change was es2020 -> es2022 in 29 to 30.

reverting that makes things happy again

**Comment by zeroedin** [comment]
Actually, I believe the real fix might be instead to add the following config to web-dev-server.config.js 

By passing in the `tsconfig.json` as the tsconfig option.

Doing so I think you could remove `target` completely from the esBuildPlugin options in dev-server.ts

```js
export default pfeDevServerConfig({
  litcssOptions,
  tsconfig: 'tsconfig.json',
  middleware: [
    /** redirect requests for lightdom css to /elements */
    function(ctx, next) {
      const match = ctx.path.match(/^\/components\/(?<slug>[-\w]+)\/(?<path>.*)\.css$/);
      if (match) {
        const { slug, path } = match.groups;
        ctx.redirect(`/elements/rh-${slug}/${path}.css`);
      }
      return next();
    }
  ]
});
```

**Comment by bennypowers** [comment]
exactly correct, that was the intent of adding the tsconfig passthrough. nice work!
