### ISSUE TITLE
Quick start README link

### ISSUE THREAD

**Issue by bdone** [patternfly/patternfly-elements#2203]
### Impacted component(s)

- README

### Steps to reproduce

1. Go to CONTRIBUTING.md in something that renders markup
2. Click "README" in `(see the Quick start in the [README])`
3. Observe that README isn't clickable.

![2203-README](https://user-images.githubusercontent.com/302272/198162406-efc96c17-4ce9-4ed9-b5c7-bde26532d521.png)

### Expected behavior

1. `(see the Quick start in the [README])` "README" links to README.md 

![2203-README-fixed](https://user-images.githubusercontent.com/302272/198162403-f7c94e95-9133-405b-b6bb-73dfeb7688a2.png)

**Comment by kylebuch8** [comment]
Fixed by #2204
