### ISSUE TITLE
[bug]switch: clicking switch wrapped by a label does not update the switch

### ISSUE THREAD

**Issue by kylebuch8** [patternfly/patternfly-elements#2209]
Go to https://patternflyelements.org/components/switch/demo/#nested-label

Click the switch and notice that the switch does not update. If you click the label, everything works. But clicking the switch should also work.

It works correctly in Firefox but not in Chrome. It appears that clicking the switch in Firefox causes two clicks on the switch and just one click in Chrome.

**Comment by bennypowers** [comment]
https://github.com/patternfly/patternfly-elements/pull/2206
