### ISSUE TITLE
[bug] switch: attachInternals is undefined in Safari

### ISSUE THREAD

**Issue by kylebuch8** [patternfly/patternfly-elements#2214]
![image](https://user-images.githubusercontent.com/330256/199103044-c956249f-c375-4810-996d-eb3e0bdcdac0.png)

In Safari, switch fails to render because `this.attachInternals` is undefined.

## Steps to reproduce
- Open https://patternflyelements.org/components/switch/ in Safari
- View the console

The demo page, https://patternflyelements.org/components/switch/demo/, works fine because it imports `element-internals-polyfill`.

I think we'll need to add some guidance about including this polyfill when switch is used.

**Comment by kylebuch8** [comment]
It looks like we'll need to include `element-internals-polyfill` prior to pfe.min.js being added to the page.

**Comment by bennypowers** [comment]
yes, we need to polyfill for now. luckily, [webkit has already implemented element internals](https://github.com/WebKit/WebKit/pull/2690), so the polyfill period will not be very long
