### ISSUE TITLE
[bug] switch: docs pages show both on and off message

### ISSUE THREAD

**Issue by kylebuch8** [patternfly/patternfly-elements#2224]
![image](https://user-images.githubusercontent.com/330256/200319268-11c72af4-4ed5-4a12-bf48-070f3d5b6efe.png)

There is an issue where both the on and off messages are shown when the `id` of `pfe-switch` is equal to `disabled`. Visit https://patternflyelements.org/components/switch/#disabled to see the issue.

**Comment by kylebuch8** [comment]
After a review of the page, there is an `h3` that receives an `id` of `disabled`. The example code also has an `id` of disabled which causes the conflict.

**Comment by bennypowers** [comment]
is that id conflict (on the page) the root cause?
