### ISSUE TITLE
rh-autocomplete

### ISSUE THREAD

**Issue by Homa** [patternfly/patternfly-elements#223]
Create an element for async search autocomplete
- [x] write the element
- [x] theming
- [x] write test 
- [x] accessibility test

**Comment by starryeyez024** [comment]
@Homa  https://github.com/RHElements/rhelements/pull/249#pullrequestreview-178610111

**Comment by starryeyez024** [comment]
Where are the mockups for this?

**Comment by starryeyez024** [comment]
@Homa ^^ are there mockups for this component?

**Comment by Homa** [comment]
@starryeyez024 no we don't have any mockups. I replace 'search' with search icon.

**Comment by ajacobs21e** [comment]
@Homa I'm playing with the demo now and it seems to be working well - I can use the keyboard or mouse to select, keyboard to move up and down the list, and the clear works. 

Do we want the ability to hold down the arrow key to scroll through the list quickly?

This component is matching the needs of autocomplete - it is showing exact matches that start with what the user has started typing. For example, the input "Uni" autocompletes to "United States".
However, I believe this component should be providing matches to any part of the results. For example, if I type "States" I should match to "United States" or if on the Dashboard I type in "Mitre" I should see the result "The Mitre Corp.".

**Comment by Homa** [comment]
@ajacobs21e 

> @Homa I'm playing with the demo now and it seems to be working well - I can use the keyboard or mouse to select, keyboard to move up and down the list, and the clear works.
> 
> Do we want the ability to hold down the arrow key to scroll through the list quickly?
> 
> This component is matching the needs of autocomplete - it is showing exact matches that start with what the user has started typing. For example, the input "Uni" autocompletes to "United States".
> However, I believe this component should be providing matches to any part of the results. For example, if I type "States" I should match to "United States" or if on the Dashboard I type in "Mitre" I should see the result "The Mitre Corp.".

**Comment by ajacobs21e** [comment]
Hi @Homa 

> The response depends of the result that is provided to component from outside of the component.

Does this mean that it's up to the consuming app to decide if it will show results that match any part of the result versus the beginning of the result?

**Comment by Homa** [comment]
@ajacobs21e Correct. When user types, by each keyboard stroke, a function outside of the component runs. Typed phrase is pass the to the function. Based on the phrase, the function returns options list back to the component.

**Comment by ajacobs21e** [comment]
Thanks @Homa !

**Comment by starryeyez024** [comment]
https://patternflyelements.com/elements/pfe-autocomplete/demo/
