### ISSUE TITLE
pfe-label has incorrect version

### ISSUE THREAD

**Issue by zeroedin** [patternfly/patternfly-elements#2248]
`<pfe-label>` is at version `1.0.0-next.x` rather than `2.0.0-next.x`

This was done as my understanding at the time was these components were versioned independently.  Given changes to the project over time, I believe this should be aligned with other components in the 1:1 pfe 2.0 project. Take `pfe-switch` which started at version `2.0.0-next.x` as an example.

@bennypowers let me know how you'd like me to approach this fix.

**Comment by bennypowers** [comment]
if it doesn't break anything leave it and it'll be solved by #2134

**Comment by zeroedin** [comment]
Sounds good.
