### ISSUE TITLE
[bug] tooltip: double tab index when wrapped around focusable element

### ISSUE THREAD

**Issue by heyMP** [patternfly/patternfly-elements#2258]
## Description of the issue

When pfe-tooltip is wrapped around a focusable element like anchor or button, there is an extra focus effect.

### Impacted component(s)

- pfe-tooltip

### Steps to reproduce

1. Go to https://patternflyelements.com/components/tooltip/
2. Tab through the buttons on the demo page.
3. You'll see that there is a focusable item for the tooltip invoker AND one for the button

### Expected behavior

I don't think tooltips should have there own tabindex.  They should only monitor focusin, focusout and similar events.

Reference: 

> A tooltip provides extra information about a form field, a link, a button, or other focusable element. It must be triggered by both focus and hover events and remains on the screen as long as the trigger has the focus. The focus does not move to the tooltip.

[https://dequeuniversity.com/library/aria/tooltip](https://dequeuniversity.com/library/aria/tooltip)

### Screenshots

Bug:

https://user-images.githubusercontent.com/3428964/206749810-cacea7fb-4c37-4b51-a5e8-29c27df6d038.mp4

Expected behavior:

https://user-images.githubusercontent.com/3428964/206749890-c2b6dc85-c753-42fb-85e7-51ba524db913.mp4

### Proposal

```patch
diff --git a/elements/pfe-tooltip/BaseTooltip.ts b/elements/pfe-tooltip/BaseTooltip.ts
index 8f5615919..24054fa27 100644
--- a/elements/pfe-tooltip/BaseTooltip.ts
+++ b/elements/pfe-tooltip/BaseTooltip.ts
@@ -63,7 +63,8 @@ export abstract class BaseTooltip extends LitElement {
   }

   #addListeners() {
-    this.addEventListener('focus', this.show);
+    this.addEventListener('focusin', this.show);
+    this.addEventListener('focusout', this.hide);
     this.addEventListener('blur', this.hide);
     this.addEventListener('tap', this.show);
     this.addEventListener('click', this.show);
@@ -74,7 +75,7 @@ export abstract class BaseTooltip extends LitElement {
   override render() {
     const { initialized } = this.#domController;
     return html`
-      <div id="invoker" part="invoker" role="tooltip" tabindex="0" aria-labelledby="tooltip">
+      <div id="invoker" part="invoker" role="tooltip" aria-labelledby="tooltip">
         <slot></slot>
       </div>
       <div id="tooltip" aria-hidden=${!this.#isOpen} class=${classMap({ initialized })}>
```

**Comment by brianferry** [comment]
Agreed, the tooltip doesn't need a tabindex.  The browser should be able to handle the tabs through the lightdom or the elements themselves. I updated https://github.com/patternfly/patternfly-elements/pull/2257 with these changes too

**Comment by nikkimk** [comment]
Chiming in to agree. From: https://w3c.github.io/aria-practices/#tooltip

> Keyboard Interaction
Escape: Dismisses the Tooltip.

> NOTE
Focus stays on the triggering element while the tooltip is displayed.
If the tooltip is invoked when the trigger element receives focus, then it is dismissed when it no longer has focus (onBlur). If the tooltip is invoked with mouseIn, then it is dismissed with on mouseOut.

**Comment by nikkimk** [comment]
Additionally if they are a part of a toolbar, like in the audio-player, for example, they need to be dismissible with the ESC key
