### ISSUE TITLE
It's too hard to read the document website on large display

### ISSUE THREAD

**Issue by tomoyanime** [patternfly/patternfly-elements#2299]
## Description of the issue

The padding value becomes too big on the large display size (e.g. 1920 x 1080) so it's hard to view the document.

### Impacted component(s)

- none

### Steps to reproduce

1. Go to [the website](https://patternflyelements.org/)
2. See error

### Expected behavior

The padding value shouldn't be so big on the large display.

### Screenshots

![Screenshot (107)](https://user-images.githubusercontent.com/31934952/210401449-398a3b70-ed30-4b28-8f04-4c59b23fdcba.png)
![Screenshot (108)](https://user-images.githubusercontent.com/31934952/210401452-75081238-5893-4911-af62-e834c25f81f5.png)

**Comment by bennypowers** [comment]
#2297 should fix this

**Comment by tomoyanime** [comment]
@bennypowers It's fixed. Thanks!
