### ISSUE TITLE
pfe-tabs inset implementation is incorrect

### ISSUE THREAD

**Issue by zeroedin** [patternfly/patternfly-elements#2323]
Incorrect implementation of inset.

Inset uses a [key, value] set of breakpoints to determine the amount of inset, not individually set as `sm|md|lg...` per tab set.  

```
inset={{
  default: 'insetNone',
  md: 'insetSm',
  xl: 'insetLg',
  '2xl': 'inset2xl'
}}
```

**Comment by bennypowers** [comment]
Closed by #2329
