### ISSUE TITLE
pf-avatar missing dark variant image implementation

### ISSUE THREAD

**Issue by zeroedin** [patternfly/patternfly-elements#2324]
Patternfly v4 has a dark variant avatar image:  https://github.com/patternfly/patternfly-elements/issues/2323

The current version of avatar does not implement this feature.  The dark avatar svg is available in the component, the attribute and image swap need to be added.

**Comment by bennypowers** [comment]
@anujsingla asked to grab this

**Comment by anujsingla** [comment]
I have made changes for this issue - https://github.com/patternfly/patternfly-elements/pull/2357
closing this issue.
