### ISSUE TITLE
pfe-cta: Rounded corners should not be the default

### ISSUE THREAD

**Issue by kylebuch8** [patternfly/patternfly-elements#236]
There is already a CSS variable ui--border-radius but we need to expose a variable in the rh-cta.scss: 

--rh-cta--ui--border-radius: ui--border-radius;   

Can we set the theme variable to default  to 0px?
--ui--border-radius: 0px

**Comment by markcaron** [comment]
Default for what? Red Hat or the community?

Currently the default is for the base RH Elements, which is community-based. So, I don't agree that we should make the fallback 0px.

A theming developer can easily change this with CSS vars to square corners. This would be the proper approach to making a site, like Red Hat's, have square corners (which is our Brand's preference).

**Comment by markcaron** [comment]
If you're wanting to expose a custom, component-level var, we can do that. The border-radius statement would need to look like:

```
border-radius: calc(var(--rh-cta--ui--border-radius, #{rh-var(ui--border-radius)}) * 20);
```

This would give us a more broad stroke to turn ONLY CTAs square/round. But, I don't think we should set the default (fallback in rh-sass) to be 0px.

**Comment by castastrophe** [comment]
+1 @markcaron, I like your solution.  What would you think of slightly reducing the rounded corner in the community project though?  I'm also curious why it's multiplied by 20?
