### ISSUE TITLE
'failed to load' error message template

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-elements#237]
Based on error messages for the Red Hat Dashboard and Solution Engine, I am proposing a template for when something fails to load:
![error message](https://user-images.githubusercontent.com/6415742/48091940-39e10080-e1d9-11e8-932f-e3a8f7736b96.png)

the {description} should be descriptive enough for the user to know what didn't load while still being concise. 
The _let us know_ link should open a feedback form, if one exists. 

@KrystalMoore16 Is this something that would be a component or would just be part of our documentation?

**Comment by castastrophe** [comment]
I love the idea of using something like this for standardization of messaging.  How would translations be handled?

**Comment by castastrophe** [comment]
@ajacobs21e @KrystalMoore16  Is this still relevant?

**Comment by ajacobs21e** [comment]
I think this is covered by the PF UX writing guidance: https://www.patternfly.org/v4/ux-writing/error-messages

FYI @jkbrock this might be more appropriate for a Portal style guide
