### ISSUE TITLE
[pfe-tools]: dev-server doesn't reflect changes to .css files

### ISSUE THREAD

**Issue by heyMP** [patternfly/patternfly-elements#2387]
## Description of the issue

When developing elements using `npm run start` changes to `.css` files aren't reflected in the browser.  You need to stop the dev-server and restart it for the new css to be seen.

### Impacted component(s)

- All components

### Steps to reproduce

1. `nvm use`
2. `npm run clean:nuke`
3. `npm run ci`
4. `npm run build`
5. `npm run start`
6. Visit: http://localhost:8000/components/label/demo/
7. In your IDE, edit the `elements/pf-label/pf-label.css` file and add a the following css
```css
:host {
  display: none;
}
```
8. Verify that the css change was not reflected on the demo page in your browser.

### Expected behavior

CSS changes should immediately seen in your browser.

## Related issues

- https://github.com/RedHat-UX/red-hat-design-system/pull/735

**Comment by bennypowers** [comment]
Following your steps, after step 7, I confirmed that
- saving the file refreshed the page
- there was no change to the label styles in the browser.
But then, if I *saved the file one or two more times* then the changes appeared, and subsequently all new changes were immediate

do you have the same experience @heyMP, @brianferry ?

**Comment by bennypowers** [comment]
adding this middleware to web-dev-server.config.js appears to update the cache headers on each request, however it appears that I still have to refresh two or three times before changes will appear

```ts
async function cacheBusterMiddleware(ctx: Context, next: Next) {
  if (ctx.path.match(/elements\/[\w-]+\/[\w-]+.css$/)) {
    const lm = new Date().toString();
    const etag = Date.now().toString();
    ctx.response.set('Cache-Control', 'no-store,no-cache,must-revalidate');
    ctx.response.set('Pragma', 'no-cache');
    ctx.response.set('Last-Modified', lm);
    ctx.response.etag = etag;
    console.log(ctx.path, etag, lm);
  }
  return next();
}

```
