### ISSUE TITLE
patternflyelements.org/components does not display examples

### ISSUE THREAD

**Issue by jasonawant** [patternfly/patternfly-elements#2391]
## Description of the issue
When navigating to a component detail page, e.g. https://patternflyelements.org/components/button/, examples are not displayed for the v2 prerelease version.

### Impacted component(s)
- all components for v2 prerelease

### Steps to reproduce

1. Go to [view button component](https://patternflyelements.org/components/button/)
2. Choose v1 in the version selector at top right of page
3. Observe examples rendered under the overview heading
 
![image](https://user-images.githubusercontent.com/4835629/221667443-1a05b1a4-fe95-4045-b210-9bff7be02114.png)

4. Change version to v2 prerelease
5. Observe no examples of button below overview heading

![image](https://user-images.githubusercontent.com/4835629/221667692-0060d783-1d5e-4d53-8583-5b389d0de296.png)

### Expected behavior
Expected to see examples as seen with v1 version.

**Comment by jasonawant** [comment]
@kylebuch8 wow, that was fast! 

I should have included links to all component detail paths/pages. I'm not sure if other components are impacted by the same bug or a different bug.

These components appear to not render correctly.
- https://patternflyelements.org/components/card/
- https://patternflyelements.org/components/jump-links/
- https://patternflyelements.org/components/tabs/
- https://patternflyelements.org/components/panel/

I can create a new issue for these if needed.

**Comment by jasonawant** [comment]
These components' v2 prerelease versions are rendering as expected b/c they are WIP

**Comment by kylebuch8** [comment]
Yeah, the docs pages aren't completely filled out yet. We'll be sure to get everything updated.
