### ISSUE TITLE
[bug] pf-panel styles for raised and bordered 

### ISSUE THREAD

**Issue by zeroedin** [patternfly/patternfly-elements#2402]
## Description of the issue

Styles for `pf-panel` for raise and bordered variants do not seem to be working correctly.

See [pf-panel demo](https://patternflyelements.com/components/panel/demo/) and compare to [PFv4 panel](https://www.patternfly.org/v4/components/panel)

https://www.patternfly.org/v4/components/panel/#bordered
https://www.patternfly.org/v4/components/panel/#raised

**Comment by anujsingla** [comment]
Yes, I will take this issue.

**Comment by anujsingla** [comment]
I have made changes for this issue - https://github.com/patternfly/patternfly-elements/pull/2436
closing this issue.
