### ISSUE TITLE
Existing layout classes don't seem to be working in storybook

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#241]
https://rhelements.github.io/rhelements/?selectedKind=Layouts&selectedStory=rh-layouts&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybooks%2Fstorybook-addon-knobs

**Comment by starryeyez024** [comment]
@markcaron @kylebuch8 this seems to be fixed when i spin up storybook in the master branch, however its broken on the public-facing version:
  https://www.patternfly.org/patternfly-elements/?selectedKind=Layouts&selectedStory=rh-layouts&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybooks%2Fstorybook-addon-knobs

**Comment by castastrophe** [comment]
I believe this is now resolved; please re-open if the issue reoccurs!
