### ISSUE TITLE
[bug][docs] Accordion page load sets focus further down the page

### ISSUE THREAD

**Issue by markcaron** [patternfly/patternfly-elements#2454]
Not sure why, but the [accordion page](https://patternflyelements.org/components/accordion/) jumps the focus down the page automatically when it loads.

**Comment by zeroedin** [comment]
@brianferry can you take a look at this?  I believe we discussed this at some point.

**Comment by brianferry** [comment]
We do call a `header.focus()` when you have an auto expanded tab in the accordion, maybe we should remove that
