### ISSUE TITLE
use pf-tabs in React project will get error

### ISSUE THREAD

**Issue by kunyan** [patternfly/patternfly-elements#2491]
## Description of the issue

When I use `pf-tabs` in a React project, it will show errors in console, and `pf-tabs` is not be able to render as expected

The other components like `pf-tab` and `pf-tab-panel` works good

### Impacted component(s)

- pf-tabs

### Steps to reproduce

https://stackblitz.com/edit/vitejs-vite-sq6x63?file=src/App.tsx

### Screenshots

<img width="531" alt="Screenshot 2023-05-06 at 22 42 48" src="https://user-images.githubusercontent.com/752130/236630991-997cee4b-9c07-404b-92a3-3f0edd91974e.png">
<img width="1289" alt="Screenshot 2023-05-06 at 22 43 15" src="https://user-images.githubusercontent.com/752130/236631029-f9644205-1646-4cad-a5ed-f34eef735786.png">

**Comment by kunyan** [comment]
This issue still present in latest v2.2.1 @bennypowers 

https://stackblitz.com/edit/vitejs-vite-d4qjyz

**Comment by bennypowers** [comment]
Thanks for the report. The problem is here https://github.com/patternfly/patternfly-elements/blob/933a0d6dd06c33d43291e5ed0ab87914fefd9a67/elements/pf-tabs/BaseTabPanel.ts#L10

i will issue a pr soon, as I'm travelling

**Comment by bennypowers** [comment]
please try with https://github.com/patternfly/patternfly-elements/releases/tag/%40patternfly/elements%402.2.2
