### ISSUE TITLE
roving-tabindex-controller listeners should only handle focusable item events.

### ISSUE THREAD

**Issue by nikkimk** [patternfly/patternfly-elements#2496]
## Description of the issue

`roving-tabindex-controller` currently listens for keydown events on the items' common ancestor container, which works in cases where the items share a common ancestor, like for tabs or menus, but for accordions, the listener is also capturing panel key events.

### Impacted component(s)

- `pf-accordion`

### Steps to reproduce

1. Go to the [Fixed Panel demo](https://deploy-preview-2493--patternfly-elements.netlify.app/components/accordion/demo/)
2. Expand **Item three**.
3. Tab to **Focus on me!** 
4. Use arrow keys. 
5. The focus changes to  another **Fixed panel** heading. 

### Expected behavior

The listener should ignore arrow keys from inside a panel.

## Related issues

- [#2493](https://github.com/patternfly/patternfly-elements/pull/2493)

**Comment by bennypowers** [comment]
does #2493 address this?
