### ISSUE TITLE
Move guidelines documentation into repo docs

### ISSUE THREAD

**Issue by castastrophe** [patternfly/patternfly-elements#25]
Would suggest we get together and build out some usage guidelines for folks using and contributing to rhelements.  Things to include:

- Best practices, how to write a component
- Namespacing guidelines, what's taken and what's allowed
- Naming conventions, how to name a component

**Comment by mwcz** [comment]
Related to #22

**Comment by mwcz** [comment]
Oh yeah, here's a [WIP branch](https://github.com/RHElements/rhelements/tree/readme-spruce) where I started to trim down the main README to be easily digestible, and moved contribution stuff to CONTRIBUTING.md.  It still needs a *lot* of work, the bullets you suggested!
