### ISSUE TITLE
Compiled files moved to a dist directory

### ISSUE THREAD

**Issue by castastrophe** [patternfly/patternfly-elements#251]
Rather than the compiled files for each element being stored in the root of the folder, it would be helpful to generate them into a dist directory.  Ideally the dist directory would be hidden from git so that it is not committed except in the tag releases.

**Comment by starryeyez024** [comment]
Just adding my emphatic +1 to this issue. I am constantly getting git conflict tangles around the generated javascript files.

**Comment by castastrophe** [comment]
Demo branch: https://github.com/patternfly/patternfly-elements/pull/258

**Comment by mwcz** [comment]
@starryeyez024 You should see a LOT fewer merge conflicts now that #273 is merged in.  This issue here is absolutely still on the table, but in the meantime the merge conflict pain should subside. :)

**Comment by starryeyez024** [comment]
@castastrophe can we close this issue or do you still feel like the structure needs tidying?

**Comment by castastrophe** [comment]
@starryeyez024 I would still really like a dedicated dist directory which is the original ask of the issue :)

**Comment by starryeyez024** [comment]
Notes: probably we want to flatten the directory structure inside of /dist. 

/dist
    - pfe-accordion.js
    - pfe-accordion.min.js
    - pfe-accordion.umd.min.js

Note, do we need to include the CSS files?

**Comment by castastrophe** [comment]
This is the updated demo branch: https://github.com/patternfly/patternfly-elements/pull/380

**Comment by castastrophe** [comment]
@starryeyez024 For the purposes of debugging, it helps to have a copy of the css compiled by itself but we don't have to commit that during a tag release.  We can also have separate build tasks for releases than for development.

**Comment by castastrophe** [comment]
I also think you were looking at the older demo re: "flatten the directory structure inside dist" because the current demo already does that.
