### ISSUE TITLE
Add Firefox ESR to testing matrix

### ISSUE THREAD

**Issue by zhawkins** [patternfly/patternfly-elements#2510]
>  if it's not too much trouble can you open an issue on pfe and rhds to add ff esr to the testing matrix? cheers
- Benny

😄

**Comment by bennypowers** [comment]
Firefox 115 is slated for an esr release June or July. Presumably, RHEL will pick it up then. I suggest that from that point on we begin testing Firefox ESR with playwright

**Comment by bennypowers** [comment]
https://github.com/microsoft/playwright/issues/27542#event-12563761524
