### ISSUE TITLE
perform build steps in a temp directory to stop browsersync frenzy

### ISSUE THREAD

**Issue by mwcz** [patternfly/patternfly-elements#252]
Currently, build steps are performed in the root dir of each element, which triggers browsersync (`npm start`) to refresh a bunch of times.  "Hiding" the in-progress build files from browsersync by doing it in a temp directory would fix that, and then copy the built result back into the current location.

**Comment by mwcz** [comment]
Hit a wall with this before the break.  For example, by running rollup on `elements/rh-card/.build/rh-card.js` instead of `elements/rh-card/rh-card.js`, relative paths no longer line up.  I scoured rollup config for a way around this, but I don't think it's going to work.

**Comment by castastrophe** [comment]
If you have a demo branch on this, I'd love to take a look.  Maybe there's some cross-over on the code we've been working on.

**Comment by mwcz** [comment]
@castastrophe I still have the branch, but in a tumultuous state!  Would you still like to see it?

**Comment by castastrophe** [comment]
Yes please!
