### ISSUE TITLE
[bug] pf-accordion collapses last panel when internal checkbox is checked

### ISSUE THREAD

**Issue by brianferry** [patternfly/patternfly-elements#2537]
## Description of the issue

Noticed this while converting the product trials preview panel from the original `pfe-accordion` to `pf-accordion`.  When you have a checkbox in the panel it will close the first or next panel in the accordion.  This is because when we do a check for the collapse function we do not cancel -1 indexes which indicate that it comes from a non-pf-accordion element. 

### Impacted component(s)

- 

### Steps to reproduce

1. Go to [codepen](https://codepen.io/OhHeyBrian/pen/vYQeLoX)
2. Click on the checkbox in the accordion panel
3. See that it closes the panel unexpectedly 

### Expected behavior

1. Clicking an internal element that is not the accordion element should not result in the panel being collapsed.

**Comment by bennypowers** [comment]
Closed by #2538
