### ISSUE TITLE
Need placeholder property for pf-text-input component

### ISSUE THREAD

**Issue by kishori-patil1** [patternfly/patternfly-elements#2594]
We have a design requirement where we need to add placeholder text in text input. Currently, I don't see this prop present for the pf-text-input component. We need this prop to be added so that we can easily add the placeholder text.

### Impacted component(s)

- pf-text-input

## Related issues

- None

**Comment by bennypowers** [comment]
Thank you for the issue, @kishori-patil1 . This will release with v2.5.0 when https://github.com/patternfly/patternfly-elements/pull/2596 merges
