### ISSUE TITLE
[Discussion] how to facilitate webcomponent

### ISSUE THREAD

**Issue by daKmoR** [patternfly/patternfly-elements#260]
hey,

we are trying to establish a best practice for how to facilitate webcomponent. Our current status can be seen on [github](https://github.com/open-wc/open-wc) and on a [project page](https://open-wc.org/). 

I think especially interesting for this project could be to start testing with karma and some utils.
I, for example, love using `await fixture()` and doing semantic dom comparisons in tests. It's really powerful. Take a look [here](https://open-wc.org/recommendations/testing-chai-dom-equals.html#test-dom-of-an-element).

We also have a default storybook setup which results in something like [this set game example](https://example-set-game-open-wc.netlify.com/).

It could maybe make your setup for storybook easier as well :)

Overall this is about getting in contact and hopefully, we can in some areas work together and make great webcomponent :)

just let me know what you think :)

**Comment by castastrophe** [comment]
Hi @daKmoR, I'm so glad this conversation has been started and I hope we can collaborate more in the future.  Since there isn't a clear action item from this issue I am going to close it out but don't hesitate to reach out to us with additional ideas.  In the meantime, if you're interested in updates, please subscribe to our mailing lists:

- [patternfly-elements-announce@redhat.com](https://www.redhat.com/mailman/listinfo/patternfly-elements-announce): General announcements about the project
- [patternfly-elements-contribute@redhat.com](https://www.redhat.com/mailman/listinfo/patternfly-elements-contribute): For active contributors

**Comment by daKmoR** [comment]
hey :) 
I think `@open-wc/testing` should be really useful now. Karma with the latest version of karma-webpack is finally ready for webcomponents. So if you want to make it a concrete action I could make a PR for e.g. converting the [pfe-number tests](https://github.com/patternfly/patternfly-elements/blob/master/elements/pfe-number/test/pfe-number.html) to karma.
You could take a look at the result and see if it's something you would be interested in.

if you prefer wct over karma then yeah there would probably no action right now 🙈 

just let me know 🤗

**Comment by castastrophe** [comment]
That would be great - I like the idea of opening a focused PR for an actionable item.

I did a little looking into Karma and didn't really see a benefit in it over wct. What we really need is more browser control like what webdriver provides - ability to trigger events, change the viewport, take visual snapshots, etc.  So as far as migrating our repo, my vote would be in moving it to webdriver but I could be dissuaded.

**Comment by daKmoR** [comment]
I think having one testing solution that does everything will be tough... and in that case, you are right if you want to do everything then a full-blown selenium based solution like webdriover.io or as a non selenium alternative cypress will be good.
I would consider these e2e tests which are highly valuable for full applications.

However, especially for leaf webcomponents it's mostly about making sure that the component renders its dom, sets attributes, properties and fires events correctly. These are more unit/integration tests. And for something like this karma with webpack bundling seems to be a good fit. It's smaller and faster.
And in comparison to WCT there is:
- works fully with js files (incl. es modules)
- WCT dependencies are outdated
- does not dictate what you use (we use it with latest mocha, chai, sinon...)
- does not need selenium
- ...

We also had some discussions about it here: https://github.com/open-wc/open-wc/issues/74#issuecomment-445180197

I can fully understand if you guys still don't need/want it - no hard feelings :)
If you would like to have a PR to take a look - just let me know I'm happily investing some time to show it :)
