### ISSUE TITLE
Remove BaseAccordion*

### ISSUE THREAD

**Issue by bennypowers** [patternfly/patternfly-elements#2612]
Affects `<rh-accordion>`

**Comment by bennypowers** [comment]
@zeroedin I think this should be considered along with #2624 and #2577

**Comment by zeroedin** [comment]
> @zeroedin I think this should work should be done in consideration of #2624 and #2577. in other words, tabs controller and baseaccordion have significant overlap

I did some work on #2577 today just to get it in line with expectations for `3.0` organizing and putting the tabs controller under core.  I can start looking at abstracting whatever we call this new controller that is shared between tabs and accordion now I think a bit more clearly.

**Comment by bennypowers** [comment]
Closed by #2764
