### ISSUE TITLE
Decorator classes for listbox controller

### ISSUE THREAD

**Issue by nikkimk** [patternfly/patternfly-elements#2645]
All these reactive accessor pairs are *just fine the way they are*, but i'm just floating the option to write a decorator for class fields instead

_Originally posted by @bennypowers in https://github.com/patternfly/patternfly-elements/pull/2570#discussion_r1354367678_

**Comment by bennypowers** [comment]
Closing since this is a very low priority. if anyone wants to pick up such a refactor in the future, have at 'em, but it's not something we need to focus on
