### ISSUE TITLE
replace usage of @cascades in favor a context implementation in `pf-tabs`

### ISSUE THREAD

**Issue by zeroedin** [patternfly/patternfly-elements#2651]
> [bennypowers](https://github.com/bennypowers) [5 hours ago](https://github.com/patternfly/patternfly-elements/pull/2577#discussion_r1413636838)
If there's any way to get rid of these @cascades decorators (maybe a context?) it would help simplify things quite a bit IMO
>
> can be a followup

Look at replacing in favor of context.

**Comment by bennypowers** [comment]
Fixed by #2699
