### ISSUE TITLE
pfe-card | Clickable card design & interactions

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-elements#266]
Card options currently in the Portal component library:
Default card 
![screen shot 2018-12-17 at 1 14 46 pm](https://user-images.githubusercontent.com/6415742/50106454-dc8b9680-01fd-11e9-9995-0cdd90fc5250.png)

Card link
![screen shot 2018-12-17 at 1 15 01 pm](https://user-images.githubusercontent.com/6415742/50106545-207e9b80-01fe-11e9-921b-2fa2ec5c1845.png)
![screen shot 2018-12-17 at 1 17 46 pm](https://user-images.githubusercontent.com/6415742/50106555-2a080380-01fe-11e9-9308-917c7ea1af06.png)

Card with tags
![screen shot 2018-12-17 at 1 15 35 pm](https://user-images.githubusercontent.com/6415742/50106560-2e342100-01fe-11e9-8e2a-dc2e2029f987.png)

Card with CTA
![screen shot 2018-12-17 at 1 14 53 pm](https://user-images.githubusercontent.com/6415742/50106505-03e26380-01fe-11e9-948f-f02a8d266faf.png)

There is no visual difference between a default non-clickable card and the card link except that card link has a hover state. 

Cards with tags are used sparingly and not consistently to indicate if a card is clickable or not.

Cards with CTAs the card is not clickable but it does have a clickable element (button).

We need to standardize a design moving forward for cards that are and are not clickable.
@KrystalMoore16 proposes using card with tags for non-clickable cards. However, this conflicts with the product selector for the Solution Engine on the home page - this component is not a card but visually looks like a card with tag.
![screen shot 2018-12-17 at 1 22 11 pm](https://user-images.githubusercontent.com/6415742/50106782-c8946480-01fe-11e9-836a-302c0ea52403.png)

We'll also have to decide whether or not card with CTA get the clickable or non-clickable treatment.

**Comment by samlinville** [comment]
Posting from our chat in #cp-design:

are we saying that clickable cards get a blue side border? this would make the most sense to me given that our other interactable elements are generally blue.

**Comment by castastrophe** [comment]
@ajacobs21e I know this is from a while ago but I wanted to follow-up: is the request in this issue to add a clickable card feature for pfe-card?  Are we discussing what that design should look like in this issue?

**Comment by ajacobs21e** [comment]
@castastrophe This isn't relevant anymore now that the Portal is using the PF design system. Thanks for checking!
