### ISSUE TITLE
[docs] remove duplicate chip demos from docs page

### ISSUE THREAD

**Issue by hellogreg** [patternfly/patternfly-elements#2667]
## Description of the issue

The chip demo section appears twice on the [chip docs page](https://patternflyelements.org/components/chip/).

The page is currently structured like this, so that it starts over at "Default" after "Chip group with removable categories": 

- **Default** (first occurrence)
- Chip variants
    - Read-only
    - Overflow chip
    - Max-width
- Chip group
    - Chip group with categories
    - Chip group with removable categories
- **Default** (second occurrence)
- _...and so on..._
 
### Expected behavior
The demos should only appear once. Delete the duplicate group of demos.

**Comment by bennypowers** [comment]
This is a bug in the `band` shortcode and affects every page that uses it, e.g. the card docs. Thanks for the report, Greg!
