### ISSUE TITLE
select: disabling filter does not work

### ISSUE THREAD

**Issue by nikkimk** [patternfly/patternfly-elements#2668]
## Description of the issue

Select has an variant to disable option filtering, but it is not working.

### Impacted component(s)

- `pf-select`
- `pf-listbox`

### Steps to reproduce

1. Go to [Select documentation -> Disable filtering](https://patternflyelements.org/components/select/#disable-filtering-1)
2. Type "B".

### Expected behavior

All options should be showing.

**Comment by bennypowers** [comment]
I can take this one

**Comment by bennypowers** [comment]
does upstream have a feature to disable the filter in this way? http://v4-archive.patternfly.org/v4/components/select I couldn't find it here

**Comment by bennypowers** [comment]
let's come back to this in pfev5
