### ISSUE TITLE
`<pf-tabs>`: roles not being read

### ISSUE THREAD

**Issue by Arathy-s** [patternfly/patternfly-elements#2692]
## Description of the issue

Elements with an ARIA [role] that require children to contain a specific [role] are missing some or all of those required children.

### Impacted component(s)

- All the pages which uses pfe-tabs

### Screenshots

![Screenshot 2024-02-08 at 3 23 25 PM](https://github.com/patternfly/patternfly-elements/assets/49025521/18a0aa97-417e-4685-97fd-a9e885085101)

**Comment by bennypowers** [comment]
Which browser and version? Which os?

**Comment by Arathy-s** [comment]
Browser: Chrome
Version:  121.0.6167.139
OS: macOS Sonoma 14.3

The issue can be reproduced on running a lighthouse scan on https://patternflyelements.org/components/tabs/.

**Comment by zeroedin** [comment]
@bennypowers could this be a element internals/cross root aria issue, I'm leaning towards that it is?  /cc @nikkimk 

`this.#internals.role = 'tab';` is set in PfTab and `this.#internals.role = 'tabpanel';` is set in PfTabPanel, but those don't seem to get reported to the `role="tablist"` that is set on the slot in the parent PfTabs.   

A work around right that passes the lighthouse check is setting `role="tab"` and `role="tabpanel` directly on the `pf-tab` and `pf-tab-panel` elements.

If it indeed a cross root aria issue, then we should have the element write these attributes out on the host element instead of trying to use element internals here.  Thoughts?

**Comment by bennypowers** [comment]
yeah my gut reaction was that this is a ua thing, but it would be better to try and rule out our own code first.

**Comment by hellogreg** [comment]
Doing some testing on this. One odd thing on the [docs page](https://patternflyelements.org/components/tabs/) is that, if you click on (or shift keyboard focus for) a tab in one of the demos, it also changes which tab is selected in the "Reacting to changes" **HTML**/**Lit**/**React** tablist!

If you click on the first tab in any example on the page (e.g., **Users** in this screencap), then **HTML** will be selected. If you click on the second tab (e.g., **Containers** below), then **Lit** gets selected.
<img width="423" alt="screencap of the Tabs docs page" src="https://github.com/patternfly/patternfly-elements/assets/642695/cbba0882-a456-478f-be6a-cd43acb9408a">

This video shows what I mean: 
[Video of Tabs docs page issue](https://drive.google.com/file/d/1jH_nolHX8iJykAmSLOkoAfe_yfhQwAjy/view?usp=sharing)

Not sure if this is at all related, but something I noticed in multiple browsers.

**Comment by hellogreg** [comment]
Did some basic real-world keyboard and screen reader testing too, with the following desktop combos:

- Mac Safari and VoiceOver
- Win Chrome and JAWS
- Win Firefox and NVDA

First, keyboard usage without a screen reader on works in all browsers.

However, with screen readers on...

### Mac
Safari and VoiceOver work fine for navigating the tabs. The screen reader switches to focus mode when focus is within the tab group, and the tabs can be operated via the arrow keys.

However, if you are just having VoiceOver read the page content, it does _not_ read the individual tab headings. Instead, it announces the tab group, and then does so again for each of the tabs within.

In other words, for the following example...
<img width="385" alt="screencap of a tab group" src="https://github.com/patternfly/patternfly-elements/assets/642695/d6b7290c-bf83-4525-8d9c-76448b6b691e">

VoiceOver says, "Users and two more items, tab group," four times in a row. Once for the tab group, and once for each tab.

### Windows
Interestingly, neither Chrome/JAWS nor Firefox/NVDA automatically enter focus mode for the tab groups. So the arrow keys do nothing, At least not at first.

In JAWS, the tabs can be navigated in browse mode via the apostrophe (and shift-apostrophe) key, and then selected. Focus mode _cannot_ be entered manually (via the enter key), though this should be possible.

In NVDA, the user _can_ enter focus mode manually (via the NVDA-space key combo), after which the tabs work as expected via the arrow keys.

### Our tabs compared to WAI
I tested the [WAI tabs example](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-automatic/) with the same combos.

The results:
- Safari/VoiceOver: Works as expected (and doesn't have the read mode issue).
- Firefox/NVDA: Works as expected. Enters focus mode automatically (unlike ours).
- Chrome: Does not auto-enter focus mode (like ours). However, focus mode _can_ be turned on manually (via enter key). Apostrophe navigation works in browse mode.

**Comment by bennypowers** [comment]
I want to make some changes in TabsController which I believe will help with some of the issues raised here

**Comment by bennypowers** [comment]
blocked by https://github.com/patternfly/patternfly-elements/pull/2677

**Comment by bennypowers** [comment]
@hellogreg @nikkimk @Arathy-s is this still an issue after #2677 and #2695 were both merged?
