### ISSUE TITLE
Add support for running individual tests locally

### ISSUE THREAD

**Issue by castastrophe** [patternfly/patternfly-elements#271]
Running `npm test` locally triggers the following: `npm run build && wct --configFile wct.conf.json test/index.html`.

I'm proposing a way to pass in an argument to allow running isolated local tests which are great for use while writing AT on a new component.  For example: `npm test pfe-band` would build pfe-band and pfelement and kick off tests against pfe-band only.

**Comment by Homa** [comment]
You need to run:
`npm test -- -p`
in your element folder

**Comment by castastrophe** [comment]
That doesn't appear to work - it's still building every file in the elements folder first.

**Comment by castastrophe** [comment]
The crux of the request is not functionality so much as usability too.  I'm looking for a succinct command that efficiently runs isolated tests.  Similar to the script @mwcz wrote for `npm run dev` which allows you to easily pass in the attributes to watch.

**Comment by mwcz** [comment]
@Homa  The `-p` flag makes the test server persistent; it stays alive after the tests have finished.  What @castastrophe is asking for is the ability to specify that test run only on certain elements.

**Comment by mwcz** [comment]
I think this was resolved by #274.
