### ISSUE TITLE
The versions dropdown is not opening correctly in the documentation site

### ISSUE THREAD

**Issue by anujsingla** [patternfly/patternfly-elements#2717]
## Description of the issue
The versions dropdown is not opening correctly in the documentation site
 Please check the attached screenshot and video for more details.
https://patternflyelements.org/get-started/

![Screenshot 2024-03-22 at 12 35 02 PM](https://github.com/patternfly/patternfly-elements/assets/16379731/cdc56425-c34e-4897-8e22-d64743025ef4)

https://github.com/patternfly/patternfly-elements/assets/16379731/0496c130-2d27-4a45-8156-91e94fd0b2e7

**Comment by bennypowers** [comment]
see https://github.com/patternfly/patternfly-elements/pull/2713

**Comment by anujsingla** [comment]
> see #2713

I think we can close this ticket.

**Comment by bennypowers** [comment]
i set it to close automaticallt when #2713 is approved and merged
