### ISSUE TITLE
Root README out of date

### ISSUE THREAD

**Issue by markcaron** [patternfly/patternfly-elements#278]
There are many references to RH Elements, the RH Elements logo, and the wrong repo to clone in the root README. Also, we should consider replacing the `npm install` command with `npm run bootstrap` since the former produces errors.

**Comment by mwcz** [comment]
What errors does `npm install` cause?  It is the correct command and `npm run bootstrap` should never be required.

**Comment by castastrophe** [comment]
This should be resolved by https://github.com/patternfly/patternfly-elements/pull/279
