### ISSUE TITLE
pf-icon v2 icons not displaying

### ISSUE THREAD

**Issue by rlahoda** [patternfly/patternfly-elements#2792]
## Description of the issue

When using pf-icon v2 the icons are not displaying. Checking the console there are these errors for each icon:
```
[pf-icon] The specifier “@patternfly/icons/fas/cloud.js” was a bare specifier, but was not remapped to anything. Relative module specifiers must start with “./”, “../” or “/”.
```

PFE v2.2.2 is imported by Primer so this is impacting any sites currently using pf-icon on the portal.

### Impacted component(s)

- pf-icon 

### Steps to reproduce

1. Go to https://patternflyelements.org/v2/components/icon/
4. Check console
5. See error

### Expected behavior

The icon component should display icons.

### Screenshots
![image](https://github.com/patternfly/patternfly-elements/assets/18124644/c1fa9218-4abf-4433-a2e5-3e0908e2dc2d)
## Related issues

- #100

**Comment by bennypowers** [comment]
For the portal, you can set an import map, or use `PfIcon.getIconUrl` to point to a url that's more convenient

Keep in mind that this will change in version 4, see #2766
