### ISSUE TITLE
`<pf-select>`: Typeahead Search

### ISSUE THREAD

**Issue by Arathy-s** [patternfly/patternfly-elements#2800]
# Component name: <pf-select>

> pf-select

## Design specification updates

A new typeahead variant for pf-select. 
Refer: https://www.patternfly.org/components/menus/select/#typeahead 

<img width="859" alt="typeahead" src="https://github.com/patternfly/patternfly-elements/assets/49025521/986be572-ca1c-4c85-98cc-d675d210b40a">

## Accessibility updates

Refer: https://www.patternfly.org/components/menus/select/#typeahead

**Comment by bennypowers** [comment]
This is blocking an open issue on CP - trouble shooting dropdown
