### ISSUE TITLE
[tools] after checking out a new branch, automatically clean out any empty element dirs

### ISSUE THREAD

**Issue by mwcz** [patternfly/patternfly-elements#286]
Who else has seen this problem?

You're working on a branch for a new element, say `pfe-foo`.  Then you switch back to master or some other branch, but `elements/pfe-foo/` is still there.  This happens because node_modules dirs are ignored by git, and when you switch branches, git would normally delete `elements/pfe-foo/`.  But because it contains an untracked, ignored dir (node_modules), git plays the nice guy and refuses to delete untracked files.  It's a good thing, but in our workflow it leads to these zombie dirs sticking around after they should be gone.

We can use [Husky](https://github.com/typicode/husky) (already used for setting up git hooks) to set up a post-checkout hook that scans through and cleans up any zombie dirs.  Just brainstorming, it could scan through all packages (themes and elements) and look for any that contain no files other than node_modules, and delete them.

**Comment by castastrophe** [comment]
@mwcz I believe you already did this work - is that correct?  Can this be closed?

**Comment by bennypowers** [comment]
@mwcz closing for now, if this continues to be bothersome let's open a new issue
