### ISSUE TITLE
[docs]: update select docs page with typeahead demo

### ISSUE THREAD

**Issue by bennypowers** [patternfly/patternfly-elements#2861]
https://patternflyelements.org/components/select/
This page should include the typeahead demo, found here:
https://github.com/patternfly/patternfly-elements/blob/main/elements/pf-select/demo/typeahead.html

**Comment by rohit-bharmal** [comment]
Hi @bennypowers ,

I worked on this issue and created MR for it. Please have a look once and let me know.
MR link: (https://github.com/patternfly/patternfly-elements/pull/2868)

**Comment by bennypowers** [comment]
Closed by #2868
