### ISSUE TITLE
Remove cp-theme from repository

### ISSUE THREAD

**Issue by kylebuch8** [patternfly/patternfly-elements#287]
Each theme should be contained in a separate repository and be npm installable. We should have a default PatternFly theme in the repository and all other themes should be moved out of the repo.

**Comment by castastrophe** [comment]
TODO for this would be migrate cp-theme to a gitlab or access repo in the meantime so as not to lose the work and then we can look at bringing this together with rdc theme.

**Comment by starryeyez024** [comment]
FWIW, I started a simple RHDC repo just for our theme vars. It still needs some love but we are going to use this to pull variables into various projects. 
https://gitlab.corp.redhat.com/uxdd/pfe-redhat-theme

**Comment by castastrophe** [comment]
https://github.com/patternfly/patternfly-elements/pull/362
