### ISSUE TITLE
System colors preview page

### ISSUE THREAD

**Issue by castastrophe** [patternfly/patternfly-elements#291]
Build a storybook page that allows developers to preview available system colors, i.e. what is --pfe-theme--color--ui-complement?

![screen shot 2019-01-18 at 2 53 53 pm](https://user-images.githubusercontent.com/1840295/51409839-e7a15180-1b30-11e9-90ea-b076e0eae805.png)

Maybe the pfe-sass component could have a storybook page?

**Comment by starryeyez024** [comment]
@castastrophe do we still need this // can we copy your work form the redhat-theme repo?

**Comment by castastrophe** [comment]
@starryeyez024 I think so but we can update this to display the default colors available in the pfe-sass files.

**Comment by starryeyez024** [comment]
Something perhaps to emulate: 
https://ionicframework.com/docs/theming/color-generator
