### ISSUE TITLE
pfe-avatar: suggest updating PFElement references to this instead

### ISSUE THREAD

**Issue by castastrophe** [patternfly/patternfly-elements#297]
Inside the components' class, when we are extending PFElement root class, I'm suggesting we always use `this.function` instead of `PFElement.function` references.  I think this is a little cleaner and saves us some time if we need to rename the root class for example.

**Comment by kylebuch8** [comment]
@castastrophe Can we close this? I'm not seeing PFElement.whatever in this component anymore.
