### ISSUE TITLE
pfe-accordion throwing JS error

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#323]
With the latest code from master, and after running `npm clean && npm install && npm run start`, when I view https://www.evernote.com/l/AA7-1NZ14q1P3ZlUxz_mOQ09PB0Za-FT5VA I see this error in the console:
`Unchecked runtime.lastError: The message port closed before a response was received.`

![image](https://user-images.githubusercontent.com/456863/52647603-1225c680-2eb3-11e9-845f-dafc77324ac7.png)

**Comment by mwcz** [comment]
Likely a browser extension error, not PFE.  Can you try in incognito mode to verify?

**Comment by mwcz** [comment]
@starryeyez024  I'll close this, but feel free to re-open if you're still seeing the issue.
