### ISSUE TITLE
[fix] pfe-autocomplete | add box-sizing: border-box

### ISSUE THREAD

**Issue by castastrophe** [patternfly/patternfly-elements#325]
Can we update the autocomplete component to use `box-sizing: border-box` on the input field?  The element risks overflows its containers without it.

![screen shot 2019-02-14 at 3 27 27 pm](https://user-images.githubusercontent.com/1840295/52815625-2a414580-306d-11e9-8ef7-ccc21cfae237.png)

![screen shot 2019-02-14 at 3 27 30 pm](https://user-images.githubusercontent.com/1840295/52815629-2dd4cc80-306d-11e9-901e-daef639ec22a.png)

**Comment by bennypowers** [comment]
I believe this is solved:
<img width="751" alt="Screen Shot 2022-02-23 at 17 26 15" src="https://user-images.githubusercontent.com/1466420/155419684-dd730aa6-693e-4c1a-8ef9-fa76ac7d8b97.png">
