### ISSUE TITLE
Band | Major FF issues with the grid named areas

### ISSUE THREAD

**Issue by castastrophe** [patternfly/patternfly-elements#330]
Firefox (latest) is showing some pretty serious jankiness on the band layout:
![screen shot 2019-02-15 at 10 49 32 am](https://user-images.githubusercontent.com/1840295/52867748-96748580-310f-11e9-8411-d8abde92ba33.png)

![screen shot 2019-02-15 at 10 49 40 am](https://user-images.githubusercontent.com/1840295/52867745-92e0fe80-310f-11e9-9ab1-527acab3d8b8.png)

I think this is related to the grid named areas and the sass not using autoprefixer.

**Comment by kylebuch8** [comment]
Major Jank, sir! Reporting for duty, sir!

**Comment by castastrophe** [comment]
Can be fixed by removing grid name areas from custom properties and just encoding them.
