### ISSUE TITLE
pfe-content-set doubles up content in light dom; doesn't respect light dom styles for things in panel

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#345]
![image](https://user-images.githubusercontent.com/456863/53593938-cc7e2480-3b67-11e9-9085-1d61963e9e2a.png)

image.png
![image](https://user-images.githubusercontent.com/456863/53593922-c5efad00-3b67-11e9-9dd1-7d7256251d4f.png)

![image](https://user-images.githubusercontent.com/456863/53593907-bbcdae80-3b67-11e9-9ae2-248500308254.png)

**Comment by kylebuch8** [comment]
@starryeyez024 This should be fixed in #346
