### ISSUE TITLE
pfe-content-set / pfe-accordion: open by default

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#350]
These components should support some attribute which specifies that a panel should be open on page load.

**Comment by chrisdo1** [comment]
We may want to set more than one accordion panels to be open on page load.
Also, we can look at the `selected-index` attribute that we are using on tabs for guidance. Maybe the attribute for accordions ought to be `expanded-index`?

**Comment by starryeyez024** [comment]
Closing this out in favor of the related issue: https://github.com/patternfly/patternfly-elements/issues/859
