### ISSUE TITLE
Cannot run deploy-docs script from Mac

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#369]
```
ktotten@MacBook-Pro-2:~/Sites/patternfly-elements$ npm run deploy-docs


> @patternfly/patternfly-elements@ deploy-docs /Users/ktotten/Sites/patternfly-elements
> bash scripts/deploy-docs.sh

scripts/deploy-docs.sh: line 5: hugo-check.sh: No such file or directory
scripts/deploy-docs.sh: line 7: hugoNoisyCheck: command not found
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @patternfly/patternfly-elements@ deploy-docs: `bash scripts/deploy-docs.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @patternfly/patternfly-elements@ deploy-docs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ktotten/.npm/_logs/2019-03-19T19_11_04_645Z-debug.log
```

**Comment by castastrophe** [comment]
@starryeyez024 I don't think this is Mac-specific.  This is because your branch can't find the hugo-check.sh script that should be in the scripts folder.

**Comment by castastrophe** [comment]
This PR will probably make this easier too https://github.com/patternfly/patternfly-elements/issues/352

**Comment by starryeyez024** [comment]
Hmm, it's in the scripts folder:
![image](https://user-images.githubusercontent.com/456863/55122697-3392e880-50d6-11e9-99d6-4d5b2f083114.png)

I installed hugo-installer & hugo-cli, still no luck @mwcz @castastrophe 
http://pastebin.test.redhat.com/745674

**Comment by kylebuch8** [comment]
@starryeyez024 - Is this still an issue for you? I just deployed an update to the docs without issue from my Mac.
