### ISSUE TITLE
rh-tabs: Styles and CSS variables need to be reviewed and adjusted

### ISSUE THREAD

**Issue by kylebuch8** [patternfly/patternfly-elements#37]
I've started the styles that are specific to the Portal but we need to abstract it out so rh.com and developers can also easily use these.

Check out the [rh-tabs](https://github.com/RHElements/rhelements/tree/rh-tabs) branch.

**Comment by kylebuch8** [comment]
@markcaron - I've updated the rh-tabs branch to have all of my code changes to accommodate the changes we've made to the base Rhelement and gulpfile. We should be ready for style updates.

**Comment by starryeyez024** [comment]
Closing because PR was merged:
https://github.com/patternfly/patternfly-elements/pull/363
