### ISSUE TITLE
CTAs: Primary "on saturated" needs to flip to white?

### ISSUE THREAD

**Issue by markcaron** [patternfly/patternfly-elements#377]
@starryeyez024, we should ensure the primary CTA's "on dark" flips from red with white text to white with dark "black" text (#151515).

**Comment by starryeyez024** [comment]
@markcaron these are the styles from the DSC that will we need to update the CTAs to match; the CTA primary is the same regardless of background:
![image](https://user-images.githubusercontent.com/456863/57201337-c0e31b80-6f65-11e9-9042-6f9e1018bfd9.png)

can you close this issue?

**Comment by castastrophe** [comment]
@starryeyez024 Do we want to revist this on saturated backgrounds though?

**Comment by castastrophe** [comment]
Fixed in https://github.com/patternfly/patternfly-elements/pull/630
