### ISSUE TITLE
[Component] Secondary sticky navigation (new)

### ISSUE THREAD

**Issue by castastrophe** [patternfly/patternfly-elements#384]
Example page that contains sticky nav: https://www.redhat.com/en/events/red-hat-google-cloud-next

Possible code to borrow from: https://gitlab.corp.redhat.com/uxdd/webrh/tree/dev/src/library/patterns/secondary_nav_bar

Interactions: https://gitlab.corp.redhat.com/uxdd/webrh/tree/dev/src/js/smooth-scroll

**Comment by starryeyez024** [comment]
https://docs.google.com/document/d/153LBNhqijdBwxoeibtAAd7Uf3pmvhZUYOssLJGycDto/edit

**Comment by castastrophe** [comment]
Closing this in favor of jump links horizontal
