### ISSUE TITLE
[NEW] Account dropdown + avatar

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-elements#385]
Request from James to include the user's name (to show auth status) & avatar in the universal nav. This design exists in PF4. This component should be included in the Universal Nav design once created. 

[Discovery doc](https://docs.google.com/document/d/1kpEZEi9cCwBIOy3MSZkeXvhu-o10j6nNH7F_qofetys/edit#)

**Comment by castastrophe** [comment]
@wesruv Did you tackle this as an integrated part of navigation 2.0 or is it a distinct component?

**Comment by wesruv** [comment]
Yep!

The design doesn't show the user's name in the bar, but all that info is in the Dropdown. Allie was the designer, so I assume that's what we ended up wanting.

**Comment by coreyvickery** [comment]
@ajacobs21e Keep me posted on any progress if you're picking this up again, I'll need to update our kit with any new designs.

**Comment by castastrophe** [comment]
@wesruv Sorry, I'm not sure which part you were saying yes to:
- integrated part of navigation 2.0
-  is it a distinct component

If it's already been handled in navigation, do we still need this issue or should I close it out?  Is there still a request to build a distinct component or does this meet the requirements?

**Comment by wesruv** [comment]
Oh, sorry. It's a separate component.

It:
* receives decoded parts of the JWT
* wants the login/logout URL set as an attribute
* fetches an avatar from the portal (UX & James Bailey decided to make that the 'one avatar to rule them all' for now)
* builds the content of the account dropdown based on JWT content (user metadata and a few permissions)
* provides the avatar URL for the navigation to build dropdown toggle

Here's a demo of an authenticated `pfe-navigation-account` without `pfe-navigation` wrapping it: https://deploy-preview-963--patternfly-elements.netlify.app/elements/pfe-navigation-account/demo/

**Comment by wesruv** [comment]
It's on the baseline nav demo as well on the far right: https://deploy-preview-963--patternfly-elements.netlify.app/elements/pfe-navigation/demo/

**Comment by bennypowers** [comment]
This issue to be transferred to rhds repo, once created

**Comment by wesruv** [comment]
This is complete, we can close it
