### ISSUE TITLE
[CI] Build a release action

### ISSUE THREAD

**Issue by mwcz** [patternfly/patternfly-elements#386]
Instead of devs running publishes manually, we should have a bot do the publishing.

Here is a nice reference project for implementing this with GitHub Actions: [merge-release](https://github.com/mikeal/merge-release).  In that project, all merges into master are automatically published.  We can debate what strategy to use (my vote is all master merges get published).

cc @starryeyez024

**Comment by mwcz** [comment]
This is much closer to reality now that #399 is done.

**Comment by castastrophe** [comment]
Previous title: Automatically publish to NPM

**Comment by castastrophe** [comment]
Versioning discussion: https://docs.google.com/document/d/1u0f-dqm1RTexhsbflRkU0r-kruBRvJUZEUZMrCzkv1o/edit

**Comment by castastrophe** [comment]
Related issue: https://github.com/patternfly/patternfly-elements/issues/79

**Comment by castastrophe** [comment]
Related: https://github.com/patternfly/patternfly-elements/issues/1453

**Comment by bennypowers** [comment]
This is done in 2.0, and with changesets, yet
