### ISSUE TITLE
Add redhat-theme & redhatfont to dev dependencies

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#389]
## Done Criteria

We need to load the new RH brand CSS variables & fonts into PFE for testing.

[Red Hat Theme](https://gitlab.corp.redhat.com/uxdd/redhat-theme/)
[Red Hat Font](https://github.com/RedHatOfficial/RedHatFont)

## Implementation Details:
1)  Add something like this to package.json
```
    "redhat-font": "git://github.com/RedHatOfficial/RedHatFont.git#1.0.0",
    "redhat-theme": "https://gitlab.corp.redhat.com/uxdd/redhat-theme/-/archive/1.0.0/redhat-theme-1.0.0.tar.gz",
```
(note, the last one doesn't work, needs help)

2) Add something like this to every demo/index.html file:
```html
    <!--link href="../node_modules/redhat-theme/advanced-theme.css" rel="stylesheet"-->
    <!--link href="../node_modules/redhat-font/webfonts/red-hat-font.css" rel="stylesheet-->
```

**Comment by castastrophe** [comment]
I'm not sure this Red Hat specific theme belongs in the upstream project. We can test our theme with new components without making it a dependency of the project and committing it upstream.

**Comment by mwcz** [comment]
I agree.  Nobody outside Red Hat would be able to `npm install` if these dev dependencies are added.

**Comment by mwcz** [comment]
@starryeyez024 Can we close this?
