### ISSUE TITLE
Determine best UX for tabs

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#400]
- should tabs be aware of parent container size?
- if you add the `vertical` attribute and it is a "mobile" size, should it ignore the vertical attribute?
- Need to add side-scrolling to h-tabs when the tabs are wider than the window

---- 
Notes from Chris:
vertical tabs are displaying as vertical on mobile.

This is in pixel 3 chrome. Seeing something similar in iPhone X Safari
https://www.evernote.com/l/AWv5lZk5qapLXI4eMmd3U0M6fVKcqgzMxXE

It's actually in the master branch too. I think it might just be the demo.

EDIT: synced this code to cdoherty sandbox and the vertical tabs appear as horizontal tabs in mobile browsers:
https://www.evernote.com/l/AWs5tx528JFECpLZFVmBvH9gYE2tTenUKlg

**Comment by chrisdo1** [comment]
Browser tested this on a sandbox and it's no longer an issue.
