### ISSUE TITLE
PFE accordion button border color

### ISSUE THREAD

**Issue by chrisdo1** [patternfly/patternfly-elements#413]
Currently the top and bottom borders for accordion buttons is set to #ececec. 
The border color should be #d2d2d2.
On some gray backgrounds it is difficult to see the borders:

<img width="1048" alt="Screen Shot 2019-05-22 at 10 53 15 AM" src="https://user-images.githubusercontent.com/32456107/58185835-cccb1f00-7c81-11e9-9737-19e3dfd02290.png">

**Comment by chrisdo1** [comment]
Created a PR for this: https://github.com/patternfly/patternfly-elements/pull/414

**Comment by starryeyez024** [comment]
https://github.com/patternfly/patternfly-elements/pull/414 has been merged
