### ISSUE TITLE
SPIKE: Performance Testing / Integration recommendations

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#425]
Requested results:
- Baseline testing (lighthouse)
- Blog post of recommended approaches of how to load WCs on your site (SPA vs. CMS, etc)

Resources
 - [btopro video on dynamic imports](https://www.youtube.com/watch?v=7o8T1eymTnQ&t=13m10s)

**Comment by kylebuch8** [comment]
Closing in favor of #409
