### ISSUE TITLE
pfe-variant doesn't get passed into dynamic pfe-tab-panels

### ISSUE THREAD

**Issue by mwcz** [patternfly/patternfly-elements#427]
The quickest way to demo the bug is this recording:

![Peek 2019-06-14 15-00](https://user-images.githubusercontent.com/364615/59531887-315e5000-8eb5-11e9-906a-20ac7a3587df.gif)

To repro:

1. run `npm start`
2. in browser, click pfe-content-set
3. scroll to the bottom
4. click the `Add Header & Panel` button
5. go back and forth between the two tabs

The new tab doesn't get the pfe-variant so the content doesn't have the same vertical spacing as the starting tab.  Maybe a better way to describe the issue is that dynamically added tabs don't get pfe-variant.

I noticed this while looking at PR #406 but I'm not sure if that PR caused the bug, or just revealed it.

**Comment by kylebuch8** [comment]
This has been fixed.
