### ISSUE TITLE
Add the release version in the compiled JavaScript

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#428]
Ideally the compiled JavaScript files for each web component should contain the version release number as a part of the Lerna packaging build steps. 

This is fairly necessary (esp. for redhat.com) since the JS is packaged up by webrh, and shipped through drupal, which then bundles it up via AdvAgg. Even after you dig through aggregated files to look for the pfe-cta.js, you can't tell which version it is, which makes it very difficult to debug or know if something is still a real issue.

**Comment by mwcz** [comment]
This would be really useful for us too!  We could insert the version into the `@license` comment, or into the PFElement class itself, or both.  Here's approximately what they would look like in the minified output.

Just `@license`:

```js
/** @license BSD whatever PatternFly Elements v1.0.0 */
class PFElement { constructor() { /* ... */ }
```

Just PFElement:

```js
/** @license BSD whatever PatternFly Elements */
class PFElement { get version() { return "v1.0.0"; } constructor() { /* ... */ }
```

Both:

```js
/** @license BSD whatever PatternFly Elements v1.0.0 */
class PFElement { get version() { return "v1.0.0"; } constructor() { /* ... */ }
```

Any preference?

**Comment by starryeyez024** [comment]
I guess I'd lean towards both for maximum visibility, but I don't have strong feels about it.

**Comment by kylebuch8** [comment]
I like the last one most.

**Comment by mwcz** [comment]
The PR for this one is ready to go.
