### ISSUE TITLE
variable name mismatch for broadcasted

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#435]
in _functions.scss, we need `--color` added to the function. Currently its
```
@function pfe-radio($cssvar...) {
    @return var(--#{$repo}-broadcasted--#{to-string($cssvar, '--')});
}
```
and files like mixins.scss and card.scss ask for the variables like  ` --pfe-broadcasted--color--text`

Also card.scss should use the new pfe-theme mixin

**Comment by starryeyez024** [comment]
WIP https://github.com/patternfly/patternfly-elements/pull/392/files

**Comment by castastrophe** [comment]
There are broadcasted variables other than color available so I'm not sure I agree with this issue.  If we embed color in the mixin then we can't set text-decoration for example.

**Comment by starryeyez024** [comment]
PR 392 was merged, closing this out
