### ISSUE TITLE
Single accordion, box style

### ISSUE THREAD

**Issue by chrisdo1** [patternfly/patternfly-elements#452]
from Dan Caryll: "we talked about if there was just one item, it would have a border on the left and right to feel like a box instead of an accordion"

An example of this is the container for Customer Portal results on the search page.

![image](https://user-images.githubusercontent.com/32456107/60355878-7dbd8b80-999d-11e9-9e39-b33650a4a2fd.png)

**Comment by castastrophe** [comment]
@chrisdo1 fixed this!
