### ISSUE TITLE
Request: Add Spacers

### ISSUE THREAD

**Issue by mindreeper2420** [patternfly/patternfly-elements#456]
I'd like to request that Spacers be integrated into PatternFly Elements, for use in margin and padding attributes. Preferably, they would resemble the system found in https://github.com/patternfly/patternfly-next/tree/master/src/patternfly/utilities/Spacing, in order to keep continuity between PatternFly projects.

Example: `pfe-u-mr-md` = `margin-right: 16px`, where `md / 16px` is the default font size.

This request is coming from the proposed integration of PatternFly Elements into the RHDP site. Currently, custom spacers are needed as none are provided by default.

**Comment by castastrophe** [comment]
Hi @mindreeper2420!  Thanks for raising this request!  PatternFly Elements does not use a class-based system, instead we allow for hooks into the margins and padding using CSS variables and the customization of a theme.  For example, if you want to ensure that your margins or padding are 16px across all components, you would just need to add:

```
:root {
    --pfe-theme--container-spacer: 16px;
    --pfe-theme--container-padding: 16px;
}
```

This would define your standards for all PatternFly Elements.  If you wanted to customize the margin or padding on just a particular component on your page, you can also do this (`--Padding` is the external padding on the card component whereas `--spacing` represents the internal spacing between regions of the card):

```
pfe-card {
    --pfe-card--Padding: 20px;
    --pfe-card--spacing: 10px;
}
```

Happy to chat more about this approach in future.  We chose BEM variable naming specifically to align with PatternFly 4 and are working on bringing our theme concepts closer as we build more widgets!

**Comment by castastrophe** [comment]
I'm going to close this as a wontfix only because we're using a different approach but I believe we have solved for your needs.  If we have not, please don't hesitate to reach out to me and I will reopen this right away!
