### ISSUE TITLE
Add a --skip-build flag for npm install

### ISSUE THREAD

**Issue by castastrophe** [patternfly/patternfly-elements#461]
At the end of `npm install`, it runs a full build.  This is great for a lot of use-cases but sometimes I just need to resolve a conflict in the package-lock.json quickly and the build is only going to get longer.  Could we consider adding a `--skip-build` flag of some kind to the install task?

**Comment by mwcz** [comment]
Yeah, I've had the same annoyance regarding regenerating package-lock.  I'm cool with this suggestion.  I'd also be cool with removing the automatic build entirely.  Running `npm install` and then `npm run build` when necessary would be just fine.
