### ISSUE TITLE
[fix] pfe-cta stretch

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#478]
current flexbox styles stretch CTAs (or other content) horizontally across the card

![pfe-card-flex-issues](https://user-images.githubusercontent.com/456863/62397514-208c9b00-b544-11e9-8943-28f4eb0bf394.gif)

**Comment by kylebuch8** [comment]
@starryeyez024 Is this not intended?

**Comment by starryeyez024** [comment]
@kylebuch8 nope, CTA's should just be whatever width the text is, plus padding.

**Comment by castastrophe** [comment]
https://github.com/patternfly/patternfly-elements/pull/854/files?file-filters%5B%5D=.scss#diff-235f07a9f47613ded24fdf03b62922561f87b3d82b78bcc90f1384ee5d3b020c
