### ISSUE TITLE
Official pfe-datetime status

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#491]
- [x] schema
- theme support n/a
- [x] framework support
    - [x] Angular
    - [x] React
    - [x] Vue
- [x] no major outstanding bugs

**Comment by castastrophe** [comment]
Would be nice if it hooked into variables for font-size and text color via broadcast with fallback to the theme.  Maybe we uncheck theme here?

**Comment by starryeyez024** [comment]
@kylebuch8  to add schema

**Comment by starryeyez024** [comment]
@castastrophe I think we talked about this verbally but adding notes here for posterity, the datetime component is inline, so presumably the block-level element is responsible for providing styles:
```
<p>I remember the day clearly, it was<pfe-datetime datetime="January 9, 2019" type="local" day="numeric" month="long" year="numeric" locale="en-US">January 9, 2019</pfe-datetime> when I committed my first line of code.<p>
```
