### ISSUE TITLE
Official pfe-icon-panel status

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#493]
- [x] schema
  - https://github.com/patternfly/patternfly-elements/pull/572
- [x] theme support
- [x] framework support
    - [x] Angular
    - [x] React
    - [x] Vue
- [x] no major outstanding bugs
  - https://github.com/patternfly/patternfly-elements/issues/442
  - circles are not circular

**Comment by mwcz** [comment]
I don't think I'm the right person for this.  I updated pfe-icon-panel to work with the new pfe-icon, but I don't own pfe-icon-panel.  I never even understood what the purpose of the component is.

**Comment by eyevana** [comment]
Circular bug addressed in PR #578.
