### ISSUE TITLE
Official pfe-band status

### ISSUE THREAD

**Issue by kylebuch8** [patternfly/patternfly-elements#497]
- [x] schema
- [x] theme support
- [ ] framework support
    - Currently not working in any framework: https://github.com/patternfly/patternfly-elements/issues/587
    - [ ] Angular
    - [ ] React
    - [ ] Vue
- [ ] no major outstanding bugs
    - [T5 FED story for band layout issue](https://rally1.rallydev.com/#/270861059696d/detail/userstory/305092917904)
    - [Needs bug fixed for FF layout issues (Issue 330)](https://github.com/patternfly/patternfly-elements/issues/330)

**Comment by starryeyez024** [comment]
This will be merged this sprint
