### ISSUE TITLE
pfe-collapse should not be in storybook

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#513]
Pfe-collapse should not appear in storybook because it's not intended to be used on it's own, right? And there is no preview. 

https://patternfly.github.io/patternfly-elements/demo/?knob-Theme=light&knob-Count=5&selectedKind=Collapse&selectedStory=pfe-collapse&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybooks%2Fstorybook-addon-knobs

**Comment by kylebuch8** [comment]
@starryeyez024 - There is a preview. Just click on "Toggle Control".

I think there's merit in pfe-collapse being in the Storybook so developers see how it works.

**Comment by starryeyez024** [comment]
Ohhh, that was super not-obvious to me that that text was clickable. How would you feel about changing the H3 to `<button type="button">Toggle Control</button>` @kylebuch8
