### ISSUE TITLE
pfe-accordion | fix header borders on expanded accordion on dark background

### ISSUE THREAD

**Issue by chrisdo1** [patternfly/patternfly-elements#514]
Accordion headers should have a `3px solid #ffffff` border-left and a `1px solid #ffffff` border-right when expanded on dark backgrounds. 

![Screen Shot 2019-08-26 at 2 07 12 PM](https://user-images.githubusercontent.com/32456107/63714096-05ddd700-c80f-11e9-8d3e-5d9a7d87e9bd.png)

**Comment by castastrophe** [comment]
@chrisdo1 I don't see this anymore - do you still see this issue?
