### ISSUE TITLE
Padding / Line-height on CTAs seems a little large

### ISSUE THREAD

**Issue by markcaron** [patternfly/patternfly-elements#542]
With the padding being set to `1rem` on the top and bottom, and the line-height set to `inherit` we have little control over the exact sizing of the "button" shape. It could be `1.5rem` or `1.6rem` or anything—resulting in a tall, wonky CTA.

I believe adding `line-height: 1rem;` to `:host([pfe-priority]) { ... }` on line 96 of `pfe-cta.scss` will make the sizing more in line with DSC specs.

**Comment by castastrophe** [comment]
@markcaron CTA has been set according to the current design system mocks - can I close this now?
