### ISSUE TITLE
Add `files` to all package.jsons

### ISSUE THREAD

**Issue by mwcz** [patternfly/patternfly-elements#546]
From @castastrophe, we should add a `files` property to every component's package.json in order to white-list the files to be published to npm.  We currently have files that are being published but are not ever meant to be consumed independently.  See [pfe-icon-set.js in prerelease.25](https://github.com/patternfly/patternfly-elements/blob/v1.0.0-prerelease.25/elements/pfe-icon/pfe-icon-set.js).  These files typically live in `src` and are imported by the "main" component module.  Rollup embeds them in the bundle, but they are also copied into the component's root dir, and come along for the ride when publishing.  It would be good to clean them up.

The generator could lay down a good default using the component's tag name.  An example for `pfe-navigation`:
```json
"files": [
    "pfe-navigation.*js{.map}"
],
```

Components with a need to include files that don't match that pattern (PFElement's `pfelement.css` for example) can have those files added to the `files` array.

**Comment by castastrophe** [comment]
I think we've got this covered now
