### ISSUE TITLE
pfe-modal | On dark band picks up dark broadcast values

### ISSUE THREAD

**Issue by chrisdo1** [patternfly/patternfly-elements#547]
Update the broadcast variables for text and links in pfe-modal.
![Screen Shot 2019-09-17 at 11 41 54 AM](https://user-images.githubusercontent.com/32456107/65057239-4f1dd400-d940-11e9-9f82-10f1fc6e8205.png)

**Comment by castastrophe** [comment]
Where the background color is being set on Modal, need to also update the value of the broadcast variables.

**Comment by castastrophe** [comment]
I believe this has been resolved: https://patternflyelements.com/elements/pfe-modal/demo/
