### ISSUE TITLE
pfe-modal initial page load (slow 3g)

### ISSUE THREAD

**Issue by bdone** [patternfly/patternfly-elements#548]
1. for slower page loads, the initial hidden modal content flashes on screen

![pfe-elements-pfe-modal-hidden](https://user-images.githubusercontent.com/302272/65066320-2999c600-d952-11e9-8919-512d74f3065e.gif)

**Comment by castastrophe** [comment]
I don't think this is specific to Modal - this is the flash of unstyled content that the reveal tool is supposed to help with cc @mwcz

**Comment by castastrophe** [comment]
An issue has been opened to better document the reveal tool which is what addresses this issue: https://github.com/patternfly/patternfly-elements/issues/549 . Closing out this issue unless there are objections!
