### ISSUE TITLE
<pfe-markdown> Create markdown component

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#571]
(from Luke) 

**Wishlist:**
 - Accepts Markdown, maybe shows editor
 - Short codes support of web components, for static site generators like Jekyll, Hugo, ASCII doc, etc. 

Look into LRN web component(s)
- https://github.com/elmsln/lrnwebcomponents/tree/master/elements/md-block
- https://github.com/elmsln/lrnwebcomponents/tree/master/elements

-

**Comment by kylebuch8** [comment]
@starryeyez024 Does our pfe-markdown component not satisfy this?

**Comment by castastrophe** [comment]
I think perhaps it does; I'll close this out for now and we can open a new/more-specific issue if needed.
