### ISSUE TITLE
Establish standards for custom events

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#582]
- [ ] Add base class for custom events
     - (Once we have adobe successfully seeing custom events, we can do more tests with moving content into the shadow DOM)
- [ ] Add documentation around naming and how-to for custom events within components

**Comment by starryeyez024** [comment]
@kylebuch8 please add details if you can, thanks!

**Comment by castastrophe** [comment]
I think bullet point #1 is addressed now

**Comment by castastrophe** [comment]
Addressed documentation here: https://github.com/patternfly/patternfly-elements/pull/907
