### ISSUE TITLE
Pfe-accordion animations on desktop and iOS Safari

### ISSUE THREAD

**Issue by Djfaucette** [patternfly/patternfly-elements#597]
Pfe-accordion animations do not complete in desktop and iOS safari.

Expected: the arrow should rotate 90º on state change

Actual: (iOS) opening the panel works correctly, but on close the arrow is rotated incorrectly until changing the focus. Screenshot:
<img width="423" alt="Screen Shot 2019-10-30 at 11 28 51 AM" src="https://user-images.githubusercontent.com/9581250/67873286-9a173380-fb09-11e9-9bfe-eb396a3ffd9c.png">

Actual (desktop): The close animation does not complete if the mouse is hovering over the accordion's open button. Screenshot: 
![Screen Shot 2019-10-30 at 11 38 46 AM](https://user-images.githubusercontent.com/9581250/67873467-e1052900-fb09-11e9-8518-e8b4163e626e.png)

**Comment by castastrophe** [comment]
Can you confirm if this is still an issue?

**Comment by Djfaucette** [comment]
Yeah, looks like it's resolved! Not seeing the issue anymore in IOS and Safari 13. Closing.
