### ISSUE TITLE
pfe-toast: Apply pfe-sass animation properties

### ISSUE THREAD

**Issue by eyevana** [patternfly/patternfly-elements#618]
We may need to create a new animation-timing property for pfe-toast.

```suggestion
  transition: right #{pfe-var(animation-speed)} #{pfe-var(animation-timing)};
```

_Originally posted by @castastrophe in https://github.com/patternfly/patternfly-elements/diffs_

**Comment by bennypowers** [comment]
I believe this is solved:
https://github.com/patternfly/patternfly-elements/blob/58b1ae602790a4532c9dc485c2f8bb36f81a1d44/elements/pfe-toast/pfe-toast.scss#L52

If I'm wrong about that, please open a new issue. Thanks
