### ISSUE TITLE
pfe-card: Support full-width (horizontal card)

### ISSUE THREAD

**Issue by dcaryll** [patternfly/patternfly-elements#626]
@samlinville is working on design additions to our card layout to support side by side layouts. We see this as an extension of the card component/layout. 

DSC to provide new styles and requirements.

**Comment by castastrophe** [comment]
@dcaryll @coreyvickery This has been open for a while - is this still a priority?

**Comment by coreyvickery** [comment]
@castastrophe I think we already support full-width cards (see the bottom of [this page](https://www.redhat.com/en/technologies/linux-platforms/enterprise-linux) for examples). If we need to revisit, I can create another issue and add specs.
