### ISSUE TITLE
pfe-card: Add bordered option as a default option

### ISSUE THREAD

**Issue by kylebuch8** [patternfly/patternfly-elements#629]
We use bordered cards a lot and I know we can update the CSS variables to provide a border in a theme, but I think enough people would expect to find a border on a card or at least have an option to add a border without having to update theme variables.

**Comment by ajacobs21e** [comment]
RHDDS spec https://xd.adobe.com/view/d20a1c17-375c-4c7f-6827-5fe2f8c2d92f-a43b/screen/930cbfcc-d26a-49cc-85e9-30e360dde698/Card-bar

**Comment by castastrophe** [comment]
👍Adding a `pfe-border` setting should be an easy update.

**Comment by eyevana** [comment]
Happy New Year, @castastrophe! :) I wanted to start working on this issue, but to clarify requirements...if the pfe-border attribute is present, then we apply the default border color? I think `#eee` is being used in the demo file.

**Comment by ajacobs21e** [comment]
hey @eyevana $pf-global--BorderColor-100 = $pf-color-black-300 = #d2d2d2

**Comment by castastrophe** [comment]
Do you think you could work from or add to this PR? https://github.com/patternfly/patternfly-elements/pull/592

**Comment by eyevana** [comment]
For sure. I'll add to #592 then. Thx!
