### ISSUE TITLE
Console error with pfe-number

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#632]
![image](https://user-images.githubusercontent.com/456863/69548745-e79a8b00-0f65-11ea-8885-1801c257ce2f.png)

This is just a heads up to see if anyone else is getting this error; this has not been fully verified.

**Comment by mwcz** [comment]
@starryeyez024 Can you provide some context, like where are you seeing the error?  Demo page, storybook, on a live page, etc.  I'll try to reproduce but that info would help.

**Comment by mwcz** [comment]
I checked the demo page and storybook and don't see the error.  However, in storybook I don't see any formatted numbers.  The demo page works fine.

**Comment by starryeyez024** [comment]
One of our devs saw it on a sandbox but now I cant reproduce it. Thanks for verifying, I'll close this out.

**Comment by mwcz** [comment]
Cool, I'll open a new issue for pfe-number not working in storybook.
