### ISSUE TITLE
pfe-number doesn't work in storybook

### ISSUE THREAD

**Issue by mwcz** [patternfly/patternfly-elements#633]
A followup to #632.

pfe-number displays nothing in storybook.  No formatted numbers, just blank.  No console errors either.

Screenshot:
![Screenshot from 2019-11-25 11-40-00](https://user-images.githubusercontent.com/364615/69560420-b5932400-0f79-11ea-8c23-2e060ad628b7.png)

Demo page works fine.

**Comment by Anto00x** [comment]
Hi,
any news on fixing this issue? This is still the case in the [storybook page](https://patternfly.github.io/patternfly-elements/demo/?path=/story/number--pfe-number).
There is no error in console and no number is present in the html of the component, either inside or outside the shadow DOM.

**Comment by kylebuch8** [comment]
@Anto00x - Thanks for following-up on this. I've got a PR created that will fix the issue.

https://github.com/patternfly/patternfly-elements/pull/922

**Comment by kylebuch8** [comment]
@Anto00x - This is now fixed.
https://patternfly.github.io/patternfly-elements/demo/?path=/story/number--pfe-number
