### ISSUE TITLE
MIME type issue with pfelement CSS file

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#638]
![image](https://user-images.githubusercontent.com/456863/69639575-bfc12b00-102a-11ea-8761-a8c1c55cd549.png)

This error occurs even when I add the type:

```
    <link href="pfelement/pfelement.min.css" rel="stylesheet" type="text/css" >
```

**Comment by kylebuch8** [comment]
@starryeyez024 Is it because this is pointing at a bad URL? Shouldn't it be `/pfelement/dist/pfelement.min.css`?
