### ISSUE TITLE
Hover color on tab headers

### ISSUE THREAD

**Issue by LyndseyR** [patternfly/patternfly-elements#639]
When hovering over earth variant for tabs the link goes white 
<img width="1147" alt="Screenshot 2019-11-26 at 17 57 19" src="https://user-images.githubusercontent.com/20518754/69655169-47805700-1076-11ea-9342-22b222095ad6.png">

And normal state of "wind" variant is a little too late
<img width="894" alt="Screenshot_2019-11-26_at_17_58_42" src="https://user-images.githubusercontent.com/20518754/69655315-9201d380-1076-11ea-97ba-fa29fdc17806.png">

**Comment by starryeyez024** [comment]
This has been fixed: https://patternflyelements.com/elements/pfe-tabs/demo/
(second tab is in hover state)
![image](https://user-images.githubusercontent.com/456863/108891267-833d0000-75dc-11eb-91bb-4513622c2900.png)
![image](https://user-images.githubusercontent.com/456863/108891310-9059ef00-75dc-11eb-8a01-259186f0e14f.png)
