### ISSUE TITLE
pfe-tab colors on dark context needs color updates

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#640]
![image](https://user-images.githubusercontent.com/456863/69664435-5f47e300-1056-11ea-9a10-481f6217afff.png)

**Comment by coreyvickery** [comment]
@starryeyez024 https://xd.adobe.com/view/d20a1c17-375c-4c7f-6827-5fe2f8c2d92f-a43b/screen/79e758b8-36f9-49f4-afa2-a1ba46063454/Tabs-secondary-vertical-dark-

Active tab indicator bar: #e00

Active tab text: #fff
Active tab BG: #151515 is default or use whatever the BG color behind it is, if possible

#fff text on #151515 BG ratio: 18.26:1

Inactive tab text: #ccc
Inactive tab BG: #333

#ccc text on #333 BG ratio: 7.86:1

Lines/rules: #6a6e73
- No left, bottom, and right borders

Should we also determine a minimum 'darkest' BG color that the dark tab style can be used?

**Comment by starryeyez024** [comment]
pasting quick screenshots here from the design kit each variant.

Wind:
![image](https://user-images.githubusercontent.com/456863/69672266-be612400-1065-11ea-8cc5-50654e5de4cb.png)

Earth:
![image](https://user-images.githubusercontent.com/456863/69672285-c7ea8c00-1065-11ea-98e9-ecff4fb5200a.png)

@coreyvickery the themes are all dynamic.. that sort of warrants a larger discussion which would apply to all components that would receive the dark theme treatment. Currently only two colors (darker and darkest) invoke the `--theme:dark`

```
  --pfe-theme--color--surface--lightest: #ffffff;
  --pfe-theme--color--surface--lightest--theme: light;
  --pfe-theme--color--surface--lighter: #f0f0f0;
  --pfe-theme--color--surface--lighter--theme: light;
  --pfe-theme--color--surface--base: #dddddd;
  --pfe-theme--color--surface--base--theme: light;
  --pfe-theme--color--surface--darker: #444444;
  --pfe-theme--color--surface--darker--theme: dark;
  --pfe-theme--color--surface--darkest: #1a1a1a;
  --pfe-theme--color--surface--darkest--theme: dark;
  --pfe-theme--color--surface--complement: #10565c;
  --pfe-theme--color--surface--complement--theme: saturated;
  --pfe-theme--color--surface--accent: #ee0000;
  --pfe-theme--color--surface--accent--theme: saturated;
```

**Comment by castastrophe** [comment]
Since the theme is applied with JS, we could incorporate color interpolation in future to set standards like this about when to invite certain themes.

**Comment by ajacobs21e** [comment]
https://github.com/patternfly/patternfly-elements/issues/672 This has updates to the colors to align with PF4

**Comment by coreyvickery** [comment]
Correct colors and styling here.

https://github.com/patternfly/patternfly-elements/issues/814
