### ISSUE TITLE
Edge does not accurately detect theme var; adds incorrect `on` attribute to children

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#652]
Can see issue here in the dark band, the CTA has an on="dark" attribute in Edge only:
http://localhost:8000/elements/pfe-modal/demo/

![image](https://user-images.githubusercontent.com/456863/70258662-96a34780-175a-11ea-9695-827744dee6db.png)

![image](https://user-images.githubusercontent.com/456863/70258631-8b501c00-175a-11ea-95f6-40917da7bcfc.png)

**Comment by bennypowers** [comment]
This shouldn't be relevant anymore with edgium. If I'm mistaken about that, please reopen
