### ISSUE TITLE
POLYFILLS: find alternatives

### ISSUE THREAD

**Issue by mwcz** [patternfly/patternfly-elements#66]
The Array.find polyfill is included at the top of a few elements, so it gets re-run for each of those elements that gets imported.  I also am uncomfortable with having a polyfill installed invisibly.  If it's included into a project that already has a polyfill for Array.find, it could prevent that project's polyfill from being installed, potentially leading to a very difficult to isolate bug.

A partial import of lodash's find function would be a great solution, ex: `import { find } from "lodash"`.  It would solve the problem completely.  But, we can't, because we can only import third-party dependencies that have global references.  Maybe there is some way to make it work.

**Comment by castastrophe** [comment]
I made this subject line a little more general because I think polyfills are an issue we need to solve globally

**Comment by castastrophe** [comment]
Closing in favor of this approach: https://github.com/patternfly/patternfly-elements/issues/1363
