### ISSUE TITLE
pfe-tab design updates

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-elements#672]
The design system collaborative updated the design of vertical tabs to align with PatternFly4.

Primary tabs

- Spacing: .5em 2em .5em 1em
- Leading / trailing border line: 1.5em
- Highlight height: 2em, centered (extending 4px above and below text)

Secondary tabs (box)

- Spacing: .5em 2em .5em 1em
- Leading / trailing border line: 2em

Colors
These also apply to horizontal tabs, we are still working on aligning the rest of the horizontal tab design with PF4

- Secondary color - needs to change to #6A6E73
    - Border color, dark theme
    - Inactive text, light theme
- Inactive text, dark theme: #D2D2D2 (Color--light-300)
- Inactive tab background, light theme: #F0F0F0 (BackgroundColor--200)
- Inactive tab background, dark theme: #3C3F42 (BackgroundColor--dark-200)

![Tab proposal vertical](https://user-images.githubusercontent.com/6415742/71929789-617a8280-3168-11ea-9b1d-ae6b78774efd.png)

https://github.com/patternfly/patternfly-unified-design-kit/issues/77

**Comment by starryeyez024** [comment]
https://github.com/patternfly/patternfly-elements/issues/672

**Comment by coreyvickery** [comment]
Opening a new issue for all changes to pfe-tabs. Closing.
