### ISSUE TITLE
pfe-cta arrow wraps to a new line by itself

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#679]
![image](https://user-images.githubusercontent.com/456863/72622577-7fd34180-3911-11ea-8063-598be3191f3e.png)

**Comment by starryeyez024** [comment]
https://github.com/patternfly/patternfly-elements/pull/680/files

**Comment by castastrophe** [comment]
Mostly fixed in https://github.com/patternfly/patternfly-elements/pull/630

**Comment by bennypowers** [comment]
Is this still relevant? https://patternflyelements.org/components/cta/demo/

**Comment by methomps** [comment]
Closing this issue out. Will fix in RHDS: https://github.com/RedHat-UX/red-hat-design-system/issues/333
