### ISSUE TITLE
Adjustments to gray background and secondary text color for accessibility

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-elements#691]
Relevant PF design story with background info and explanation: https://github.com/patternfly/patternfly-next/issues/2424

tl;dr
Update background color to #F0F0F0 (was #EDEDED) 
Update secondary color to #6A6E73 (was #747679)

**Comment by kylebuch8** [comment]
@ajacobs21e We'll tackle this in https://github.com/patternfly/patternfly-elements/issues/672.

Closing this one.
