### ISSUE TITLE
pfe-cta spacing & font-weight tweaks

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-elements#692]
Because of the way XD handles text line height, design mocks may inadvertently have wrong sizing for buttons and CTAs. 

It should be:

- Red Hat Text Regular (instead of medium) with 24px line height
- Buttons will use 6px top/bottom spacers (PF form spacers) for a height of 36px (6+24+6)
- Form fields & other components used with a button will match button height (36px)
- CTAs will use 16px top/bottom spacers for a height of 56px (16 + 24 + 16)

**Comment by starryeyez024** [comment]
Implementation Note: 

The [weight](https://docs.google.com/spreadsheets/d/1C0JFvlo9wKOeF1iACvLvLarTrJCfjdrffx5vI8N-gQE/edit#gid=0) used will invoke the different font files within the RedHatText font family:
```
400 |  RedHatText-Regular
700 |  RedHatDisplay-Bold | RedHatText-Medium
```

**Comment by starryeyez024** [comment]
Notes from prioritization meeting, Corey to confirm: 

## `<pfe-cta>` updates
- CTAs will use 16px top/bottom spacers for a height of 56px (16 + 24 + 16)
- Font is ok as-is

## `<button>` updates
- redhat.com team will make any button style changes in DyFo  
- more discussion needed about bringing a button into PFE

**Comment by coreyvickery** [comment]
@starryeyez024 @kylebuch8 I just decided to add all of the styles and spacing guidelines below. Please let me know if I missed anything.

---

# Themes

> There are two CTA themes available to choose from.

### Options (light theme)

<img width="1196" alt="Screen Shot 2020-04-15 at 4 55 05 PM" src="https://user-images.githubusercontent.com/45767595/79387949-85551d80-7f3a-11ea-9a22-2d3fa9b12e32.png">

### Styles (light theme)

Style | Default | Focus | Hover | Active
------------ | ------------ | ------------- | ------------- | -------------
***Primary*** | **Text label**<br />RH Display, Bold<br />16pt / 24 (1.5)<br />#fff<br /><br />**Fill**<br />Corners: 3px<br />#e00 | **Focus border**<br />Corners: 2px<br />Width: 1px<br />#fff | **Fill**<br />#d40000 | Same Fill as Hover<br />Same Border as Focus
***Primary, video*** | **Icon**<br />#fff | Same as Primary | Same as Primary | Same as Primary
***Primary, disabled*** | **Label**<br />RH Display, Bold<br />16pt / 24 (1.5)<br />#6a6e73<br /><br />**Fill**<br />Corners: 3px<br />#d2d2d2 | Same as Default | Same as Default | Same as Default
***Secondary*** | **Text label**<br />RH Display, Bold<br />16pt / 24 (1.5)<br />#151515<br /><br />**Border**<br />Corners: 3px<br />Width: 1px<br />#151515 | **Focus border**<br />Corners: 2px<br />Width: 1px<br />#151515 | **Label**<br />#fff<br /><br />**Fill**<br />#151515 | Same Fill as Hover<br /><br />**Active border**<br />Corners: 2px<br />Width: 1px<br />#fff
***Secondary, blue*** | **Text label**<br />RH Display, Bold<br />16pt / 24 (1.5)<br />#06c<br /><br />**Border**<br />Corners: 3px<br />Width: 1px<br />#06c | **Focus border**<br />Corners: 2px<br />Width: 1px<br />#06c | **Label**<br />#fff<br /><br />**Fill**<br />#06c | Same Fill as Hover<br /><br />**Active border**<br />Corners: 2px<br />Width: 1px<br />#fff
***Brick*** | **Text label**<br />RH Text, Regular<br />16pt / 24 (1.5)<br />#06c<br /><br />**Border**<br />Corners: 3px<br />Width: 1px<br />#d2d2d2 | **Focus border**<br />Corners: 2px<br />Width: 1px<br />#d2d2d2 | **Label**<br />#004080<br /><br />**Fill**<br />#f5f5f5 | Same Label as Hover<br />Same Fill as Hover<br />Same Border as Focus
***Brick with icon*** | **Icon**<br />#d2d2d2 | Same as Brick | Same as Brick | Same as Brick
***Default, blue*** | **Label**<br />RH Display, Bold<br />18pt / 27 (1.5)<br />#06c<br /><br />**Icon**<br />#06c | **Focus background**<br />Corners: 3px<br />Opacity: 10%<br />#06c | **Label**<br />#004080<br /><br />**Icon**<br />#004080 | Same Label as Hover<br />Same Icon as Hover<br />Same Background as Focus

### Options (dark theme)

<img width="1117" alt="Screen Shot 2020-04-15 at 4 58 45 PM" src="https://user-images.githubusercontent.com/45767595/79387965-8dad5880-7f3a-11ea-93d1-4b4f71679d37.png">

### Styles (dark theme)

Style | Default | Focus | Hover | Active
------------ | ------------ | ------------- | ------------- | -------------
***Primary*** | **Text label**<br />RH Display, Bold<br />16pt / 24 (1.5)<br />#fff<br /><br />**Fill**<br />Corners: 3px<br />#e00 | **Focus border**<br />Corners: 2px<br />Width: 1px<br />#fff | **Fill**<br />#d40000 | Same Fill as Hover<br />Same Border as Focus
***Primary, video*** | **Icon**<br />#fff | Same as Primary | Same as Primary | Same as Primary
***Primary, white*** | **Text label**<br />RH Display, Bold<br />16pt / 24 (1.5)<br />#151515<br /><br />**Fill**<br />Corners: 3px<br />#fff | **Focus border**<br />Corners: 2px<br />Width: 1px<br />#151515 | **Fill**<br />#f0f0f0 | Same Fill as Hover<br />Same Border as Focus
***Primary, disabled*** | **Label**<br />RH Display, Bold<br />16pt / 24 (1.5)<br />#6a6e73<br /><br />**Fill**<br />Corners: 3px<br />#d2d2d2 | Same as Default | Same as Default | Same as Default
***Secondary*** | **Text label**<br />RH Display, Bold<br />16pt / 24 (1.5)<br />#fff<br /><br />**Border**<br />Corners: 3px<br />Width: 1px<br />#fff | **Focus border**<br />Corners: 2px<br />Width: 1px<br />#fff | **Label**<br />#151515<br /><br />**Fill**<br />#fff | Same Fill as Hover<br /><br />**Active border**<br />Corners: 2px<br />Width: 1px<br />#151515
***Brick*** | **Text label**<br />RH Text, Regular<br />16pt / 24 (1.5)<br />#2b9af3<br /><br />**Border**<br />Corners: 3px<br />Width: 1px<br />#6a6e73 | **Focus border**<br />Corners: 2px<br />Width: 1px<br />#6a6e73 | **Label**<br />#73bcf7<br /><br />**Fill**<br />#3c3f42 | Same Label as Hover<br />Same Fill as Hover<br />Same Border as Focus
***Brick with icon*** | **Icon**<br />#6a6e73 | Same as Brick | Same as Brick | Same as Brick
***Default, light blue*** | **Label**<br />RH Display, Bold<br />18pt / 27 (1.5)<br />#2b9af3<br /><br />**Icon**<br />#2b9af3 | **Focus background**<br />Corners: 3px<br />Opacity: 15%<br />#73bcf7 | **Label**<br />#73bcf7<br /><br />**Icon**<br />#73bcf7 | Same Label as Hover<br />Same Icon as Hover<br />Same Background as Focus
***Default, white*** | **Label**<br />RH Display, Bold<br />18pt / 27 (1.5)<br />#fff<br /><br />**Icon**<br />#fff | **Focus background**<br />Corners: 3px<br />Opacity: 15%<br />#fff | **Label**<br />#f0f0f0<br /><br />**Icon**<br />#f0f0f0 | Same Label as Hover<br />Same Icon as Hover<br />Same Background as Focus

---

# Spacing and heights

### Light theme

<img width="1040" alt="Screen Shot 2020-04-15 at 11 41 13 PM" src="https://user-images.githubusercontent.com/45767595/79412695-1a283d00-7f74-11ea-9a08-9aaae0ce8071.png">

**Spacing legend**
https://www.patternfly.org/v4/design-guidelines/styles/spacers

### Dark theme

<img width="1040" alt="Screen Shot 2020-04-15 at 11 46 22 PM" src="https://user-images.githubusercontent.com/45767595/79412709-22807800-7f74-11ea-9ab8-7c4a245d11a7.png">

**Spacing legend**
https://www.patternfly.org/v4/design-guidelines/styles/spacers

**Comment by coreyvickery** [comment]
@starryeyez024 @castastrophe Small changes made to reflect that we are deprecating the Disabled style.

**Comment by coreyvickery** [comment]
@starryeyez024 Updated some info and screenshots above to reflect new dark theme link color and hover.

**Comment by bennypowers** [comment]
are these changes still relevant?

**Comment by coreyvickery** [comment]
@bennypowers I think we can close this one for now and I'll open someone else if necessary.
