### ISSUE TITLE
pfe-accordion disclosure attribute is not surfaced in storybook as a knob

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#702]
![image](https://user-images.githubusercontent.com/456863/73313311-e3564c80-41f8-11ea-87ff-e03df14bf847.png)

**Comment by castastrophe** [comment]
It is only surfaced when there is just 1 item in the accordion set: https://patternflyelements.com/storybook/?path=/story/accordion--pfe-accordion&knob-Context=lightest&knob-Count=1&knob-Opt-out%20of%20disclosure=true
