### ISSUE TITLE
pfe-navigation: full width nav

### ISSUE THREAD

**Issue by kylebuch8** [patternfly/patternfly-elements#714]
We have some apps that need to have a full width nav. Can we add an attribute that would allow the nav to stretch edge to edge?

**Comment by samlinville** [comment]
Padding on either side when width>1200 should be 64px

**Comment by kylebuch8** [comment]
1200 and above: 64px
1200<x>992 : 32px
Below 992: 16px

@samlinville Correct?

**Comment by samlinville** [comment]
@kylebuch8  Based on looking at what's currently implemented on RH.com, it's more like

1200 and above: 64px
1200-768: 32px
768 and below: 16px

**Comment by starryeyez024** [comment]
Adding notes:  we have two vars, which could maybe benefit from a naming / usage adjustments:

- `--pfe-navigation--Width` which controls the width of the nav items in the black bar
- Then the width of the tray contents uses that var too, but the class `..pfe-navigation-item__tray--container`  resets the value of that variable to `calc(1200px - var(--pfe-navigation--MaxWidth))`
