### ISSUE TITLE
Line height on accordion button is too tall

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#717]
![image](https://user-images.githubusercontent.com/456863/73767450-76393e80-4745-11ea-8245-76b247c2abef.png)

**Comment by kylebuch8** [comment]
@starryeyez024 Can you provide more detail on what it should be and if there is a variable we can be using?

**Comment by starryeyez024** [comment]
Idk, I put in a request with @coreyvickery to update the mockups to show text wrapping to two lines
https://xd.adobe.com/spec/3e62e93c-8338-4f31-5040-3b81f0ed5c71-4853/screen/d1bad3d6-75c3-455a-a26f-c135517ed131/Accordion-light

**Comment by castastrophe** [comment]
Line-height is now 26.4px on the main branch: https://happy-galileo-ea79c4.netlify.app/elements/pfe-accordion/demo/
