### ISSUE TITLE
pfe-icon-panel storybook view is not working correctly

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#719]
The list of background colors has incorrect values of "light" and "dark", should be "lighter" and "darker".

Most of the colors have no effect. The accent color changes something but it changes the icon instead of the circle, which is what the label says
![image](https://user-images.githubusercontent.com/456863/73806574-dbb61b00-4797-11ea-9fbf-967618f7182e.png)

**Comment by mwcz** [comment]
Are you sure this is an issue with pfe-icon? The screenshot shows pfe-icon-panel.

**Comment by starryeyez024** [comment]
Fair point! I've updated name of this issue.

**Comment by starryeyez024** [comment]
FWIW the icon seems to be an on-load problem, as the attribute is only missing on first paint. Then if you choose any icon, the attribute is added correctly. 

![icon-panel](https://user-images.githubusercontent.com/456863/74063705-03d39300-49bf-11ea-9a88-30d203453508.gif)

**Comment by castastrophe** [comment]
Fixed in https://github.com/patternfly/patternfly-elements/pull/867
