### ISSUE TITLE
pfe-content-set does not cascade the on="dark" attribute

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#720]
![image](https://user-images.githubusercontent.com/456863/73874532-ad7d1d80-4821-11ea-8a28-557572e570b4.png)

As such, text that is inside the content set is the wrong color:
![image](https://user-images.githubusercontent.com/456863/73874545-b5d55880-4821-11ea-93b4-9d815eb98aff.png)

**Comment by kylebuch8** [comment]
@starryeyez024 I think this should be a pretty simple fix. I think the logic in the code is not updating the "on" property if there is an "on" attribute that's already set.
