### ISSUE TITLE
pfe-icon needs a function to opt out of default icon set

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#723]
If a developer wanted to load an icon set that had the prefix of "web", they cannot do so. That namespace is taken, and there's no way to opt out of that or all the rh icons that come with pfe-icon.

**Comment by mwcz** [comment]
Since icon sets are objects created specifically for pfe-icon, and are not pre-existing things with pre-existing names, why can't the developer simply name the icon set something else?

**Comment by starryeyez024** [comment]
Hey @mwcz, I need to update the icons in the pfe-navigation, which uses pfe-icon. The icons on access.redhat.com are out of date from what brand has created. 
![image](https://user-images.githubusercontent.com/456863/74063074-b60a5b00-49bd-11ea-8671-7b5c1cc21112.png)
vs 
![image](https://user-images.githubusercontent.com/456863/74063084-bacf0f00-49bd-11ea-9d10-0f596ccef35b.png) 
for example.

Currently redhat.com is referencing icons from access.redhat.com and I cannot override them. This could be remedied by your team updating the icons, but it could be a continuous burden on you all to upkeep icons for what we need. 

Beyond that, someone who does not work at Red Hat may want to use all the fancy functionality in pfe-icon but not load icons they don't need, and also not have a cross-origin reference to access.redhat.com.

I think in general it would make sense to allow folks to opt out of the default set of icons, and then provide their own (even with the same namespace).

**Comment by castastrophe** [comment]
To opt out, you can now add this before your components are loaded and no font sets will be defined:
```
window.PfeConfig = {
  IconSets: []
};
```

There is no cost to having the predefined fonts available because it doesn't make any fetch's unless it is used on the page.
