### ISSUE TITLE
pfe-tab outline color is really dark on light context

### ISSUE THREAD

**Issue by eyevana** [patternfly/patternfly-elements#729]
![image](https://user-images.githubusercontent.com/55894965/74182016-e1808600-4c07-11ea-91c0-48bc20d733dc.png)

**Comment by coreyvickery** [comment]
@starryeyez024 Easy fix, let's remove any styling and go with whatever the default browser style is.

**Comment by coreyvickery** [comment]
Opening a new issue for all changes to pfe-tabs. Closing.
