### ISSUE TITLE
[question] Ensuring design documentation reflects component flexibility

### ISSUE THREAD

**Issue by cybtachyon** [patternfly/patternfly-elements#748]
(Sorry if I missed it somewhere)

What processes / tools do we have in place to ensure the designs or documentation for the component reflect the reality of what is easily modifiable on the component?

**Goal: To ensure designers default to creating design variants that preserve the improved velocity of using a pre-built design kit and pattern library.**

_Example use case: We're using PatternFly components but the product owners require that all buttons must be a specific shade of blue. This is an easy global CSS styling change, so when our designers make that update there's no problem for the developers. Conversely, the product owners require all buttons change border in a specific manner on hover. The designers make the update but the developers realize they have to write a React event intercept to make it happen which is much more time consuming and annoying use of resources._

**Directed Questions:**
1. Are we simply assuming designers should not be modifying Patternfly components at all?
1. Is there a documentation template that requires entering the existing classes & easily modifiable CSS, or some sort of design consideration that makes this easy to discover?
1. Are we just ensuring design symbols have all of the easily modifiable attributes such as color, font size etc.?

**Comment by castastrophe** [comment]
Each component in PatternFly Elements includes a list of the variable hooks you can use in their READMEs too! https://github.com/patternfly/patternfly-elements/blob/master/elements/pfe-card/README.md
