### ISSUE TITLE
Generator can produce a JS file with invalid variable names

### ISSUE THREAD

**Issue by mwcz** [patternfly/patternfly-elements#764]
@wesruv found this one.

For instance, if you tell the generator you want slots named `message-on` and `message-off`, it will generate the following JS:

```js
this.message-on = this.querySelector([slot="${this.tag}--message-on"]);
this.message-off = this.querySelector([slot="${this.tag}--message-off"]);
```

Hyphens aren't allowed in dot (`.`) notation, so the generator should either produce:

```js
this["message-on"] = this.querySelector([slot="${this.tag}--message-on"]);
this["message-off"] = this.querySelector([slot="${this.tag}--message-off"]);
```

Or substitute invalid characters with valid characters:

```js
this.message_on = this.querySelector([slot="${this.tag}--message-on"]);
this.message_off = this.querySelector([slot="${this.tag}--message-off"]);
```

*Or* warn during the generator that invalid characters were entered.  Or some combination of the above.

**Comment by wesruv** [comment]
Related to this, but maybe a different ticket:
When I was trying to figure out why it wouldn't build `npm run live-demo` only reported that there was a problem with running `gulp dev`, I believe I got a similar message for `npm run dev`

```
@patternfly/pfe-switch: npm ERR! code ELIFECYCLE
@patternfly/pfe-switch: npm ERR! errno 1
@patternfly/pfe-switch: npm ERR! @patternfly/pfe-switch@1.0.0-prerelease.39 dev: `../../node_modules/.bin/gulp dev`
@patternfly/pfe-switch: npm ERR! Exit status 1
@patternfly/pfe-switch: npm ERR!
@patternfly/pfe-switch: npm ERR! Failed at the @patternfly/pfe-switch@1.0.0-prerelease.39 dev script.
@patternfly/pfe-switch: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
@patternfly/pfe-switch: npm ERR! A complete log of this run can be found in:
@patternfly/pfe-switch: npm ERR!     /home/wesruv/.npm/_logs/2020-02-26T13_54_51_920Z-debug.log
```
If I were a bit smarter I might have checked the log file... but I think ideally that error would show up in the output.

**Comment by castastrophe** [comment]
@wesruv To debug the above, we'd need the full build output, that's just a subset.  I've found that typically the error does show up but it does it during the build, not at the end.  I would say to alter error messaging, we could open a separate issue and look at including some of the error compiling packages that would collate errors and report them in a set.

**Comment by castastrophe** [comment]
https://github.com/patternfly/patternfly-elements/pull/768/files
