### ISSUE TITLE
pfe-cta: demo page updates

### ISSUE THREAD

**Issue by castastrophe** [patternfly/patternfly-elements#775]
A few issues to resolve on the demo page:

-  Card layout gets too skinny on smaller screens:
<img width="642" alt="Screen Shot 2020-03-06 at 10 13 33 AM" src="https://user-images.githubusercontent.com/1840295/76095984-43c47080-5f93-11ea-90df-043a00ad4975.png">

**Comment by starryeyez024** [comment]
It looks good now! https://deploy-preview-761--happy-galileo-ea79c4.netlify.com/elements/pfe-cta/demo/

Closing this issue.
