### ISSUE TITLE
Discussion about renaming theme classes

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#782]
Currently in the theme layer in the advanced-theme.css file, we are printing classes such as .pfe-headline-1, .pfe-headline-2, etc. 

The point has been made that using the numbers can confuse the typographical styles with the standard heading tags, such as `<h1>`, `<h2>` and so on.

The proposed idea is to convert the classes to utilize the greek naming conventions we are using for the variables, so .pfe-headline-alpha, .pfe-headline-beta, etc. 

Please forgive discussion points that have happened elsewhere, I'm just hoping to summarize the issue here in the public space of the project to capture pros & cons.  

I've made [a copy of the internal spreadsheet where we were comparing use cases and naming conventions for visibility](https://docs.google.com/spreadsheets/d/1Lo567BQlg5132liUNQdFNGPZ0JqPKfYGoylKz3OAzW4/edit?usp=sharing).

**Comment by starryeyez024** [comment]
Also: the theme update with these proposed changes would be a major release (4.0.0) signifying a breaking change.

**Comment by samlinville** [comment]
Would it be possible to just standardize around the existing PF4 naming conventions? To me, the greek letter hierarchy isn't very intuitive either.

**Comment by markcaron** [comment]
[Military alphabet](https://en.wikipedia.org/wiki/NATO_phonetic_alphabet) is an option.

Abstraction away from the standard, numbered levels is essential so that design system sizing isn't conflated with HTML heading levels. This also gives us greater flexibility and a wider range in assigning sizes (not just h1-h6).

Any abstraction away from the obvious 1, 2, 3, etc. will take some time to get used to. We won't be able to help that aspect.

**Comment by samlinville** [comment]
<img width="990" alt="Screen Shot 2020-03-12 at 11 01 06 AM" src="https://user-images.githubusercontent.com/3967272/76535153-ceecad00-6450-11ea-97f4-274f95f2bd3e.png">

Is there a reason that this taxonomy wouldn't work, though? It doesn't use numbered levels to imply h1-h6, but it also doesn't use an abstracted naming convention that requires people to think about it.

**Comment by starryeyez024** [comment]
> Any abstraction away from the obvious 1, 2, 3, etc. will take some time to get used to. We won't be able to help that aspect.

+1  The abstracted naming is intentional, so that should you need a size between small and medium, you've got somewhere to go.  Notice that between a few repos on redhat.com and probably customer portal too, we already have a mix'n'match between the semantic heading size and the naming convention. 

![image](https://user-images.githubusercontent.com/456863/76585475-d9409280-64b4-11ea-8a13-287cf3f3d35f.png)

So the argument is that it only adds to the confusion to have `<h2 class="pfe-headline-1">`

I should have linked to this in the original post, but see also 
https://github.com/castastrophe/wc-theming-standards/issues/3

Maybe one thing I should have highlighted is the theme contains:
1. variables 
2. placeholders
3. classes 

At each level *could* be an opportunity to change naming conventions, since you can leverage all of these from other projects. 

## For example..  

### Variables
```css
  // for responsive sizing:
  --pfe-theme--base--text: 16px;
  --pfe-theme--base--heading: 17px;
  --pfe-theme--base--heading-lg: 18px;

  --pfe-theme--font-size--xxl: calc(1.92  * var(--pfe-theme--base--heading-lg, 25px));
  --pfe-theme--font-size--xl: calc(1.6  * var(--pfe-theme--base--heading-lg, 25px));
  --pfe-theme--font-size--alpha: calc(1.44 * var(--pfe-theme--base--heading-lg, 25px));
  --pfe-theme--font-size--beta: calc(1.4 * var(--pfe-theme--base--heading, 20px));
  --pfe-theme--font-size--gamma: calc(1.2 * var(--pfe-theme--base--heading, 20px));
  --pfe-theme--font-size--delta: 20px;
  --pfe-theme--font-size--epsilon: calc(0.9  * 20px);
  --pfe-theme--font-size--zeta: calc(0.8  * 20px);
  --pfe-theme--font-size--eta: calc(1.11 * var(--pfe-theme--base--text, 18px));
  --pfe-theme--font-size--theta: var(--pfe-theme--base--text, 18px);

```

### Placeholders
```
%pfe-display--lg {
    font-family: var(--#{$prefix}-theme--font-family--heading, unquote(map-deep-get($font, font-family, heading)));
    font-size:   var(--#{$prefix}-theme--font-size--alpha, map-deep-get($font, font-size, alpha));
    line-height: var(--#{$prefix}-theme--line-height--alpha, map-deep-get($font, line-height, alpha));
    font-weight: var(--#{$prefix}-theme--font-weight--alpha, map-deep-get($font, font-weight, alpha));
}

%pfe-display--md {
    font-family: var(--#{$prefix}-theme--font-family--heading, unquote(map-deep-get($font, font-family, heading)));
    font-size:   var(--#{$prefix}-theme--font-size--beta, map-deep-get($font, font-size, beta));
    line-height: var(--#{$prefix}-theme--line-height--beta, map-deep-get($font, line-height, beta));
    font-weight: var(--#{$prefix}-theme--font-weight--beta, map-deep-get($font, font-weight, beta));
}
%pfe-display--sm {...}
%pfe-display--xs {...}
```

### (Semantic?) Classes
```
.pfe-headline {
  font-family: "RedHatDisplay", "Overpass", Overpass, Helvetica, Arial, sans-serif;
  font-family: var(--pfe-theme--font-family--heading, "RedHatDisplay", "Overpass", Overpass, Helvetica, Arial, sans-serif);
  font-size: calc(1.44 * 18px);
  font-size: var(--pfe-theme--font-size--alpha, calc(1.44 * var(--pfe-theme--base--heading-lg, 25px)));
  line-height: 1.3;
  line-height: var(--pfe-theme--line-height--alpha, 1.3);
  font-weight: 400;
  font-weight: var(--pfe-theme--font-weight--alpha, 400); }

.pfe-title {
  font-family: "RedHatDisplay", "Overpass", Overpass, Helvetica, Arial, sans-serif;
  font-family: var(--pfe-theme--font-family--heading, "RedHatDisplay", "Overpass", Overpass, Helvetica, Arial, sans-serif);
  font-size: calc(1.4 * 17px);
  font-size: var(--pfe-theme--font-size--beta, calc(1.4 * var(--pfe-theme--base--heading, 20px)));
  line-height: 1.3;
  line-height: var(--pfe-theme--line-height--beta, 1.3);
  font-weight: 400;
  font-weight: var(--pfe-theme--font-weight--beta, 400); }

.pfe-subheadline {...}
.pfe-subsection {...}
```

**Comment by castastrophe** [comment]
Love the idea is semantic classes and abstracted variables. The custom properties layer could be simplified using:

```css
 --pfe-theme-- FontSize--text: 16px;
 --pfe-theme--FontSize--heading:  17px;
  
--pfe-theme--FontSize--sm: 0.8;
--pfe-theme--FontSize--md: 1;
--pfe-theme--FontSize--lg: 1.2;
```

Where font size can be a ratio of base value and rendered as either em or a calc of base:

```css
body {
  font-size: var(--pfe-theme--FontSize--text, 16px);
}

.pfe-headline {
  font-size: calc(1em * var(--pfe-theme--FontSize--lg, 1.2));
```

```css
.pfe-headline {
  font-size: calc(var(--pfe-theme-- FontSize--text, 16px) * var(--pfe-theme--FontSize--lg, 1.2));
```

**Comment by castastrophe** [comment]
Also plus one to @samlinville’s sm, md, lg proposal. Keep the theme levels simple and if we need more sizes, just code them based on the base value.

**Comment by castastrophe** [comment]
I think 6 system sizes are more than enough (anything else would likely be a one-off or contextual difference); how about `xs, sm, md, lg, xl, xxl`. I do feel that as a designer trying to interpret meaning from the variables that 2xl, 3xl, etc is confusing.

**Comment by samlinville** [comment]
FWIW, I think folks on the UXD end are pretty comfortable with the 2xl, 3xl, etc... patterns, we've been using those for awhile in PF.

**Comment by castastrophe** [comment]
I think both systems need to be open to evolution based with the goal of creating a great experience for developers and designers. In clothing sizes, 2XL is the same size as XL in length but with more girth. Is that what we're trying to convey in the sizing? XXL is the size above XL on clothing. Some things to ponder.

**Comment by castastrophe** [comment]
Bootstrap is also using an `xs` to `xl` model https://getbootstrap.com/docs/4.4/utilities/spacing/

**Comment by LyndseyR** [comment]
Brainstorming here with some placeholder numbers
```
.pfe-headline-xl: 40px
.pfe-headline-lg: 36px
.pfe-headline-md: 32px
.pfe-headline-sm: 28px
.pfe-headline-xs: 24px
.pfe-headline-xxs: 20px
```
As the design system evolves what if we decide to support 34px font headlines what variable would that become? My understanding of abstract naming is it allows for flexibility for adding in between values. Although greek alphabet is less common it still poses the same problem. What is in between `beta` and `gamma`? Neither options are truly abstract. Do we need to solve for true abstraction? Or try our best to keep headlines to 6 values and we'd update the value not add an additional class? 

As far as designers, it's been eons since I've done any design work but I'm assuming they're thinking "headline = 32px" the name of what we chose doesn't matter to them. They just want to see the page rendering at 32px size so the naming becomes something that the developers should be comfortable with.

**Comment by castastrophe** [comment]
If a request came down to add a new value in between the others, there are a few questions I would ask:

1- How often and in what context will this new value be used?
2- Could this be a one-off that could be built into a component instead using the base font value and a multiplier?
3- Could this new value replace an existing value in the stack for better visual consistency and clarity for the user?

In my experience, requests to create new in-between values are often better served by replacing existing ones or end up not being reused. That’s why I would propose:

```css
--pfe-theme--FontSize--headline--base: 28px;

--pfe-theme--FontSize--headline--xxl: 1.4;
--pfe-theme--FontSize--headline--xl: 1.3;
--pfe-theme--FontSize--headline--lg: 1.14;
--pfe-theme--FontSize--headline--md: 1;
--pfe-theme--FontSize--headline--sm: .86;
--pfe-theme--FontSize--headline--xs: .7;
```
