### ISSUE TITLE
We don't have a light saturated theme

### ISSUE THREAD

**Issue by LyndseyR** [patternfly/patternfly-elements#783]
Our system currently supports the themes 
```
light
dark 
saturated
```
Currently saturated works in tangent with dark themes and is applied on backgrounds that have red, teal etc colors. If we were to set a custom color that's bright we don't have anything in our design system that supports this. 

Example below is a background-color of hotpink. Black text passes but our default cta blue of #06C does not.

<img width="1363" alt="light-theme-black-passes" src="https://user-images.githubusercontent.com/20518754/76449565-973c2180-63cc-11ea-93c8-f6c54e8ae95c.png">

<img width="1383" alt="Light-theme-blue-fails" src="https://user-images.githubusercontent.com/20518754/76449575-9b683f00-63cc-11ea-9757-6bc61b0b2bd2.png">

Question to answer
1. Do we need to add support for `light saturated` themes?
1a followup. If the answer is no then should we reconsider naming `saturated` to `dark-saturated` since it specifically applies to dark colors?

**Comment by castastrophe** [comment]
Can you share a few real world examples that require a light - saturated theme?

**Comment by castastrophe** [comment]
Closing this for now but feel free to re-open if we find we still need this!
