### ISSUE TITLE
Add horizontal scroll to pfe-tabs 

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#784]
![image](https://user-images.githubusercontent.com/456863/76647352-0c296b80-6533-11ea-89f5-eb8d97d6342b.png)

**Comment by coreyvickery** [comment]
@starryeyez024 XD artboard link:

https://xd.adobe.com/spec/3e62e93c-8338-4f31-5040-3b81f0ed5c71-4853/screen/d352fdfe-9717-4e82-859f-d573b13cf99b/Box-Tabs-horizontal-overflow-light-theme-

**Comment by starryeyez024** [comment]
@coreyvickery  to document use cases for this need

**Comment by coreyvickery** [comment]
Opening a new issue for all changes to pfe-tabs. Closing this issue.

https://github.com/patternfly/patternfly-elements/issues/814
