### ISSUE TITLE
pfe-tabs panel should match active tab-header background

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#798]
Here's an example where the background color of the page is something other than white
![image](https://user-images.githubusercontent.com/456863/77334724-90ca7580-6cfb-11ea-8d7a-740849b688f4.png)

The tab panel should be white instead of transparent.

**Comment by starryeyez024** [comment]
cc @coreyvickery just tagging you to add mockups for this, or to consolidate this into the bigger pfe-tabs issue, in which case you can close this one. Thanks!

**Comment by coreyvickery** [comment]
@starryeyez024 I think in the case of the BG not being white, the Box Tabs component (we used to call them Secondary) should regress to the Open Tabs component (Primary). When that happens, the content area BG remains transparent, like the Tabs component on the home page.

**Comment by coreyvickery** [comment]
Opening a new issue for all changes to pfe-tabs. Closing.
