### ISSUE TITLE
consolidate gulpfiles into a single root gulpfile

### ISSUE THREAD

**Issue by mwcz** [patternfly/patternfly-elements#80]
And since some elements have customized their gulpfiles, this issue involves creating a scheme for hooking into the root gulpfile with custom tasks, or common tasks shared among a few elements.

**Comment by mwcz** [comment]
Just brainstorming here:

`gulpfile.js` at the root contains all the universal task implementations.  Have the gulpfile accept optional arguments, the names of the elements to build.  If run with no arguments, it builds all elements.

```bash
npm run build # runs gulp and builds all elements
npm run build -- rh-card # builds only rh-card
npm run build -- rh-card rh-cta rh-button # builds all three
```

Create a `scripts/gulp/` dir.  In it, put any common but not universal gulp tasks, one per file.  For example, the merge task which is used by most (but not all!) elements to embed the HTML and CSS/SCSS into the JS output file, would look as follows:

**scripts/gulp/merge.js**
```js
import gulp from "../wherever/is/gulp.js";

export default gulp
    .src(`elements/${rhelement}/src/${rhelement}.js`)
    .pipe(replace(/* ... implementation here ... */))
    .pipe(gulp.dest(`elements/${rhelement}/${rhelement}.js`));
```

Each rhelement should have a `gulptasks.js` file (name up for argument):

```js
export merge from "../../scripts/gulp/merge.js";
```

And that file could also export any other tasks the particular rhelement needs.  It could also export its own unique task instead of re-exporting an existing common one.  Not sure if this should be a recommended practice, or if we should enforce all tasks being added to `scripts/gulp/`...

In this way, the rhelement can hook into the root gulpfile with customizations.

**Comment by kylebuch8** [comment]
@mwcz Can we close this? I think we've accomplished this with the gulpfile factory.

**Comment by mwcz** [comment]
Yeah, good catch, this is done.
