### ISSUE TITLE
pfe-clipboard: Copy to clipboard functionality

### ISSUE THREAD

**Issue by kylebuch8** [patternfly/patternfly-elements#803]
I've used https://clipboardjs.com/ in the past to create this as a Polymer component. We should build a PatternFly Element that wraps this functionality.

Functionality
- We need a clipboard button with a clipboard icon
- The clipboard button should have a target to copy
- Successfully copying something should trigger a tooltip on the clipboard button
- The tooltip text should be provided as an attribute so it can be translated

**Comment by diwanshi** [comment]
@kylebuch8 do you think we can just use Web API [Navigator.clipboard](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard) to build this component instead of writing a wrapper around clipboard.js?

**Comment by starryeyez024** [comment]
https://patternflyelements.com/elements/pfe-clipboard/demo/
