### ISSUE TITLE
pfe-codeblock: A component to display formatted and prettified code

### ISSUE THREAD

**Issue by kylebuch8** [patternfly/patternfly-elements#804]
[code-prettify](https://github.com/google/code-prettify) is a great library to base this component on. It's used on code.google.com and stackoverflow.com.

[prism.js](https://prismjs.com/) is also a good library and it's used in a bunch of places.

Functionality (besides what the code library already provides)
- Show or hide line numbers
- Specific list of languages that we'd support
- Provide two themes: one light, one dark

**Comment by ajacobs21e** [comment]
https://github.com/patternfly/patternfly-design/issues/836 the design story is still ongoing. If those 3 requirements are not included in the design reqs, @kylebuch8 can you add them or talk to @mcarrano please? Thanks!

**Comment by kylebuch8** [comment]
@ajacobs21e Done. https://github.com/patternfly/patternfly-design/issues/836#issuecomment-614022144
