### ISSUE TITLE
pfe-tabs all changes

### ISSUE THREAD

**Issue by coreyvickery** [patternfly/patternfly-elements#814]
# Tabs

## Themes
> There are two themes available to choose from, light and dark.

### Light theme
<img width="1300" alt="Themes - Light" src="https://user-images.githubusercontent.com/45767595/83658687-8c8ac600-a590-11ea-969c-32b7ae7c6a3a.png">

### Dark theme
<img width="1300" alt="Themes - Dark" src="https://user-images.githubusercontent.com/45767595/83658704-901e4d00-a590-11ea-9a26-3b6528774ef9.png">

---

# Styles and interactions

### Horizontal
https://xd.adobe.com/spec/3e62e93c-8338-4f31-5040-3b81f0ed5c71-4853/screen/6b20a57b-62d0-4973-ab9f-a10c004eabfe/Open-Tabs-horizontal-light-theme-

### Vertical
https://xd.adobe.com/spec/3e62e93c-8338-4f31-5040-3b81f0ed5c71-4853/screen/d6810288-96ce-42e5-9bb0-c7091d0c04c3/Open-Tabs-vertical-light-theme-

### Typography
- Labels: Red Hat Text, Regular, 16pt / 24 (1.5)

### Color
- Default and Focus text label: #6a6e73
- Hover text label: #151515
- Hover highlight bar: #b8bbbe, 3px height
- Active text label: #151515
- Active highlight bar: #e00, 3px height
- Anchor (bottom or left line): #d2d2d2

### Alignment and spacing
- Alignment: Horizontal component is always centered
- Text label spacing (top, right, bottom, left): 16px, 32px, 16px, 32px
- No spacing in between when Hover and Active highlight bars are touching

**Default**
<img width="1300" alt="IX - Primary, Open, Wind variant, light theme, default" src="https://user-images.githubusercontent.com/45767595/83681682-bce25c80-a5b0-11ea-88e0-3c66b346ddfc.png">

**Focus**
<img width="1300" alt="IX - Primary, Open, Wind variant, light theme, focus" src="https://user-images.githubusercontent.com/45767595/83681692-c075e380-a5b0-11ea-8d3b-06b33aa880ae.png">

**Hover**
<img width="1300" alt="IX - Primary, Open, Wind variant, light theme, hover" src="https://user-images.githubusercontent.com/45767595/83681701-c370d400-a5b0-11ea-91b5-35fb3e91bcbf.png">

**Active/Pressed**
<img width="1300" alt="IX - Primary, Open, Wind variant, light theme, active pressed" src="https://user-images.githubusercontent.com/45767595/83681712-c5d32e00-a5b0-11ea-87ba-83c8b05a8662.png">

### Horizontal
https://xd.adobe.com/spec/3e62e93c-8338-4f31-5040-3b81f0ed5c71-4853/screen/33071de0-c23d-4a90-bef3-6159d06505ba/Box-Tabs-horizontal-light-theme-

### Vertical
https://xd.adobe.com/spec/3e62e93c-8338-4f31-5040-3b81f0ed5c71-4853/screen/75692581-7698-4aae-b361-35530ed0d163/Box-Tabs-vertical-light-theme-

### Typography
- Labels: Red Hat Text, Regular, 16pt / 24 (1.5)

### Color
- Default and Focus text label: #6a6e73
- Default and Focus tab BG: #f0f0f0
- Hover text label: #151515
- Hover highlight bar: #b8bbbe, 3px height
- Active text label: #151515
- Active label tab BG: #fff
- Active highlight bar: #e00, 3px height
- Anchor (bottom or left line): #d2d2d2

### Alignment and spacing
- Content area: No left, right, and bottom borders below component around content panel
- Alignment: Flush left, no 1px pipe on left
- 1px pipe in between all tabs, but not to the right of the last one: #d2d2d2
- Tab spacing (top, right, bottom, left): 16px, 32px, 16px, 32px

**Default**
<img width="1300" alt="IX - Secondary, Box, Earth variant, light theme, default" src="https://user-images.githubusercontent.com/45767595/83681948-30846980-a5b1-11ea-8005-ff06d522b5e4.png">

**Focus**
<img width="1300" alt="IX - Secondary, Box, Earth variant, light theme, focus" src="https://user-images.githubusercontent.com/45767595/83681958-3417f080-a5b1-11ea-97d8-5966bd0d5ae6.png">

**Hover**
<img width="1300" alt="IX - Secondary, Box, Earth variant, light theme, hover" src="https://user-images.githubusercontent.com/45767595/83681970-38dca480-a5b1-11ea-8749-64e53e2ac43c.png">

**Active/Pressed**
<img width="1300" alt="IX - Secondary, Box, Earth variant, light theme, active pressed" src="https://user-images.githubusercontent.com/45767595/83681976-3c702b80-a5b1-11ea-9e47-949e3564addd.png">

### Horizontal
https://xd.adobe.com/spec/3e62e93c-8338-4f31-5040-3b81f0ed5c71-4853/screen/d626e1c7-1e33-4edd-b131-f5effbc91968/Open-Tabs-horizontal-dark-theme-

### Vertical
https://xd.adobe.com/spec/3e62e93c-8338-4f31-5040-3b81f0ed5c71-4853/screen/d7231502-dd43-4cd6-a8a9-8c9ee0fc3439/Open-Tabs-vertical-dark-theme-

### Typography
- Labels: Red Hat Text, Regular, 16pt / 24 (1.5)

### Color
- Default and Focus text label: #d2d2d2
- Hover text label: #fff
- Hover highlight bar: #b8bbbe, 3px height
- Active text label: #fff
- Active highlight bar: #e00, 3px height
- Anchor (bottom or left line): #6a6e73

### Alignment and spacing
- Content area: No left, right, and bottom borders below component around content panel
- Alignment: Flush left, no 1px pipe on left
- 1px pipe in between all tabs, but not to the right of the last one: #d2d2d2
- Tab spacing (top, right, bottom, left): 16px, 32px, 16px, 32px

**Default**
<img width="1300" alt="IX - Primary, Open, Wind variant, dark theme, default" src="https://user-images.githubusercontent.com/45767595/83682064-64f82580-a5b1-11ea-8626-e8354f03d0ae.png">

**Focus**
<img width="1300" alt="IX - Primary, Open, Wind variant, dark theme, focus" src="https://user-images.githubusercontent.com/45767595/83682081-688bac80-a5b1-11ea-84d3-1c2468990030.png">

**Hover**
<img width="1300" alt="IX - Primary, Open, Wind variant, dark theme, hover" src="https://user-images.githubusercontent.com/45767595/83682088-6c1f3380-a5b1-11ea-8c9e-dbd0d87b50f4.png">

**Active/Pressed**
<img width="1300" alt="IX - Primary, Open, Wind variant, dark theme, active pressed" src="https://user-images.githubusercontent.com/45767595/83682100-704b5100-a5b1-11ea-8ded-4479ffa4654b.png">

### Horizontal
https://xd.adobe.com/spec/3e62e93c-8338-4f31-5040-3b81f0ed5c71-4853/screen/6c296f8d-1ebf-4ff9-91ed-dee05a44960d/Box-Tabs-horizontal-dark-theme-

### Vertical
https://xd.adobe.com/spec/3e62e93c-8338-4f31-5040-3b81f0ed5c71-4853/screen/79e758b8-36f9-49f4-afa2-a1ba46063454/Box-Tabs-vertical-dark-theme-

### Typography
- Labels: Red Hat Text, Regular, 16pt / 24 (1.5)

### Color
- Default and Focus text label: #d2d2d2
- Default and Focus tab BG: #3c3f42
- Hover text label: #fff
- Hover highlight bar: #b8bbbe, 3px height
- Active text label: #fff
- Active label tab BG: #151515
- Active highlight bar: #e00, 3px height
- Anchor (bottom or left line): #6a6e73

### Alignment and spacing
- Content area: No left, right, and bottom borders below component
- Alignment: Flush left, no 1px pipe on left
- 1px pipe in between all other tabs: #6a6e73
- Tab spacing (top, right, bottom, left): 16px, 32px, 16px, 32px

**Default**
<img width="1300" alt="IX - Secondary, Box, Earth variant, dark theme, default" src="https://user-images.githubusercontent.com/45767595/83682253-ac7eb180-a5b1-11ea-8ac5-79184f71e7eb.png">

**Focus**
<img width="1300" alt="IX - Secondary, Box, Earth variant, dark theme, focus" src="https://user-images.githubusercontent.com/45767595/83682262-b0aacf00-a5b1-11ea-912e-219dc5454014.png">

**Hover**
<img width="1300" alt="IX - Secondary, Box, Earth variant, dark theme, hover" src="https://user-images.githubusercontent.com/45767595/83682268-b56f8300-a5b1-11ea-99ad-fa202df6c003.png">

**Active/Pressed**
<img width="1300" alt="IX - Secondary, Box, Earth variant, dark theme, active pressed" src="https://user-images.githubusercontent.com/45767595/83682279-b99ba080-a5b1-11ea-9d43-53a1f56a96f8.png">

---

# Tab order
> The order in which a user moves focus from one control to another by pressing the Tab key.

![Tab order - Animation](https://user-images.githubusercontent.com/45767595/83685439-ab03b800-a5b6-11ea-9fbc-be5d84d15671.gif)

---

# Overflow scroll button
> Applied to the Horizontal component when labels are too long and get cut off. There's no specific breakpoint for when a Scroll button appears, it depends on the number of labels and the character count of each label.

## Horizontal, light theme
https://xd.adobe.com/spec/3e62e93c-8338-4f31-5040-3b81f0ed5c71-4853/screen/d334e6a9-c875-4ed3-90da-2cd9f60a31a2/Open-Tabs-horizontal-overflow-light-theme

<img width="868" alt="Horiz scroll button - Primary, Open, Wind, light theme" src="https://user-images.githubusercontent.com/45767595/83662301-4d12a880-a595-11ea-8193-dabf4427d67e.png">

### Angle or arrow styles
- Default and Focus: #151515
- Hover and Active/Pressed: #06c
- Disabled: #d2d2d2
- Pipe or divider: #d2d2d2

### Button BG styles
- Adopts whatever the BG color is that the component is placed on

**Default**
<img width="868" alt="IX - Overflow button, light theme, default" src="https://user-images.githubusercontent.com/45767595/83687226-76ddc680-a5b9-11ea-9fb7-5bc847462d9b.png">

**Focus**
<img width="868" alt="NA" src="https://user-images.githubusercontent.com/45767595/83693005-19e70e00-a5c3-11ea-9aba-e0c3992a887c.png">

- The Scroll button can't be focused, only each individual Tab in the tab order instead

**Hover**
<img width="868" alt="IX - Overflow button, light theme, hover" src="https://user-images.githubusercontent.com/45767595/83687236-7ba27a80-a5b9-11ea-89d1-8c4cca23e627.png">

**Active/Pressed**
<img width="868" alt="IX - Overflow button, light theme, active pressed" src="https://user-images.githubusercontent.com/45767595/83687241-7e04d480-a5b9-11ea-81bd-0c89ace47aff.png">

## Horizontal, dark theme
https://xd.adobe.com/spec/3e62e93c-8338-4f31-5040-3b81f0ed5c71-4853/screen/68c6d18d-354c-4a2d-9f6f-228c28b25fd0/Open-Tabs-horizontal-overflow-dark-theme

<img width="868" alt="Horiz scroll button - Primary, Open, Wind, dark theme" src="https://user-images.githubusercontent.com/45767595/83662669-d5914900-a595-11ea-9e3b-4fdd67260efb.png">

### Angle or arrow styles
- Default and Focus: #fff
- Hover and Active/Pressed: #2b9af3
- Disabled: #6a6e73
- Pipe or divider: #6a6e73

**Default**
<img width="868" alt="IX - Overflow button, dark theme, default" src="https://user-images.githubusercontent.com/45767595/83687686-20bd5300-a5ba-11ea-820c-8a993a770db6.png">

**Focus**
<img width="868" alt="NA" src="https://user-images.githubusercontent.com/45767595/83693005-19e70e00-a5c3-11ea-9aba-e0c3992a887c.png">

- The Scroll button can't be focused, only each individual Tab in the tab order instead

**Hover**
<img width="868" alt="IX - Overflow button, dark theme, hover" src="https://user-images.githubusercontent.com/45767595/83687711-287cf780-a5ba-11ea-8ad3-4bd19b62bf1c.png">

**Active/Pressed**
<img width="868" alt="IX - Overflow button, dark theme, active pressed" src="https://user-images.githubusercontent.com/45767595/83687730-2fa40580-a5ba-11ea-9147-a82e6ce07041.png">

### Default state
- Text labels or Tabs are organized from left to right
- When Overflow buttons appear, the left button is disabled and the right button is active

### Active/Pressed
- When the right Overflow button is clicked on or pressed, text labels or Tabs move from right to left
- When the left Overflow button is clicked on or pressed, text labels or Tabs move from left to right

## Tab order

![Tab order Overflow animation](https://user-images.githubusercontent.com/45767595/83692570-48181e00-a5c2-11ea-8144-ab52940cd96f.gif)

- As a user presses the Tab key, the focus indicator will move from left to right outlining all Tabs until it reaches the end of the tab order where the Overflow button will become disabled

---

# Breakpoints
> When screens get smaller, the spacing between the component and the content panel reduces.

### Desktop
<img width="1140" alt="Breakpoints - Primary, Open, Wind, horizontal - Desktop" src="https://user-images.githubusercontent.com/45767595/83669282-4a1cb580-a59f-11ea-97bd-a386db1ff2f5.png">

### Tablet, landscape
<img width="1140" alt="Breakpoints - Primary, Open, Wind, horizontal - Tablet, landscape" src="https://user-images.githubusercontent.com/45767595/83669289-4e48d300-a59f-11ea-9943-2cf96a8cd190.png">

### Tablet, portrait
<img width="1140" alt="Breakpoints - Primary, Open, Wind, horizontal - Tablet, portrait" src="https://user-images.githubusercontent.com/45767595/83669297-5143c380-a59f-11ea-9722-3326f68c60bf.png">

## Open, Primary, Wind variant, vertical
> The vertical component occupies 20% of the total layout width on all breakpoints.

### Desktop
<img width="1140" alt="Breakpoints - Primary, Open, Wind, vertical - Desktop" src="https://user-images.githubusercontent.com/45767595/83669002-df6b7a00-a59e-11ea-98d8-78b8e45c0ff8.png">

### Tablet, landscape
<img width="1140" alt="Breakpoints - Primary, Open, Wind, vertical - Tablet, landscape" src="https://user-images.githubusercontent.com/45767595/83669333-63bdfd00-a59f-11ea-84bf-c4ba14c44ff3.png">

### Tablet, portrait
<img width="1140" alt="Breakpoints - Primary, Open, Wind, vertical - Tablet, portrait" src="https://user-images.githubusercontent.com/45767595/83669343-69b3de00-a59f-11ea-9c0c-301e28e71a7e.png">

### Desktop
<img width="1140" alt="Breakpoints - Secondary, Box, Earth, horizontal - Desktop" src="https://user-images.githubusercontent.com/45767595/83669047-ee522c80-a59e-11ea-8f26-e571f54d5c02.png">

### Tablet, landscape
<img width="1140" alt="Breakpoints - Secondary, Box, Earth, horizontal - Tablet, landscape" src="https://user-images.githubusercontent.com/45767595/83669368-79332700-a59f-11ea-8a6a-642e10dda727.png">

### Tablet, portrait
<img width="1140" alt="Breakpoints - Secondary, Box, Earth, horizontal - Tablet, portrait" src="https://user-images.githubusercontent.com/45767595/83669376-7cc6ae00-a59f-11ea-8670-53d6d236daf6.png">

## Secondary, Box, Earth variant, vertical
> The vertical component occupies 20% of the total layout width on all breakpoints.

### Desktop
<img width="1140" alt="Breakpoints - Secondary, Box, Earth, vertical - Desktop" src="https://user-images.githubusercontent.com/45767595/83669086-fad68500-a59e-11ea-9c57-33567ad940b4.png">

### Tablet, landscape
<img width="1140" alt="Breakpoints - Secondary, Box, Earth, vertical - Tablet, landscape" src="https://user-images.githubusercontent.com/45767595/83669422-923bd800-a59f-11ea-930f-2571eb00a456.png">

### Tablet, portrait
<img width="1140" alt="Breakpoints - Secondary, Box, Earth, vertical - Tablet, portrait" src="https://user-images.githubusercontent.com/45767595/83669432-95cf5f00-a59f-11ea-98a2-0251030657a4.png">

**Spacing legend**
https://www.patternfly.org/v4/design-guidelines/styles/spacers

---

# Content panel
> The area underneath a Tab set is where content can be placed.

### Primary, Open, Wind variant

**Transparent BG**
<img width="1300" alt="BG placement - Primary, Open, Wind variant" src="https://user-images.githubusercontent.com/45767595/83666921-a8479980-a59b-11ea-8d1e-1907c6bd5d31.png">

- Primary, Open, Wind variant Tabs have transparent content panel BGs where the content sits on top of BGs
- Includes both Horizontal and Vertical components

### Secondary, Box, Earth variant

**Opaque BG**
<img width="1300" alt="BG placement - Secondary, Box, Earth variant" src="https://user-images.githubusercontent.com/45767595/83666936-ada4e400-a59b-11ea-8911-e618cd60d747.png">

- Secondary, Box, Earth variant Tabs have opaque content panel BGs
- Light theme always contains a white (#fff) content panel BG
- Dark theme always contains a black (#151515) content panel BG
- Includes both Horizontal and Vertical components

## Borders
<img width="1300" alt="Borders" src="https://user-images.githubusercontent.com/45767595/83668244-a4b51200-a59d-11ea-85c1-c3d000b390f3.png">

- Secondary, Box, Earth variant Tabs don't have a border encircling the component and content panel

---

# Usage/Accessibility

### Primary, Open, Wind variant, light theme

**Guidelines**
- Can't be used on BGs darker than #f0f0f0 (4.5:1)

<img width="817" alt="Screen Shot 2020-04-01 at 2 12 34 PM" src="https://user-images.githubusercontent.com/45767595/78171743-ecdf7900-7422-11ea-912a-327ef129c758.png">

### Secondary, Box, Earth variant, light theme

**Guidelines**
- Use on white/light gray BGs only

<img width="1091" alt="Screen Shot 2020-04-02 at 4 45 32 PM" src="https://user-images.githubusercontent.com/45767595/78298955-63eb3f00-7501-11ea-9215-5b66e5ec010c.png">

### Primary, Open, Wind variant, dark theme

**Guidelines**
- Can't be used on BGs lighter than #4f5255 (5.2:1)

<img width="810" alt="Screen Shot 2020-04-01 at 2 20 05 PM" src="https://user-images.githubusercontent.com/45767595/78172357-e998bd00-7423-11ea-88c3-83a608a807b8.png">

### Secondary, Box, Earth variant, dark theme

**Guidelines**
- Use on black/dark BGs only

<img width="1092" alt="Screen Shot 2020-04-02 at 4 42 04 PM" src="https://user-images.githubusercontent.com/45767595/78298862-24bcee00-7501-11ea-915d-b961c17bd976.png">

**Active tab**
- Tab on left/in position 1 is always the Active tab

**Tab order**
- Always moves left to right (for non-RTL languages) or top to bottom
- User input/Tab key should focus Active tab/first tab on left (or the top) and then cycle through content in the content area (LTR or top-to-bottom)
- Focus will target next tab/second tab after leaving the content area

---

# Spacing

### Horizontal
<img width="1140" alt="Spacing - Primary, Open, Wind variant, horizontal" src="https://user-images.githubusercontent.com/45767595/83673376-a256b600-a5a5-11ea-9f57-321b118b43ad.png">

### Horizontal, overflow
<img width="1140" alt="Spacing - Primary, Open, Wind variant, horizontal, overflow" src="https://user-images.githubusercontent.com/45767595/83688913-20be5280-a5bc-11ea-92c4-5c16ecb3180c.png">

### Vertical
<img width="1140" alt="Spacing - Primary, Open, Wind variant, vertical" src="https://user-images.githubusercontent.com/45767595/83674081-dcc05300-a5a5-11ea-8ea7-08db8695c20d.png">

### Horizontal
<img width="1140" alt="Spacing - Secondary, Box, Earth variant, horizontal" src="https://user-images.githubusercontent.com/45767595/83674572-05484d00-a5a6-11ea-9856-9c4c40966625.png">

### Horizontal, overflow
<img width="1140" alt="Spacing - Secondary, Box, Earth variant, horizontal, overflow" src="https://user-images.githubusercontent.com/45767595/83674679-0c6f5b00-a5a6-11ea-9f46-9cb80516b1a5.png">

### Vertical
<img width="1140" alt="Spacing - Secondary, Box, Earth variant, vertical" src="https://user-images.githubusercontent.com/45767595/83674868-1db86780-a5a6-11ea-9026-8316d5439649.png">

**Spacing legend**
https://www.patternfly.org/v4/design-guidelines/styles/spacers

**Comment by kylebuch8** [comment]
@coreyvickery I just want to take a minute and let you know that these look _awesome_.

**Comment by coreyvickery** [comment]
@starryeyez024 @kylebuch8 Added more notes covering typography.

**Comment by starryeyez024** [comment]
wowza, thank you @coreyvickery !

**Comment by coreyvickery** [comment]
@starryeyez024 @kylebuch8 Added some additional notes about Scrolling button.

**Comment by starryeyez024** [comment]
[Story to work on padding & color](https://rally1.rallydev.com/#/270861059696d/detail/userstory/378976493960)

**Comment by coreyvickery** [comment]
@starryeyez024 @kylebuch8 Added more documentation regarding the vertical component minimum width and the interior spacing between the component and panel/content area.

**Comment by castastrophe** [comment]
https://rally1.rallydev.com/#/detail/userstory/378976493960?fdp=true

**Comment by coreyvickery** [comment]
@castastrophe @alazzara I have finalized changes to this issue. Nothing will be modified moving forward.

**Comment by castastrophe** [comment]
There's still more to do in this story so reopening this issue

**Comment by castastrophe** [comment]
> Tab order
> Always moves left to right (for non-RTL languages) or top to bottom

Do you want me to do any discovery on how to detect RTL?  Is that out of scope? cc @starryeyez024

**Comment by starryeyez024** [comment]
Is the "more work to do" captured in this issue or are there other items? https://github.com/patternfly/patternfly-elements/issues/1378

@castastrophe  I think the RTL support is a great idea but can be a separate issue. The way I was thinking about these github issues was the big ones like this (814) that @coreyvickery opens with all the specs is great for when we are first building the component. And if we miss anything small, or if there are requests later to change things, then we open new smaller issues for those things.  We can always re-reference the XD files if those are helpful.

**Comment by castastrophe** [comment]
Makes sense, I'll close and open an issue for RTL support tomorrow.
