### ISSUE TITLE
[AT] add tests to pfelement on calling connectedCallback more than once

### ISSUE THREAD

**Issue by mwcz** [patternfly/patternfly-elements#83]
Per the spec, connectedCallback can be run more than once, so we should make sure all components work well in that scenario.

I'm guessing connectedCallback can be called again if an already-connected element is removed from its place in the DOM, then re-inserted somewhere else.

There should be tests for this.

**Comment by bennypowers** [comment]
This shouldn't be relevant after pfe-2.0
