### ISSUE TITLE
Typo in pfe-icon README - Incorrect Closing Tag

### ISSUE THREAD

**Issue by kelsS** [patternfly/patternfly-elements#833]
one of the current examples of pfe-icon:
```html
<pfe-icon icon="rh-leaf"></pfe-card>
```

Closing tag needs to be updated to ```</pfe-icon>``` for all instances in the README of pfe-icon structure.

**Comment by castastrophe** [comment]
@kelsS Great catch!  I made the fix here: https://github.com/patternfly/patternfly-elements/pull/840 Would you like to code review?
