### ISSUE TITLE
[pfe-tabs] [IE11] Dynamically added tabs are not clickable

### ISSUE THREAD

**Issue by karangarg45** [patternfly/patternfly-elements#836]
If a tab is added dynamically say after a timeout or based on the response of an api then the tab is not clickable on **IE11** browser. Works fine on chrome and firefox.

Example repo here
https://codesandbox.io/s/quiet-microservice-wvmsf?file=/src/App.js

**Comment by kylebuch8** [comment]
It looks like all browsers but IE add the `aria-controls` and `aria-labeledby` attributes.

![image](https://user-images.githubusercontent.com/330256/79867761-dd61a900-83ac-11ea-855d-5fa775474cda.png)

Those attributes are needed for showing tabs. I'll have to investigate why they aren't being added.

**Comment by kylebuch8** [comment]
I found that the mutation observer was not firing in IE11 when a new tab is added to the light DOM. Updating the mutation observer configuration to `{ childList: true, **subtree: true** }`, fixes the issue.
