### ISSUE TITLE
Bug with the pfe-tabs-history functionality & Firefox

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#839]
On this page, the secondary nav should link you to the teal band, then the events band right underneath it. It works as expected in chrome.
http://origin-www-cms.redhat.com/en/fts-demo#worldevents

However in firefox, the first click on the nav takes you to the pfe-content-set, the second click takes you to the proper hash link.

![pfe-tabs-history-FF-bug](https://user-images.githubusercontent.com/456863/79880895-9381be80-83be-11ea-9bb0-9a014aeaac38.gif)

**Comment by castastrophe** [comment]
@kylebuch8 Is this fixed now?

**Comment by starryeyez024** [comment]
yes this was fixed with https://github.com/patternfly/patternfly-elements/pull/841
