### ISSUE TITLE
Include PF sass variables as reference (instead of redefining)

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#848]
Currently pfe-sass redefines sass variables:
![image](https://user-images.githubusercontent.com/456863/80721626-70e15b00-8acc-11ea-9412-e823a14a2a4f.png)

Instead it should pull them in from the node_modules/@patternfly/patternfly/sass-utilities directory
![image](https://user-images.githubusercontent.com/456863/80721774-9d957280-8acc-11ea-8250-5d2f7687e363.png)

**Comment by starryeyez024** [comment]
@coreyvickery @dcaryll  it's worth noting that the red colors in Patternfly are:
```scss
$pf-color-red-100:               #c9190b !default;
$pf-color-red-200:               #a30000 !default;
$pf-color-red-300:               #7d1007 !default;
$pf-color-red-400:               #470000 !default;
$pf-color-red-500:               #2c0000 !default;
```
So the only place `#ee0000` will live is the [redhat-theme](https://gitlab.corp.redhat.com/uxdd/redhat-theme/blob/dev/src/maps/_ui-elements.scss#L24)

**Comment by castastrophe** [comment]
+1 this code update appears in the design token fork for one example
