### ISSUE TITLE
pfe-accordion:  Add ability to direct link / open specific accordions

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#859]
It is a desirable feature to be able to link directly to a specific accordion in a set.

You could do this two ways, by URL, or by attribute. Assuming you have 3 accordions, Larry, Curly and Moe, you could open the 3rd accordion like this:

```html 
<pfe-accordion selected-index="3">
```

And/or by adding support for pfe-tabs-history attribute to pfe-accordion (which would be great because pfe-content-set can also upgrade to accordions).  So a URL like redhat.com/my-page?tabs=moe should also open the 3rd accordion.

**Comment by kylebuch8** [comment]
To see how we're already doing this with tabs on page load, review this code from tabs.

In the `_init` method, we're checking to see if there's something in the URL.
https://github.com/patternfly/patternfly-elements/blob/master/elements/pfe-tabs/src/pfe-tabs.js#L259

`_init` calls this:
https://github.com/patternfly/patternfly-elements/blob/master/elements/pfe-tabs/src/pfe-tabs.js#L454

Then if you follow the logic in `_init`, you'll see how we open a tab if we found a match
https://github.com/patternfly/patternfly-elements/blob/master/elements/pfe-tabs/src/pfe-tabs.js#L268

**Comment by starryeyez024** [comment]
Related issue https://github.com/patternfly/patternfly-elements/issues/350

**Comment by castastrophe** [comment]
Any opinion about how we handle multiple open accordions?
