### ISSUE TITLE
Remove demo files from NPM publishing on all elements and themes

### ISSUE THREAD

**Issue by markcaron** [patternfly/patternfly-elements#86]
Remove demo files from NPM publishing on all elements and themes

**Comment by mwcz** [comment]
Going even further, we should remove tests and *maybe* even the `src/` dir from the published artifact, leaving only the things necessary for production use.

**Comment by kylebuch8** [comment]
I'm not sure about removing the demo files. I think it makes sense to leave them so developers can refer to them if they want. I use the README files and example files in node_modules directories all the time.

**Comment by mwcz** [comment]
Closing, but can be re-opened if anyone is interested.
