### ISSUE TITLE
pfe-accordion

### ISSUE THREAD

**Issue by coreyvickery** [patternfly/patternfly-elements#877]

**Comment by coreyvickery** [comment]
# Accordion
> Accordions are used to deliver a lot of content in a small space, allowing the user to expand and collapse the component to show or hide information.

## Themes

### Light theme
<img width="1220" alt="Light theme" src="https://user-images.githubusercontent.com/45767595/82099348-27e8f380-96d5-11ea-902a-59f8045a8f9a.png">

https://xd.adobe.com/spec/3e62e93c-8338-4f31-5040-3b81f0ed5c71-4853/screen/d1bad3d6-75c3-455a-a26f-c135517ed131/Accordion-light-theme

### Dark theme
<img width="1220" alt="Dark theme" src="https://user-images.githubusercontent.com/45767595/82099355-2c151100-96d5-11ea-995c-223ea1672320.png">

https://xd.adobe.com/spec/3e62e93c-8338-4f31-5040-3b81f0ed5c71-4853/screen/6f381695-556c-443c-9424-bd30f0fe3f69/Accordion-dark-theme

---

# Anatomy

## Collapsed

### Light theme
<img width="1300" alt="Anatomy - Light theme, collapsed" src="https://user-images.githubusercontent.com/45767595/82165984-121a3080-9885-11ea-9dd1-7f75624eaf2b.png">

### Dark theme
<img width="1300" alt="Anatomy - Dark theme, collapsed" src="https://user-images.githubusercontent.com/45767595/82166003-1a726b80-9885-11ea-9275-cbcf7c9f41d5.png">

**Guidelines**
- Section/panel titles are always Red Hat Display font
- Collapsed carets/arrows are always pointed right

## Expanded

### Light theme
<img width="1300" alt="Anatomy - Light theme, expanded" src="https://user-images.githubusercontent.com/45767595/82167009-58bd5a00-9888-11ea-98a4-c97c68f744c5.png">

### Dark theme
<img width="1300" alt="Anatomy - Dark theme, expanded" src="https://user-images.githubusercontent.com/45767595/82166999-50651f00-9888-11ea-9b8e-87d2329dfb6d.png">

**Guidelines**
- Section/panel titles are always Red Hat Display font
- Expanded carets/arrows are always pointed down
- If a text box is used, the max width is always 750px when the component is wider

---

# Styles

## Light theme

### Typography
- Text label: Red Hat Display, Medium, 20pt / 30 (1.5), $pf-color-black-900 (#151515)

### Color
- Lines: $pf-color-black-300 (#d2d2d2)
- Angle/caret icon: $pf-color-black-900 (#151515)
- Hover and Active/Pressed state panel backgrounds: $pf-color-black-200 (#f0f0f0)

<img width="1220" alt="Light theme - Hover + active" src="https://user-images.githubusercontent.com/45767595/82100010-b4e07c80-96d6-11ea-8bef-700b8f40c70d.png">

### Highlight details
- Width: 3px
- Color: #e00
- Shape: Rectangular
- Other: Overlaps container edges and border

<img width="500" alt="Highlight details light theme" src="https://user-images.githubusercontent.com/45767595/82100028-be69e480-96d6-11ea-96de-d12b6c0a13c3.png">

## Dark theme

### Typography
- Text label: Red Hat Display, Medium, 20pt / 30 (1.5), $pf-color-white (#fff)

### Color
- Lines: $pf-color-black-600 (#6a6e73)
- Angle/caret icon: $pf-color-white (#fff)
- Hover and Active/Pressed state panel backgrounds: $pf-color-black-800 (#3c3f42)

<img width="1220" alt="Dark theme - Hover + active" src="https://user-images.githubusercontent.com/45767595/82100033-c3c72f00-96d6-11ea-8a31-95f5e972e5d1.png">

### Highlight details
- Width: 3px
- Color: #e00
- Shape: Rectangular
- Other: Overlaps container edges and border

<img width="500" alt="Highlight details dark theme" src="https://user-images.githubusercontent.com/45767595/82100049-cc1f6a00-96d6-11ea-97b0-3097aacd3059.png">

---

# Functionality

## Light theme

### Exterior section expanded
<img width="1590" alt="Light - Ext section expanded" src="https://user-images.githubusercontent.com/45767595/82111051-153fe000-9710-11ea-9bfe-12d2a2dcef06.png">

### Exterior sections stacked
<img width="1590" alt="Light - Ext sections stacked" src="https://user-images.githubusercontent.com/45767595/82111055-1bce5780-9710-11ea-9976-fdcb0be1d3df.png">

### Nested sections collapsed
<img width="1590" alt="Light - Nested section collapsed" src="https://user-images.githubusercontent.com/45767595/82111056-1f61de80-9710-11ea-8c73-45743090a02f.png">

### Nested section expanded
<img width="1590" alt="Light - Nested section expanded" src="https://user-images.githubusercontent.com/45767595/82111058-225ccf00-9710-11ea-8c86-a4cafa071531.png">

### Nested sections stacked
<img width="1590" alt="Light - Nested sections stacked" src="https://user-images.githubusercontent.com/45767595/82111060-2557bf80-9710-11ea-8576-b937154eb470.png">

## Dark theme

### Exterior section expanded
<img width="1590" alt="Dark - Ext section expanded" src="https://user-images.githubusercontent.com/45767595/82110468-c93f6c00-970c-11ea-9014-09b7d4076abc.png">

### Exterior sections stacked
<img width="1590" alt="Dark - Ext sections stacked" src="https://user-images.githubusercontent.com/45767595/82110465-c6dd1200-970c-11ea-8d8c-6310b95f48e6.png">

### Nested sections collapsed
<img width="1590" alt="Dark - Nested section collapsed" src="https://user-images.githubusercontent.com/45767595/82110462-c3498b00-970c-11ea-9696-12a23174c311.png">

### Nested section expanded
<img width="1590" alt="Dark - Nested section expanded" src="https://user-images.githubusercontent.com/45767595/82110460-c0e73100-970c-11ea-987e-7bdff7affd89.png">

### Nested sections stacked
<img width="1590" alt="Dark - Nested sections stacked" src="https://user-images.githubusercontent.com/45767595/82110458-bd53aa00-970c-11ea-9c2e-eb33c1d89d60.png">

---

# Interaction states

## Light theme

### Default
<img width="1220" alt="Light theme - Default" src="https://user-images.githubusercontent.com/45767595/82100936-16a1e600-96d9-11ea-9d55-0f94e6704a2f.png">

### Focus
> A focus indicator is added around the entire panel background.
<img width="1220" alt="Light theme - Focus" src="https://user-images.githubusercontent.com/45767595/82100945-19044000-96d9-11ea-8b5c-410bc5243e0f.png">

### Hover
> Changes the panel background color to $pf-color-black-200 (#f0f0f0).
<img width="1220" alt="Light theme - Hover" src="https://user-images.githubusercontent.com/45767595/82100950-1bff3080-96d9-11ea-83ba-de2817b4f3d4.png">

### Active/Pressed
> A focus indicator is added around the entire panel background and the background color remains the same as the Hover state.
<img width="1220" alt="Light theme - Active + Pressed" src="https://user-images.githubusercontent.com/45767595/82100954-1efa2100-96d9-11ea-88c3-95b05246dfaa.png">

## Dark theme

### Default
<img width="1220" alt="Dark theme - Default" src="https://user-images.githubusercontent.com/45767595/82100984-33d6b480-96d9-11ea-8d6a-167ec45ac96c.png">

### Focus
> A focus indicator is added around the entire panel background.
<img width="1220" alt="Dark theme - Focus" src="https://user-images.githubusercontent.com/45767595/82100989-36390e80-96d9-11ea-9c15-1d8cd9ddf8e4.png">

### Hover
> Changes the panel background color to $pf-color-black-800 (#3c3f42).
<img width="1220" alt="Dark theme - Hover" src="https://user-images.githubusercontent.com/45767595/82100990-389b6880-96d9-11ea-9be0-b1ec61646ed5.png">

### Active/Pressed
> A focus indicator is added around the entire panel background and the background color remains the same as the Hover state.
<img width="1220" alt="Dark theme - Active + Pressed" src="https://user-images.githubusercontent.com/45767595/82100998-3c2eef80-96d9-11ea-9425-30ab1df96fb4.png">

---

# Breakpoints

## Light theme

https://xd.adobe.com/spec/3e62e93c-8338-4f31-5040-3b81f0ed5c71-4853/screen/08cbc1c7-3fed-488e-b386-5a6fc8d3b1af/Accordion-light-theme-overflows

### Desktop
> If a text box is used, the max width is 750px in large breakpoints like Desktop and Tablet. Text labels that are written longer will break to two lines in all breakpoints.
<img width="1220" alt="Light theme - Desktop" src="https://user-images.githubusercontent.com/45767595/82102885-f83ee900-96de-11ea-9e09-22eb296324f2.png">

### Tablet, landscape
<img width="1220" alt="Light theme - Tablet, landscape" src="https://user-images.githubusercontent.com/45767595/82102889-fc6b0680-96de-11ea-83c3-24883f9816c5.png">

### Tablet, portrait
<img width="1220" alt="Light theme - Tablet, portrait" src="https://user-images.githubusercontent.com/45767595/82102894-fffe8d80-96de-11ea-9a0d-2f8827cb0e2a.png">

### Mobile, landscape
<img width="1220" alt="Light theme - mobile, landscape" src="https://user-images.githubusercontent.com/45767595/82102902-04c34180-96df-11ea-981f-fd271af41bcb.png">

### Mobile, portrait
<img width="1220" alt="Light theme - mobile, portrait" src="https://user-images.githubusercontent.com/45767595/82102911-0ab92280-96df-11ea-9d52-636dacd79fa1.png">

## Dark theme

https://xd.adobe.com/spec/3e62e93c-8338-4f31-5040-3b81f0ed5c71-4853/screen/9f13d138-fe7c-4b15-8b0f-30ff0403c32e/Accordion-dark-theme-overflows

### Desktop
> If a text box is used, the max width is 750px in large breakpoints like Desktop and Tablet. Text labels that are written longer will break to two lines in all breakpoints.
<img width="1220" alt="Dark theme - Desktop" src="https://user-images.githubusercontent.com/45767595/82109497-69dd5e00-9704-11ea-933e-0c262ca960c7.png">

### Tablet, landscape
<img width="1220" alt="Dark theme - Tablet, landscape" src="https://user-images.githubusercontent.com/45767595/82109539-d0fb1280-9704-11ea-8af6-78910b2d2535.png">

### Tablet, portrait
<img width="1220" alt="Dark theme - Tablet, portrait" src="https://user-images.githubusercontent.com/45767595/82109541-d7898a00-9704-11ea-9693-527f0c8ffda4.png">

### Mobile, landscape
<img width="1220" alt="Dark theme - mobile, landscape" src="https://user-images.githubusercontent.com/45767595/82109546-df492e80-9704-11ea-89d9-272872996ea7.png">

### Mobile, portrait
<img width="1220" alt="Dark theme - mobile, portrait" src="https://user-images.githubusercontent.com/45767595/82109547-e53f0f80-9704-11ea-9e5b-ad60e537fa62.png">

---

# Accessibility

If an Accordion is collapsed:

Key | Interaction
------------ | -------------
Tab | Focuses the top panel and moves down the tab order
Enter or Space | Expands an Accordion

![Collapsed-animation](https://user-images.githubusercontent.com/45767595/82161672-afb53600-986c-11ea-958f-6b68a4eb07c8.gif)

If an Accordion is expanded:

Key | Interaction
------------ | -------------
Tab | Focuses the next interactive element in the tab order
Shift + Tab | Focuses the previous interactive element in the tab order or the panel background
Enter or Space | Expands an Accordion

![Expanded-animation](https://user-images.githubusercontent.com/45767595/82161674-b479ea00-986c-11ea-8e61-e4b311f56911.gif)

---

# Usage

## Light theme
<img width="1300" alt="Light theme usage" src="https://user-images.githubusercontent.com/45767595/82164636-9073d400-987f-11ea-9c5d-79cbe4ee4bb6.png">

### Guidelines
- Use on white or light gray backgrounds only, no darker than #f0f0f0
- Don't use on backgrounds that are the same color or darker than the border color
- Switch themes if it's used on an opposing background color

## Dark theme
<img width="1300" alt="Dark theme usage" src="https://user-images.githubusercontent.com/45767595/82164646-9e295980-987f-11ea-97d2-8516deefd850.png">

### Guidelines
- Use on black or dark gray backgrounds only, no lighter than #3c3f42
- Don't use on backgrounds that are the same color or lighter than the border color
- Switch themes if it's used on an opposing background color

---

# Spacing

## Light theme

### Exterior sections collapsed
<img width="1140" alt="Accordion - Ext sections collapsed - Desktop - Light theme" src="https://user-images.githubusercontent.com/45767595/82169335-2fec9300-988f-11ea-9cd1-be6434c4493b.png">

### Exterior section expanded
<img width="1152" alt="Accordion - Ext section expanded - Desktop - Light theme" src="https://user-images.githubusercontent.com/45767595/82169340-324eed00-988f-11ea-8487-c9279290cf2e.png">

### Nested sections collapsed
<img width="1152" alt="Accordion - Int sections collapsed - Desktop - Light theme" src="https://user-images.githubusercontent.com/45767595/82169343-3549dd80-988f-11ea-934c-d7cb1653a216.png">

### Nested sections expanded
<img width="1152" alt="Accordion - Int section expanded - Desktop - Light theme" src="https://user-images.githubusercontent.com/45767595/82169349-37ac3780-988f-11ea-9f77-94a7bacdac6a.png">

## Dark theme

### Exterior sections collapsed
<img width="1220" alt="Accordion - Ext sections collapsed - Desktop - Dark theme" src="https://user-images.githubusercontent.com/45767595/82169216-ce2c2900-988e-11ea-824a-71d94c695b9c.png">

### Exterior section expanded
<img width="1220" alt="Accordion - Ext section expanded - Desktop - Dark theme" src="https://user-images.githubusercontent.com/45767595/82169224-d4baa080-988e-11ea-8a36-507497ff1561.png">

### Nested sections collapsed
<img width="1220" alt="Accordion - Int sections collapsed - Desktop - Dark theme" src="https://user-images.githubusercontent.com/45767595/82169231-d97f5480-988e-11ea-8930-8cc2a5063be9.png">

### Nested sections expanded
<img width="1220" alt="Accordion - Int section expanded - Desktop - Dark theme" src="https://user-images.githubusercontent.com/45767595/82169238-dc7a4500-988e-11ea-9fab-aca7dd3d500d.png">

**Spacing legend**
https://www.patternfly.org/v4/design-guidelines/styles/spacers

**Comment by coreyvickery** [comment]
@starryeyez024 Updated:

- Highlight bar design details (thin left bar in Expanded state)
- In Expanded state, changed the spacing of `Body copy` under the `Section label` from 16px to 24px

**Comment by coreyvickery** [comment]
@starryeyez024 Updated:

- Nested container BG colors need to match parent container BG colors, included examples in Styles section

**Comment by starryeyez024** [comment]
@coreyvickery  can we include disclosure styles here too?

**Comment by starryeyez024** [comment]
@coreyvickery @dcaryll  hey! We are working on prioritizing things and I came across this issue. I think, based on what I know of the component and the styles reflected here that we are 95% good on these styles. Things I think that could look like they need adjustments are the borders and the spacing so I'm adding some notes:

CSS by default uses miter joints (45° angles) for all borders. Hence, to achieve squared joints (90° angles) for any border, we'd have to use hacks like an inner box-shadow, pseudo elements or multiple linear-gradients.  Though this is very difficult to see, and probably not worth the time & attention right now.
https://codepen.io/tobiasbueschel/pen/yZOoMB?editors=1100 

I believe the [pfe-accordion](https://patternflyelements.com/elements/pfe-accordion/demo/) is using the correct spacing, however there's always extra pixels due to whitespace above the characters, built into the font. I don't think we want to get into the business of trying to offset for the extra space in the font, so these are actually correct / good as-is. 
![image](https://user-images.githubusercontent.com/456863/108402847-0c72c200-71ec-11eb-9521-6977c3c3a84b.png)

Is there anything I'm overlooking that needs attention re: accordions?

**Comment by castastrophe** [comment]
Linking to a few open issues regarding accordion styles:

- https://github.com/patternfly/patternfly-elements/issues/1002
- https://github.com/patternfly/patternfly-elements/issues/1397
- https://github.com/patternfly/patternfly-elements/issues/1265
-

**Comment by starryeyez024** [comment]
Excellent, thanks @castastrophe  for connecting the dots! :)

**Comment by coreyvickery** [comment]
@starryeyez024 I'm looking at this link for the most current Accordions in code.

https://patternflyelements.com/elements/pfe-accordion/demo/

I'd like us to be aware of Allie's issue below when it comes to styling updates. These styles can be seen in the design kit and are outlined in my long issue above. I think everything else is very close to being 1:1 except for these final styling pushes.

https://github.com/patternfly/patternfly/issues/3865

Let me know if we need to keep talking through anything at all.

**Comment by starryeyez024** [comment]
Closing this out since major work has been completed and there are smaller issues for remaining items.

**Comment by coreyvickery** [comment]
@starryeyez024 Can you post links to the other issues here?

**Comment by starryeyez024** [comment]
@coreyvickery  this is the primary one relating to styles: https://github.com/patternfly/patternfly-elements/issues/1002
