### ISSUE TITLE
Pfe-accordion: disclosure includes unwanted padding in the panel

### ISSUE THREAD

**Issue by Djfaucette** [patternfly/patternfly-elements#883]
![Screen Shot 2020-05-20 at 2 17 55 PM](https://user-images.githubusercontent.com/9581250/82488512-03629200-9aae-11ea-9bfc-fac30af8fc5b.png)
The right padding on accordion panels should match the left padding, but instead it looks like the padding is doubled. From a chat conversation:
```there’s a bug with the padding on the accordion panel .container, in terms of the specificity of the padding variable. It shouldnt have all that extra padding on the right when disclosure=true. And the last declaration in the accordion-panel.css tries to override it but it doesn’t succeed```

**Comment by castastrophe** [comment]
Key for the spacer blocks: <img width="220" alt="Screen Shot 2020-09-03 at 11 58 34 AM" src="https://user-images.githubusercontent.com/1840295/92138782-d5932600-eddc-11ea-81e9-83074445fcc3.png">

**Comment by castastrophe** [comment]
16px = the `container-padding` value; `pfe-var(container-padding)` is how you invoke it in the styles
