### ISSUE TITLE
[tools] Ability to watch pfe-sass & trigger recompile of all components

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#886]
Global changes to pfe-sass could affect all components; so when making global changes it might be ideal to have changes to those files trigger rebuilds of all other component files. 

Could be more ideal to have this as a separate command or flag so we can toggle it on/off as desired.

**Comment by castastrophe** [comment]
So many +1s!  Would love to add this feature!

**Comment by castastrophe** [comment]
I set this as `size: lg` because I've attempted this in the past and it was difficult since build tasks are independent of each other

**Comment by bennypowers** [comment]
from pfe-2 this should no longer be relevant, as we compile on-the-file in dev mode
