### ISSUE TITLE
Additional styles for pfe-dropdown

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#891]
- wind variant (no borders)
 - support for inline icon (plus arrow)

**Comment by coreyvickery** [comment]
Let me know what is needed here to complete or if I need to review.

**Comment by starryeyez024** [comment]
@kylebuch8  can you add clarity here or can we close this out?

@coreyvickery  this is the current dropdown: https://deploy-preview-932--happy-galileo-ea79c4.netlify.app/elements/pfe-dropdown/demo/

**Comment by coreyvickery** [comment]
@starryeyez024 Looks fine to me, sounds Kyle has the last word if this is done or not.

**Comment by starryeyez024** [comment]
closing, this is complete
