### ISSUE TITLE
Additional style updates for jump links

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#892]

**Comment by dcaryll** [comment]
@starryeyez024 to put themed version on demo site and @coreyvickery to review. If 👍 close this issue and open new issue for additional design requirements

**Comment by starryeyez024** [comment]
@coreyvickery  @dcaryll 
You can review here:
https://web-dev-drupal-abt.dev.a1.vary.redhat.com/en/test-jump-links-more-words
