### ISSUE TITLE
Updating how we include typographical styles in components

### ISSUE THREAD

**Issue by castastrophe** [patternfly/patternfly-elements#900]
Broad philosophical question: should we include a font-family variable in any component? Seems unlikely that authors would need to override it per component, and even if they did, i think they could target it with the selector and the theme var:
```
pfe-cta {
    --pfe-theme--font-family: "foo";
}
```

_Originally posted by @starryeyez024 in https://github.com/patternfly/patternfly-elements/pull/854_

**Comment by starryeyez024** [comment]
Here's the conclusions we came to in the [FED Infra meeting]:(https://docs.google.com/document/d/1OATDjKEhmDL9V5wVN3bucedgwYKQnR8rfsGOhUV35VU/edit#)

- If text is in the shadow dom, provide typography hook(s). Light dom text can inherit globals.
- Slotted content should not be styled by the component (i.e. card content area or jump-links-panel or accordion-panel .. etc)
- Pfe-base.css can continue to provide opt-in global light dom styles

**Comment by castastrophe** [comment]
Should we be gently offering broadcast colors to slotted content?

```
 ::slotted(*) {
    color: pfe-broadcasted(text);
  }
```

**Comment by starryeyez024** [comment]
> Should we be gently offering broadcast colors to slotted content?
> 
> ```
>  ::slotted(*) {
>     color: pfe-broadcasted(text);
>   }
> ```

 I think i like this idea better than having the theme do it
![image](https://user-images.githubusercontent.com/456863/83790330-0345c300-a666-11ea-86aa-d92c3d99b505.png)

Though we did talk about wanting to move all the typography classes from the theme to the pfe-base.css, maybe that handles it, and we don't need to put it on slotted?

**Comment by castastrophe** [comment]
Related to issue #918
