### ISSUE TITLE
Update attribute prefixing

### ISSUE THREAD

**Issue by kylebuch8** [patternfly/patternfly-elements#933]
# All components

### Global
pfe-g-\<name\>

#### Globally-scoped attributes
These would be protected and components would not be allowed to use the same attribute name. i.e., `pfe-g-context="dark"` (system adds on="dark" < styles queue off of this), `pfe-g-type="container"`

Should still avoid reusing these concepts on the component-level to mean something else; could result in conflicting styles or confusing author experience

#### component name (minus the pfe prefix)
Locally-scoped attributes; these are for use inside the component to communicate settings or content. i.e., card-color="accent" or icon-name="rh-atom"
BEM naming? c-color, c-name="rh-atom"
pfe-c-<name>: component-specific

**Comment by castastrophe** [comment]
Goal: Set up a structured method for defining attributes on a component.

How LitElement is doing this: https://lit-element.polymer-project.org/guide/properties

```
static get properties() {
  return { 
    propertyName: options
  };
}
```

What would go in our options?
- CMS-readable name or "title"
- Attribute name (should prefixing be built-in automatically so this value would be `disabled` and upgrade to `pfe-c-disabled`)?
- Observed boolean?

**Comment by kylebuch8** [comment]
In progress Codesandbox: https://codesandbox.io/s/pfe-constructor-properties-dwiwe

**Comment by markcaron** [comment]
Not sure if this is part of this specific issue, but the documentation site (https://patternfly.github.io/patternfly-elements/theme/) needs to be updated to match too. Still says `pfe-color`, etc.
