### ISSUE TITLE
pfe-navigation font size variable does not work

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#937]
## Description of the issue

pfe-navigation overrides it's own local variable for font size, such that `--pfe-navigation__trigger--FontSize` doesn't work (you cannot use it to influence the font size of the triggers).

![image](https://user-images.githubusercontent.com/456863/85054471-15495a80-b16a-11ea-8295-c97e65173cf1.png) 

### Impacted component(s)

- pfe-navigation

### Steps to reproduce

1. Go to https://deploy-preview-854--happy-galileo-ea79c4.netlify.app/elements/pfe-navigation/demo/
2. In web inspector:
```
html {
--pfe-navigation__trigger--FontSize: 30px;
}
//or
pfe-navigation {
--pfe-navigation__trigger--FontSize: 30px;
}
```
3. Notice that the font size of the triggers does not change

**Comment by castastrophe** [comment]
Rally: #US261998 https://rally1.rallydev.com/#/detail/userstory/399031068408
