### ISSUE TITLE
[feat] [pfe-navigation 1.x] | Mobile links need event hooks

### ISSUE THREAD

**Issue by castastrophe** [patternfly/patternfly-elements#945]
## Description of the requested feature

The mobile links such as login and language need to have their click events surfaced as a custom event so that external JS can hook into that event and intercept behavior if necessary.

Use case: Trying to fire a modal using the mobile link.

### Impacted component(s)

- pfe-navigation

**Comment by starryeyez024** [comment]
Associated Rally story: https://rally1.rallydev.com/#/detail/userstory/399031068408?fdp=true

**Comment by castastrophe** [comment]
Rally: #US261998 https://rally1.rallydev.com/#/detail/userstory/399031068408

**Comment by castastrophe** [comment]
cc @wesruv as this is might be needed for navigation 2.0 too
