### ISSUE TITLE
Pfe-band doesn't work correctly with Angular

### ISSUE THREAD

**Issue by grandemayta** [patternfly/patternfly-elements#952]
Hi guys,

I am working with Patternfly Elements and I having some issues with Angular integration.

### Impacted component(s)

- pfe-band

### Steps to reproduce
I created on Sandbox an Angular project with the pfe-band, you can find on this link:
https://codesandbox.io/s/pfe-band-patternfly-o8emc
### Expected behavior

We should see the patternfly band.

**Comment by castastrophe** [comment]
Hi @grandemayta, thank you again for opening this issue.  There is already an issue that covers this so I'm going to link them and close this one out.  The sandbox you provided will be very helpful as we continue to upgrade this component.  Would you mind adding any additional information you want to share in this issue instead? https://github.com/patternfly/patternfly-elements/issues/587
