### ISSUE TITLE
Discussion for 1.0: Prettier Config Updates

### ISSUE THREAD

**Issue by wesruv** [patternfly/patternfly-elements#967]
Our prettier file is currently blank (meaning we're using the defaults), if we wanted to make any changes, pre-1.0 is a good time.

Here are the defaults that I could find: https://prettier.io/docs/en/options.html

I propose we vote in the issue, put in a comment with current state and proposed state and we can :+1:  or :confused: to vote.

**Comment by wesruv** [comment]
I propose we up line length to at least 120, default is 80
https://prettier.io/docs/en/options.html#print-width

**Comment by mwcz** [comment]
Re 80-column lines: https://lkml.org/lkml/2020/5/29/1038 :smile:

**Comment by starryeyez024** [comment]
I don't mind/care, go for it :)
