### ISSUE TITLE
Release script should keep you on release branch

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#979]
## Description of the issue

The release script returns you to the master branch, but it should leave you on the release branch so you can commit the doc updates.

### Impacted 

- Tag release creation

### Steps to reproduce

https://docs.google.com/document/d/1lKAazbjIRYwCwpydewuAamxd8fIMLv2PSWw4r7uEC5I/edit?disco=AAAAEH_3quE

**Comment by castastrophe** [comment]
May I close this one out in favor of scripting the release?

**Comment by castastrophe** [comment]
Versioning discussion: https://docs.google.com/document/d/1u0f-dqm1RTexhsbflRkU0r-kruBRvJUZEUZMrCzkv1o/edit

**Comment by castastrophe** [comment]
Please re-open if you think this is still needed!  Thanks!
